<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta; ?>js/js_Transporte_buscaconductores.js"></script>
<div>
    <fieldset class="ui-widget ui-widget-content">
        <legend style="margin-left:5px"><span class="text1">EMPRESA </span></legend>
        <div class="contentForm">
        	<table class="tableContent" width="80%" border="0" cellpadding="0">
			    <tr>
				    <td>
						<span id="lblplaca" class="text1">Codigo </span>
					<td>
						<span id="lblpadron" class="text1">Razon Social </span>
					<td>	
						<span id="lblpadron" class="text1">RUC </span>
					<td>	
						&nbsp;
			    </tr>
				<tr>
					<td>
						<input type="hidden" name="txtcid" id="txtcid">
						<input type="text" name="txtccodigo" id="txtccodigo" class="cajaoff" readonly style="width:60px;">
					<td>	
						<input type="text" name="txtcnombre" id="txtcnombre" class="cajaoff" readonly style="width:520px;">
					<td>	
						<input type="text" name="txtcruc" id="txtcruc" class="cajaoff" readonly style="width:80px;">
					<td>	
						
				</tr>
			</table>    
        </div>
    </fieldset>
	<br/>
	<div id="divgridConductores"></div>
	<br style="clear:both">
	<div class="divButtons">
		<table border="0" cellpadding="0" cellspacing="0" width="100%">
			<tr>
				<td style="padding-left:5px">
					<input type="button" value="Nuevo" id="btncnuevo" style="width:150px; height:40px" />
					<!--<input type="button" value="Ver" id="btncver" style="width:150px; height:40px" />-->
					<input type="button" value="Cerrar" id="btnccierra" style="width:150px; height:40px" />
				</td>
				<td>
				</td>
			</tr>
		</table>
	</div>
</div>