<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta; ?>js/js_Mantgiro_buscar.js"></script>
<div>
    <fieldset class="ui-widget ui-widget-content">
        <legend style="margin-left:5px">Criterios:</legend>
        <div class="contentForm">
        <table class="tableContent">
          <tr>
          <td>
          <label>
          <input name="rdCritBusGiro" type="radio" value="C" checked/><b> Código</b>
          </label>
          </td>
          <td>
          <label>
          <input name="rdCritBusGiro" type="radio" value="N" /><b> Nombre</b>
          </label>
          </td>
          <td><input name="txtCritBusGiro" id="txtCritBusGiro" type="text" class="caja" size="30" maxlength="100" /></td>
          <td><input type="button" id="btnBusGiro" value="Buscar" /></td>
          </tr>
        </table>	    
        </div>
    </fieldset>	
    <br/>
    <div id="gridBusGiro"></div>
    <br/>
    <div class="divButtons">
        <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
        <td style="padding-left:5px">
        <input type="button" id="btnNuevoGiro" value="Nuevo Giro" />
        <input type="button" id="btnCerrarGiro" value="Cerrar Ventana" />
        </td>
        <td></td>
        </table>
    </div>
</div>
