<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Licendecjurada.js"></script>
<style>
input[type="text"]
{
	text-transform:uppercase;
}
</style>
<form id="frmlicendecjurada">
<input  type="hidden" name="accion" id="accion" value="<?php echo $this->accion ;?>" />
<input  type="hidden" name="idSolLice" id="idSolLice" value="<?php echo $this->idSolLice ;?>" />
    <div class="contentBoxMain">
    	  </fieldset>
		<br/>
    	<div id="contentTabsLeft" class="ui-tabs-left">
	        <ul>
	            <li style="width:62px" id="tab1">
                    <a href="#tabs-1">
                    <img src="<?php echo $this->ruta;?>img/icon_licencias.png"><div>S.DJ-I</div>
                    </a>
                </li>
	            <li style="width:62px" id="tab2">
                	<a href="#tabs-2">
                    <img src="<?php echo $this->ruta;?>img/icon_licencias.png"><div>S.DJ-II</div>
                    </a>
                </li>
                <li style="width:62px" id="tab3">
                	<a href="#tabs-3">
                    <img src="<?php echo $this->ruta;?>img/icon_licencias.png"><div>S.DJ-III</div>
                    </a>
                </li>
               
               
              	<div style="position:absolute; bottom:0;">
                    <div style="padding-bottom:15px">
                    <input type="button" id="btnSaveSol" value="Grabar" style="width:57px; height:40px; margin:5px 0 5px 0"/>
                    <input type="button" id="btnSalirSol" value="Cerrar" style="width:57px; height:40px; margin:5px 0 5px 0"/>
                    </div>
                </div>
              
	        </ul>            
	        <div id="tabs-1"><?php include("licendecjurada_1.phtml"); ?></div>
	        <div id="tabs-2"><?php include("licendecjurada_2.phtml"); ?></div>
	        <div id="tabs-3"><?php include("licendecjurada_3.phtml"); ?></div>
                 
		</div>
		
    </div>
</form>