<fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">VIII. Autorizaci&oacute;n del Anuncio y/o Toldos</legend>
    <div class="contentForm">
    <table class="tableContent" width="100%">
    <tr>
        <td><label><input id="chkAuto" type="checkbox"> <span>Autorizaci&oacute;n</span></label></td>
        <td><label><input id="chkReno" type="checkbox"> <span>Renovaci&oacute;n de Autorizaci&oacute;n</span></label></td>
        <td><label><input id="chkOtro" type="checkbox"/><span>Otros</span></label></td>
        <td><input id="txtOtro" class="cajaoff" readonly="readonly"  type="text" /></td>
       
      
    </tr>
    <tr>
        <td>
        <fieldset class="ui-widget ui-widget-content">
                 <legend style="margin-left:5px">&nbsp;Tipo de Anuncio</legend>
         <div class="contentForm">
        <select style="width:135px;" name="cmbTipAnun" id="cmbTipAnun" class="combo">
          <option>[Seleccione]</option>
        </select>
        </div>
        </fieldset>
        </td>
        <td>
        <fieldset class="ui-widget ui-widget-content">
                 <legend style="margin-left:5px">&nbsp;Tipo de iluminaci&oacute;n</legend>
         <div class="contentForm">
        <select style="width:135px;"  name="cmbTipIlum" id="cmbTipIlum" class="combo">
          <option>[Seleccione]</option>
        </select>
        <!--<div id="anuncio"></div>-->
        </div>
        </fieldset>
    	</td>
        <td>
        <fieldset class="ui-widget ui-widget-content">
             <legend style="margin-left:5px">&nbsp;Tipo de Autorizaci&oacute;n</legend>
        
        <div class="contentForm">
        <select style="width:135px;"  name="cmbTipAuto" id="cmbTipAuto" class="combo">
        <option>[Seleccione]</option>
        </select>
        <!--<div id="anuncio"></div>-->
        </div>
        </fieldset>
        </td> 
        <td>&nbsp;</td>
       
    </tr>
    <tr>
    <td colspan="5">
    <fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">&nbsp;Dimensiones</legend>
    <div class="contentForm">
        <table class="tableContent">
         <tr>
          <td><span id="lblTipAuto">LARGO (ml):</span></td>
          <td><span id="lblTipAuto">ANCHO (ml):</span></td>
          <td><span id="lblTipAuto">ALTURA (ml):</span></td>
          <td><span id="lblTipAuto">AREA (m2):</span></td>
          <td><span id="lblTipAuto">N&deg; DE CARAS :</span></td>

      </tr>
      <tr>
          <td><input name="txtlargo" id="txtlargo" type="text" class="caja" size="10" maxlength="4" /></td>       
          <td><input name="txtancho" id="txtancho" type="text" class="caja" size="10" maxlength="4" /></td>
          <td><input name="txtalto" id="txtalto" type="text" class="caja" size="10" maxlength="4" /></td>
          <td><input name="txtarea" id="txtarea" type="text" class="caja" size="10" maxlength="4" /></td>
          <td><input name="txtcaras" id="txtcaras" type="text" class="caja" size="10" maxlength="4" /></td>
      </tr>
   </table>
    </div>    
</fieldset>
    </td>
    </tr>
    <tr>
    <td colspan="5">
    <fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">&nbsp;Requisitos</legend>
    <div class="contentForm">
    <table class="tableContent" >
      <tr>
      <td><input id="chkCarSol" type="checkbox"></td>
      <td><span id="lblTipAuto">Completos</span></td>
      <td><input id="chkCarSol" type="checkbox"></td>
      <td><span id="lblTipAuto">Imcompletos</span></td>
      <td><span id="lblTipAuto">&nbsp;</span></td>
      <td colspan="4"><span id="lblTipPredio">Informe N&deg;</span></td>
       <td colspan="4"><input  type="text" name="txtNro7" rows="3" class="caja" id="txtNro8" style="width:200px"></textarea></td>
      </tr>
   
    </table>
    </div>
</fieldset>
</td>
    </tr>
    <tr>
    <td colspan="5">
    <fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">&nbsp;Ubicaci&oacute;n del Anuncio</legend>
    <div class="contentForm">   
        <textarea name="txtNro1" rows="3" class="caja" id="txtNro1" style="width:100%"></textarea>    
    </div>
</fieldset></td>
    </tr>
    <tr><td colspan="5">
    <fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">&nbsp;Leyenda del Anuncio</legend>
    <div class="contentForm">   
        <textarea name="txtNro2" rows="3" class="caja" id="txtNro2" style="width:100%"></textarea>   
    </div>
</fieldset>
</td></tr>
    </table>
  </div>

</fieldset>






    




  