 <fieldset class="ui-widget ui-widget-content">
        <legend style="margin-left:5px">Observancias de Defensa Civil:</legend>
        <div class="contentForm">        
        	<div id="gridObser"></div>
            <table class="tableContent">
          <tr>
            <td colspan="2"> 
            <fieldset class="ui-widget ui-widget-content">
            	<legend style="margin-left:5px">Certificado N&deg;</legend>
                <div class="contentForm">
                 <table class="tableContent">
            <tr>
            <td><input name="txtNro4" id="txtNro5" type="text" class="caja" size="50" maxlength="20" /></td>
            </tr>
              </table>  
                </div>
             </fieldset>   
             </td>
            <td colspan="2" >
            <fieldset class="ui-widget ui-widget-content">
    		<legend style="margin-left:5px">Vigencia</legend>
            <div class="contentForm">
            <table class="tableContent">
            <tr>
            	<td><span id="lblTrabH">del</span></td>
                <td>
                	<input name="txtFchViDel" id="txtFchViDel" type="text" class="caja" size="14" maxlength="100" />
                </td>
                <td><span id="lblTrabM">al</span></td>
                <td>
                	<input name="txtFchViAl" id="txtFchViAl" type="text" class="caja" size="14" maxlength="100" />
                </td>
            </tr>
            </table>
            </div>
            </fieldset>
            </td>
          </tr>
        
        </table>
        </div>
 </fieldset>


