<fieldset class="ui-widget ui-widget-content" style="margin-bottom:100px">
    <legend style="margin-left:5px">&nbsp;VII. Documentos Anexados</legend>
    <div class="contentForm">
          <input type="hidden" name="oldDocItems" id="oldDocItems" value="">    
	<table>
			<tr>
            <td valign="top">
            <div id="gridFicIndDoc"></div>
            </td>            
		</tr>
	</table>
    </div>
</fieldset>




