<fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">&nbsp;I. Tipo de Autorizaci&oacute;n Municipal o Tr&aacute;mite</legend>
    <div class="contentForm">
        <table class="tableContent">
          <tr>
          <td><span id="lblTipAuto">Tipo:</span></td>
          <td><select name="cmbTipLicencia" id="cmbTipLicencia" class="combo">
            
          </select></td>
         
          
          <td><span id="lblFecPresenta">Fecha Presentaci&oacute;n:</span></td>
          <td><input readonly="readonly" name="txtFechaPre" id="txtFechaPre" type="text" class="caja" size="12" maxlength="100" /></td>
          </tr>
          <tr>
           <td><span id="lblTipAuto">Concepto:</span></td>
          <td colspan="2"><select name="cmbCptoLicencia" id="cmbCptoLicencia" style="width:150px;" class="combo"><option>[Seleccione]</option>
            
          </select></td>
          </tr>
        </table>
    </div>
</fieldset>
<br/>
<fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">&nbsp;Tipo de Persona</legend>
    <div class="contentForm">
        <table class="tableContent">
          <tr>
          <td><span id="lblTipAuto"  >Persona Natural:</span></td>
          <td><input type="radio" name="persona" id="personaN" value="N" checked="checked" /></td>
          <td><span id="lblTipAuto" >Persona J&uacute;ridica:</span></td>
          <td><input type="radio" name="persona" id="personaJ" value="J"  /></td>      
          </tr>
        </table>
    </div>
</fieldset>
<br />
<fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">&nbsp;II. Identificaci&oacute;n del Solicitante</legend>
    <div class="contentForm">
      <table class="tableContent">
          <tr>
          <td width="144" style="visibility:hidden; display:none;"><span id="lblTipAuto" >C&oacute;digo:</span></td>
          <td colspan="2"><span id="lblFecPresenta">Nombres y Apellidos/ Raz&oacute;n Social:</span></td>
          <td width="9">&nbsp;</td>
          </tr>
          <tr>
            <td style="visibility:hidden;display:none;"><input name="txtCodPer" id="txtCodPer" type="text" class="cajaoff" size="10" maxlength="100" readonly /></td>
            <td colspan="3">
            <input name="txtNomPer" id="txtNomPer" type="text" class="cajaoff" size="60" maxlength="100" readonly />
            &nbsp; <input type="button" id="btnBusPerSol" value="Buscar" />
            </td>
          </tr>
         
          <tr>
          <td>
           
            <table class="tableContent">
            <tr>
            <td><span id="lblTipAuto">Nro DNI:</span></td>
            </tr> 
             <tr>
            <td><span id="lblTipAuto"><input name="txtNroDoc" id="txtNroDoc" type="text" class="caja" size="20" maxlength="8" /></span></td>
            </tr> 
            </table> 
         
           
          </td>
          <td width="229">
           
            <table class="tableContent">
            <tr>
            <td><span id="lblTipAuto">Regimen Tributario:</span></td>
            </tr> 
             <tr>
            <td><select name="cmbTipRegimen" id="cmbTipRegimen" class="combo">          
          </select></td>
            </tr> 
            </table> 
         
           
          </td>
          <td width="180">
           
            <table class="tableContent">
            <tr>
            <td><span id="lblTipAuto">Nro RUC:</span></td>
            </tr> 
             <tr>
            <td><span id="lblTipAuto"><input name="txtNroRuc" id="txtNroRuc" type="text" class="caja" size="20" maxlength="11" /></span></td>
            </tr> 
            </table> 
         
           
          </td>
          
        
          
          </tr>
          
         
           <tr>
            <td style="visibility:hidden; display:none;"><span id="lblTipAuto"  >Tipo de Doc.:</span></td>
            
            <td><span id="lblTipAuto">Tel&eacute;fono:</span></td>
            <td><span id="lblTipAuto">Correo Electr&eacute;nico:</span></td>
          </tr>
          <tr>
            <td style="visibility:hidden; display:none;"><input name="txtTipDoc" id="txtTipDoc" type="text" class="cajaoff" size="10" maxlength="100" readonly /></td>
            
            <td><input name="txtNroTe" id="txtNroTe" type="text" class="caja" size="20" maxlength="8" /></td>
            
            <td><input name="txtCorreo" type="email" id="txtCorreo"  class="caja" size="30" maxlength="100" /></td>
          </tr>
           <tr>
            <td><span id="lblTipAuto">Distrito :</span></td>           
            <td colspan="2"><span id="lblTipAuto">Domicilio Fiscal:</span></td>
          </tr>
          <tr>
           <td><input name="txtDis" id="txtDis" type="text" class="cajaoff" maxlength="100" readonly style="width:100%" /></td>
            <td colspan="3"><input name="txtDirPer" id="txtDirPer" type="text" class="cajaoff" maxlength="100" readonly style="width:100%" /></td>
          </tr>
        </table>
    
</fieldset>
<br/>
<fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">&nbsp;III. Representante Legal</legend>
    <div class="contentForm">
        <table class="tableContent">
          <tr>
          <td colspan="2"><span id="lblTipAuto">Nombres y Apellidos/ Raz&oacute;n Social:</span></td>

          </tr>
          <tr>
            <td colspan="3"><input name="txtApeNom" id="txtApeNom" type="text" class="cajaoff" maxlength="100" readonly="readonly" style="width:100%" /></td>
          </tr>
          <tr>
            <td><span id="lblTipPredio">Doc. de Identidad:</span></td>
            <td><span id="lblNro">Nro. Documento:</span></td>
            <td><span id="lblNro">Tel&eacute;fono:</span></td>
          </tr>
          <tr>
          <td><select disabled="disabled"  name="cmbTipPredio2" id="cmbTipPredio2" class="combo">
            <option>[Seleccione]</option>
          </select></td>
          <td><input name="txtNroDocRe" id="txtNroDocRe" type="text" readonly="readonly" class="cajaoff" size="20" maxlength="11"/></td>
          <td><input name="txtPhone" id="txtPhone" readonly="readonly" type="text" class="cajaoff" size="20" maxlength="9" /></td>
          </tr>
          <tr>
          <td colspan="1"><span id="lblTipPredio">Partida Regitral (SUNARP):</span></td>
		  <td colspan="2"><span id="lblTipPredio">Correo Electr&oacute;nico:</span></td>
                
          </tr>
          <tr>
          <td colspan="1">
          	<input name="txtSUNARP" readonly="readonly" id="txtSUNARP" type="text" class="cajaoff" maxlength="50" />&nbsp;
          	<input hidden name="txtpredio" id="txtpredio" type="text" class="caja" maxlength="50" />
          </td>
            <td colspan="2">
          	<input name="txtRemail" readonly="readonly" id="txtRemail" type="email" class="cajaoff" size="30" />&nbsp;
          </td>
                
          </tr>
        </table>
       
    </div>
</fieldset>
<br/>


    



  