<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Rptgeneral_saldoXsector.js"></script>
<div id="contentBox" class="ui-content-tabs">
	<ul>
    	<li class="contentBoxHead" style="padding:0 0 2px 5px"><?php echo $this->title;?></li>
    </ul>
    <div class="contentBox">
	    <fieldset class="ui-widget ui-widget-content">
		    <legend style="margin-left:5px">Criterios:</legend>
	        <div class="contentForm">
	   		<table class="tableContent">
			   <tr>
                    <td><b>Año:</b></td>
					<td><b>Sector:</b></td>
					<td><b>Concepto Arbitrio:</b></td>

               </tr>
				<tr>

                    <td>
						<select name="cb_anno" id="cb_anno" class="combo" style="width:70px"><?php echo $this->cb_anno;?></select>
					</td>
					<td>
						<select id="cb_Sector" name="cb_Sector" class="combo" style="width:200px"><?php echo $this->cb_sector;?></select>
					</td>
					<td>
						<select id="cb_concepto" name="cb_concepto" class="combo" style="width:200px">
						<option value="11.01">Recoleccion de Residuos</option>
						<option value="11.02">Barrido de Vias</option>
						<option value="11.03">Parques y Jardines</option>
						<option value="11.04">Servicio de Serenazgo</option>
						</select>
					</td>
					<td>
						<input type="button" id="btnProcesar_saldo_X_Sector" value="Procesar Saldos" />
					</td>
                </tr>
            </table>	    
	    	</div>
			
			

			
	    </fieldset>

    </div>
	<div id="ReporteSaldoXSector">	
	   
	    	
			</div>
</div>