<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Mantpoblado_formu.js"></script>
<form id="frmpoblado">
<input type="hidden" name="actionPoblado" id="actionPoblado">
<div>
    <fieldset class="ui-widget ui-widget-content">
        <legend style="margin-left:5px"></legend>
        <div class="contentForm">
        	<table class="tableContent" width="100%">
			    <tr>
			      <td width="19%"><span id="lblCodigo">Código:</span></td>
			      <td colspan="2"><input name="txtCodPoblado" id="txtCodPoblado" type="text" class="cajaoff" size="20" maxlength="100" readonly value="<?php echo $this->cod;?>"/></td>
			    </tr>
			     		    
			    <tr>
			      <td><span id="lblUrba">Tipo:</span></td>
			      <td><input type="radio" name="rdCriterioTipo" id="rdTipoVia"  value="1"/> 
			      via
</td>
			      <td><input type="radio" name="rdCriterioTipo" id="rdTipoDenominacion"  value="2"/> 
			        denominacion
</td>
			    </tr>
				
				<tr>
				  <td><span>Ubicacion:</span></td>
				  <td colspan="2"><select name="cmbUbicacion" id="cmbUbicacion" class="combo" style="width:200px;">
				    <option>[Seleccione]</option>
			      </select></td>
			  </tr>
				<tr>
				  <td><span>Cuadra:</span></td>
				  <td colspan="2"><label for="txtCuadra"></label>
			      <input type="text" name="txtCuadra" id="txtCuadra" size="4" class="caja" maxlength="2"/></td>
			  </tr>
				<tr>
				  <td><span>Zona:</span></td>
				  <td colspan="2"><select name="cmbZona" id="cmbZona" class="combo">
				    <option>[Seleccione]</option>
			      </select></td>
			  </tr>
				<tr>
				  <td><span>Tipo zona:</span></td>
				  <td width="14%"><input type="radio" name="rdTipozona" id="rdbaja" value="baja" >
				  baja</td>
				  <td width="67%"><input type="radio" name="rdTipozona" id="rdalta" value="alta">
				  alta</td>
		      </tr>
				<tr>
			      <td><span id="lblDescripcion">Nombre:</span></td>
				  <td colspan="2"><input name="txtNombre" type="text" id="txtNombre" size="45" class="caja" /></td>
			    </tr>  
			    			    
			    <tr>
			      <td><span>Estado:</span></td>
			      <td colspan="2"><input type="checkbox" name="nestado" id="nestado" value="1"></td>
			    </tr>
			    
			    <tr>
			      <td colspan="8">
                  <div class="divButtons">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                    <td style="padding-left:5px">
           	          <input type="button" name="btnGrabaPoblado" id="btnGrabaPoblado" value="Grabar" />
                      <input type="button" name="btnSalirPoblados" id="btnSalirPoblados" value="Salir" />
                    </td>
                    </tr>
                    </table>
                  </div>
                  </td>
		      </tr>
			    
		    </table>	    
        </div>
    </fieldset>	    
</div>
<div ID="MSG_ERROR"></div>
</form>