<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Mantpoblado.js"></script>
<div id="contentBox" class="ui-content-tabs">
	<ul>
    	<li class="contentBoxHead" style="padding:0 0 2px 5px"><?php echo $this->title;?></li>
    </ul>
    <div class="contentBox">
	    <fieldset class="ui-widget ui-widget-content">
		    <legend style="margin-left:5px">Criterios:</legend>
	        <div class="contentForm">
	   		<table class="tableContent">
              <!--<tr>
				  <td>
					  <label>
					  <input name="rdCriterio" id="rdCriterio1" type="radio" value="C" checked/><b> Código</b>
					  </label>
				  </td>
				  <td>
					  <label>
					  <input name="rdCriterio" id="rdCriterio2" type="radio" value="N" /><b> Urbanización</b>
					  </label>
				  </td>
              <td>
              <label>
              <input name="rdCriterio" id="rdCriterio3" type="radio" value="D" /><b> Zona</b>
              </label>
              </td>
              <td><input name="txtCriterio" id="txtCriterio" style="text-transform: uppercase" type="text" class="caja" size="20" maxlength="100" /></td>
              <td><input type="button" id="btnBusPoblado" value="Buscar" /></td>
              </tr>-->
			   <tr>
                    <td><b>Codigo:</b></td>
                    <td><b>Zona:</b></td>
                    <td><b>Urbanizacion:</b></td>
					<td><b>Nombre de via:</b></td>
                    <td><b>Estado:</b></td>
					<td>&nbsp;</td>
                </tr>
				<tr>
                    <td>
						<input name="txtCodigo" id="txtCodigo" type="text" class="caja" size="15" maxlength="13" />
					</td>
                    <td>
						<input name="txtZona" id="txtZona" type="text" class="caja" size="25" />
					</td>
                    <td>
						<input name="txtUrbanizacion" id="txtUrbanizacion" type="text" class="caja" size="30"  />
					</td>
					<td>
						<input name="txtNomVia" id="txtNomVia" type="text" class="caja" size="35" />
					</td>
                    <td>
						 <select name="cmbEstado" id="cmbEstado" class="combo" style="width:100px;">
							<option value="">-Seleccione-</option>
							<option value="1">Activo</option>
							<option value="0">Inactivo</option>
						 </select>
					</td>
					<td>
						<input type="button" id="btnBusPoblado" value="Buscar" />
					</td>
                </tr>
            </table>	    
	    	</div>
	    </fieldset>
	    <br/>
	    <div id="gridPoblad"></div>
	    <br/>
	    <div class="divButtons">
		    <table border="0" cellpadding="0" cellspacing="0" width="100%">
		    <tr>
		    <td style="padding-left:5px">
		    <!--<input type="button" id="btnVerPoblado" value="Ver Detalle" />-->
		    <input type="button" id="btnNuevoPoblado" value="Nueva Zona" />
		    </td>
		    <td></td>
		    </table>
		</div>
    </div>
</div>