<h1>AUTORIZACIÓN MUNICIPAL DE FUNCIONAMIENTO</h1>
<input type="hidden" id="oldActItems" name="oldActItems">
<div style="margin-top:5px">
    <table class="tableContentc">
    <tr>
      <td valign="top">
      <div id="gridFicEcoActivi"></div>
      </td>
      <td style="padding-left:15px" valign="top">
            <div class="lblTxtField" style="width:320px;">Area de la Actividad Económica</div>        
            <div class="lblCodField" style="width:30px">147</div>             
            <div class="lblTxtField" style="width:100px;">N. Expediente</div>
            <div class="lblCodField" style="width:30px">148</div>  
            <div class="lblTxtField" style="width:100px;">N. Licencia</div>
            
            <div class="lblTxtField" style="width:80px; clear:left; border-top:0;">Ubicación</div>
            <div class="lblCodField" style="width:30px; border-top:0;">145</div>
            <div class="lblTxtField" style="width:90px; border-top:0;">A. Autorizada</div>
            <div class="lblCodField" style="width:30px; border-top:0;">146</div>
            <div class="lblTxtField" style="width:90px; border-top:0;">A. Verificada</div>
            <div class="lblObjField" style="border-left:0; border-top:0">
            <input name="nroexpex" type="text" class="cajac" id="nroexpex" style="width:129px" maxlength="25">
            </div>
            <div class="lblObjField" style="border-left:0; border-top:0">
            <input name="nrolicex" type="text" class="cajac" id="nrolicex" style="width:129px" maxlength="25">
            </div>
            
            <div class="lblTxtField" style="width:80px; clear:left; border-top:0;">P. Catastral</div>
            <div class="lblObjField" style="border-left:0; border-top:0">
            <input name="areaaup" type="text" class="cajac" id="areaaup" style="width:119px" maxlength="20">
            </div>
            <div class="lblObjField" style="border-left:0; border-left:0; border-top:0">
            <input name="areavep" type="text" class="cajac" id="areavep" style="width:119px" maxlength="20">
            </div>
            <div class="lblTxtField" style="width:260px; border-left:0; border-top:0;">Vigencia de Autorización</div>
            
            <div class="lblTxtField" style="width:80px; clear:left; border-top:0;">Vía Pública</div>
            <div class="lblObjField" style="border-left:0; border-top:0">
            <input name="areaauv" type="text" class="cajac" id="areaauv" style="width:119px" maxlength="20">
            </div>
            <div class="lblObjField" style="border-left:0; border-left:0; border-top:0">
            <input name="areavev" type="text" class="cajac" id="areavev" style="width:119px" maxlength="20">
            </div>
            <div class="lblCodField" style="width:30px; border-top:0">149</div>             
            <div class="lblTxtField" style="width:100px; border-top:0">F. Expedición</div>
            <div class="lblCodField" style="width:30px; border-top:0">150</div>  
            <div class="lblTxtField" style="width:100px; border-top:0">F. Vencimiento</div>            
            <div class="lblTxtField" style="width:80px; clear:left; border-top:0;">Bien Común</div>
            <div class="lblObjField" style="border-left:0; border-top:0">
            <input name="areaaub" type="text" class="cajac" id="areaaub" style="width:119px" maxlength="20">
            </div>
            <div class="lblObjField" style="border-left:0; border-left:0; border-top:0">
            <input name="areaveb" type="text" class="cajac" id="areaveb" style="width:119px" maxlength="20">
            </div>
            <div class="lblObjField" style="border-left:0; border-top:0">
            <input name="fecexpe" type="text" class="cajac" id="fecexpe" style="width:129px" maxlength="10">
            </div>
            <div class="lblObjField" style="border-left:0; border-top:0">
            <input name="fecvenc" type="text" class="cajac" id="fecvenc" style="width:129px" maxlength="10">
            </div>
            
            <div class="lblTxtField" style="width:80px; clear:left; border-top:0;">Total</div>
            <div class="lblObjField" style="border-left:0; border-top:0">
            <input name="areaaut" type="text" class="cajac" id="areaaut" style="width:119px" maxlength="20">
            </div>
            <div class="lblObjField" style="border-left:0; border-left:0; border-top:0">
            <input name="areavet" type="text" class="cajac" id="areavet" style="width:119px" maxlength="20">
            </div>
            <div class="lblCodField" style="width:30px; border-top:0">149</div>             
            <div class="lblTxtField" style="width:100px; border-top:0">Inic. Actividad</div>
            <div class="lblObjField" style="border-left:0; border-top:0">
            <input name="fecinic" type="text" class="cajac" id="fecinic" style="width:129px" maxlength="10">
            </div>
      </td>
    
    </tr>
    </table>
</div>
<div id="divAddActivi" style="margin-top:5px;">
    <table class="tableContentc">
    <tr>
    <td>
        <input type="hidden" id="actActivi" name="actActivi">
        <input type="hidden" id="idcactivi" name="idcactivi">
        <div class="lblCodField" style="width:30px">143</div>
        <div class="lblTxtField" style="width:120px;">Código Actividad</div>
        <div class="lblCodField" style="width:30px">144</div>
        <div class="lblTxtField" style="width:170px;">Descripción Actividad</div>
        <div class="lblObjField" style="clear:left; border-top:0">
        <select name="cidacti" id="cidacti" class="comboc" style="width:348px; height:20px"></select>
        </div>
    </td>
    </tr>
    </table>
</div>
<div style="margin-top:10px">
	<table>
    <tr>
    <td id="rowAddActivi">
    <input type="button" id="btnAddActivi" name="btnAddActivi" value="Agregar" style="width:100px" />
    </td>        
    <td id="rowSaveActivi">
    <input type="button" id="btnSaveActivi" name="btnSaveActivi" value="Guardar" style="width:100px" />
    </td>
    <td id="rowEditActivi">
    <input type="button" id="btnEditActivi" name="btnEditActivi" value="Editar" style="width:100px" />
    </td>
    <td id="rowCancelActivi">
    <input type="button" id="btnCancelActivi" name="btnCancelActivi" value="Cancelar" style="width:100px" />
    </td>
    <td>
    <input type="button" id="btnDelActivi" name="btnDelActivi" value="Eliminar" style="width:100px"/>
    </td>
    </tr>
    </table>
</div>