<h1>AUTORIZACION DE ANUNCIO</h1>
<input type="hidden" id="oldAnuItems" name="oldAnuItems">
<div style="margin-top:5px">
<table class="tableContentc">
<tr>
  <td valign="top">
  <div id="gridFiceAnunci"></div>
  </td>
</tr>

<tr>
  <td valign="top">
        <div id="divAddAnunci" style="margin-top:10px;">
        <table class="tableContentc" width="100%">
        <tr>
        <td>
        	<input type="hidden" id="actAnunci" name="actAnunci">
            <input type="hidden" id="idcanunci" name="idcanunci">
        	<div class="lblCodField" style="width:30px;">152</div>
	        <div class="lblTxtField" style="width:50px;">Código</div> 
	        <div class="lblCodField" style="width:30px;">153</div>    
	        <div class="lblTxtField" style="width:210px;">Descripción del tipo de anuncio</div>  
	        <div class="lblCodField" style="width:30px;">154</div>  
	        <div class="lblTxtField" style="width:80px;">Nº de lados</div>
	        <div class="lblCodField" style="width:30px;">155</div>
	        <div class="lblTxtField" style="width:142px;">Area Aut. del anuncio</div>
	        <div class="lblObjField" style="border-left:0;">
       		<input name="areauto" type="text" class="cajac" id="areauto" style="width:119px" maxlength="20">
        	</div>
        	<div class="lblCodField" style="width:30px;">157</div>
	        <div class="lblTxtField" style="width:100px;">Nº Expediente</div>
	        <div class="lblObjField" style="border-left:0;">
       		<input name="nroexpe" type="text" class="cajac" id="nroexpe" style="width:97px" maxlength="7">
        	</div>	
        	
        	<div class="lblObjField" style="border-top:0; clear:left; ">
       		<select name="cidanuc" id="cidanuc" class="comboc" style="width:318px"></select>
			</div>       
			<div class="lblObjField" style="border-left:0; border-top:0;">
       		<input name="nrolado" type="text" class="cajac" id="nrolado" style="width:109px" maxlength="10">
        	</div>  
        	<div class="lblCodField" style="width:30px; border-top:0;">156</div>
        	<div class="lblTxtField" style="width:142px; border-top:0;">Area Verif. del anuncio</div>
        	<div class="lblObjField" style="border-left:0; border-top:0;">
       		<input name="areveri" type="text" class="cajac" id="areveri" style="width:119px" maxlength="20">
        	</div>
        	<div class="lblCodField" style="width:30px; border-top:0;">158</div>
	        <div class="lblTxtField" style="width:100px; border-top:0;">Nº Licencia</div>
	        <div class="lblObjField" style="border-left:0; border-top:0;">
       		<input name="nrolice" type="text" class="cajac" id="nrolice" style="width:97px" maxlength="7">
        	</div>	
        </td>
        </tr>
        
        <tr>
	        <td style="float: right; ">
	       		<div class="lblCodField" style="width:31px; border-top:0;">159</div>
		        <div class="lblTxtField" style="width:100px; border-top:0;">F. Expedición</div>
		        <div class="lblObjField" style="border-left:0; border-top:0;">
	       		<input name="fexpedi" type="text" class="cajac" id="fexpedi" style="width:97px" maxlength="10">
	        	</div> 
	        </td>
        </tr>	       
        
        <tr>
	        <td style="float: right; ">
	        	<div class="lblCodField" style="width:31px; border-top:0; clear:left;">160</div>
		        <div class="lblTxtField" style="width:100px; border-top:0;">F. Vencimiento</div>
		        <div class="lblObjField" style="border-left:0; border-top:0;">
	       		<input name="fvencim" type="text" class="cajac" id="fvencim" style="width:97px" maxlength="10">
	        	</div>	
	        </td>
        </tr>
        </table>
        </div>
  </td>
</tr>


</table>
</div>
<div style="margin-top:20px">
	<table class="tableContentc">
    <tr>
    	<td id="rowAddAnunci"><input type="button" id="btnAddAnunci" name="btnAddAnunci" value="Agregar" style=""></td>
        <td id="rowSaveAnunci"><input type="button" id="btnSaveAnunci" name="btnSaveAnunci" value="Guardar" style=""></td>
    	<td id="rowEditAnunci"><input type="button" id="btnEditAnunci" name="btnEditAnunci" value="Editar" style=""></td>
    	<td id="rowCancelAnunci"><input type="button" id="btnCancelAnunci" name="btnCancelAnunci" value="Cancelar" style=""></td>
    	<td><input type="button" id="btnDelAnunci" name="btnDelAnunci" value="Eliminar" style=""></td>
    </tr>
    </table>
</div>