<h1>IDENTIFICACIÓN DEL CONDUCTOR</h1>
<input type="hidden" id="oldUbiItems" name="oldUbiItems">
<div style="margin-top:10px">
	<table class="tableContentc">
    <tr>
    <td>
    	<div class="lblCodField" style="width:30px">&nbsp;</div>
        <div class="lblTxtField" style="width:60px;">Código</div>
        <div class="lblObjField" style="border-left:0">
        <input name="cid_per" type="text" class="cajacoff" id="cid_per" style="width:100px" readonly>
        </div>
        <div class="lblCodField" style="width:30px">&nbsp;</div>
        <div class="lblTxtField" style="width:175px;">Nombre de Conductor</div>                
        <div class="lblObjField" style="border-left:0">
        <input name="nom_per" type="text" class="cajacoff" id="nom_per" style="width:350px" readonly>
        </div>            
        <div class="lblObjField" style="border:0; margin-left:10px">
        <input type="button" id="btnSearchCond" name="btnSearchCond" value="Seleccionar" style="height:21px">
        </div>     
    </td>
    </tr>
    <tr>
    	<td style="height:20px"></td>
    </tr>
    <tr>
    <td>
    	<div class="lblCodField" style="width:30px;">140</div>
        <div class="lblTxtField" style="width:155px;">Tipo de Conductor</div>        
        <div class="lblObjField" style="border-left:0;">
        <select name="xcidpers" id="xcidpers" class="comboc" style="width:280px"></select>
		</div>                  
        <div class="lblCodField" style="width:30px;">141</div>
        <div class="lblTxtField" style="width:142px;">Nombre Comercial</div>         
        <div class="lblObjField" style="border-left:0;">
        <input name="nombcom" type="text" class="cajac" id="nombcom" style="width:310px" maxlength="250">
        </div>
        
        <div class="lblCodField" style="width:30px; border-top:0">142</div>
        <div class="lblTxtField" style="width:155px; border-top:0;">Cond. del Conductor</div>        
        <div class="lblObjField" style="border-left:0; border-top:0">
        <select name="cidcond" id="cidcond" class="comboc" style="width:280px"></select>
		</div>                          
    </td>
    </tr>
    </table>
</div>
<br/>
<h1>INFORMACIÓN COMPLEMENTARIA</h1>
<div style="margin-top:10px">
	<table class="tableContentc">	   	
    <tr>
    <td>
    	<div class="lblCodField" style="width:30px;">114</div>
        <div class="lblTxtField" style="width:155px;">Cond. de Declarante</div>        
        <div class="lblObjField" style="border-left:0;">
        <select name="ciddecl" id="ciddecl" class="comboc" style="width:280px"></select>
		</div>                  
        <div class="lblCodField" style="width:30px;">116</div>
        <div class="lblTxtField" style="width:142px;">Estado de la Ficha</div>         
        <div class="lblObjField" style="border-left:0;">
        <select name="cidesta" id="cidesta" class="comboc" style="width:310px"></select>
		</div>
        
        <div class="lblCodField" style="width:30px; border-top:0">161</div>
        <div class="lblTxtField" style="width:155px; border-top:0;">Doc. Presentados</div>        
        <div class="lblObjField" style="border-left:0; border-top:0">
        <select name="cidocpe" id="cidocpe" class="comboc" style="width:280px"></select>
		</div>               
		<div class="lblCodField" style="width:30px; border-top:0">119</div>
        <div class="lblTxtField" style="width:142px; border-top:0;">Mantenimiento</div>        
        <div class="lblObjField" style="border-left:0; border-top:0">
        <select name="cidmant" id="cidmant" class="comboc" style="width:310px"></select>
		</div>          
    </td>
    </tr>
    </table>
</div>

<div style="margin-top:20px">
	<table class="tableContentc">	   	
    <tr>
    <td>
    	<div class="lblCodField" style="width:30px;">&nbsp;</div>
        <div class="lblTxtField" style="width:919px;">Observaciones</div>       
         
        <div class="lblCodField" style="width:30px; clear:left; border-top:0; height:39px">&nbsp;</div>
          
        <div class="lblObjField" style="border-top:0">
        <textarea id="vobserv" name="vobserv" class='cajac' style="width:917px; height:38px"></textarea>
		</div>               
    </td>
    </tr>
    </table>
</div>


