<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	<title>Municipalidad Distrital de Independencia</title>
	<script type="text/javascript" src="<?php echo $this->ruta;?>js/jquery.min.js"></script>
	<script>
	var altoTotal=0;
	var altoAnt=0;
	var altoFinal=0;
	</script>
	<style type="text/css">
		BODY{
			padding: 0px;
			margin: 0px;
			font-family: tahoma;
			font-style: normal;
		}
		.text1{
			font-family: tahoma;
			font-size:13px;
			letter-spacing:5px;
		}
	</style>
</head>
<body>
<div style="position:relative">
<?php echo $this->varhtml; ?>
</div>
</body>
</html>