<h1>DOCUMENTOS Y DATOS REGISTRALES</h1>
<div style="margin-top:10px">
	<table class="tableContentc">
    <tr>
    <td>
    	<div class="lblTxtField" style="width:800px; border-bottom:0">REGISTRO NOTARIAL DE LA ESCRITURA PÚBLICA</div>
        <div class="lblCodField" style="clear:left; width:30px; border-bottom:0">101</div>
        <div class="lblTxtField" style="width:360px; border-bottom:0">Nombre de la Notaría</div>
        <div class="lblCodField" style="width:30px; border-bottom:0">102</div>
        <div class="lblTxtField" style="width:150px; border-left:0; border-bottom:0">Kardex</div>
        <div class="lblCodField" style="width:30px; border-bottom:0">103</div>
        <div class="lblTxtField" style="width:200px; border-left:0; border-bottom:0">Fecha de Escritura Pública</div>
        <div class="lblObjField" style="clear:left;">
        <input name="cidnota" type="text" class="cajac" id="cidnota" style="width:388px" maxlength="250">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="vkardex" type="text" class="cajac" id="vkardex" style="width:179px" maxlength="20">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="feescri" type="text" class="cajac" id="feescri" style="width:229px" maxlength="10">
        </div>
    </td>
    </tr>
    </table>
</div>
<div style="margin-top:20px">
<table class="tableContentc">
<tr>
  <td valign="top">
  		<div class="lblTxtField" style="width:943px; border-bottom:0">INSCRIPCIÓN EN REGISTRO DE PREDIOS</div>
  		<div class="lblCodField" style="clear:left; width:30px">104</div>
        <div class="lblTxtField" style="width:150px;">Tipo Partida Registral</div>
        <div class="lblObjField" style="border-left:0">
        <select name="cidregi" id="cidregi" class="comboc" style="width:150px"></select>
		</div>
        <div class="lblCodField" style="width:30px">105</div>
        <div class="lblTxtField" style="width:140px;">Número</div>
        <div class="lblObjField" style="border-left:0">
        <input type="text" id="vnumero" name="vnumero" class="cajac" style="width:110px" maxlength="20" />
		</div>
        <div class="lblCodField" style="width:30px">106</div>
        <div class="lblTxtField" style="width:120px;">Fojas</div>
        <div class="lblObjField" style="border-left:0">
        <input type="text" id="vafojas" name="vafojas" class="cajac" style="width:180px" maxlength="20" />
		</div>
  </td>
</tr>
<tr>
  <td valign="top">
  		<div class="lblCodField" style="width:30px; border-top:0">107</div>
        <div class="lblTxtField" style="width:150px; border-top:0">Asiento</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="asiento" name="asiento" class="cajac" style="width:150px" maxlength="20" />
		</div>
        <div class="lblCodField" style="width:30px; border-top:0">108</div>
        <div class="lblTxtField" style="width:140px; border-top:0">Fec. Insc. del Predio</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="fecinsp" name="fecinsp" class="cajac" style="width:110px" maxlength="10" />
		</div>
        <div class="lblCodField" style="width:30px; border-top:0">109</div>
        <div class="lblTxtField" style="width:120px; border-top:0">Declar. de Fábrica</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <select name="cidfabr" id="cidfabr" class="comboc" style="width:180px"></select>
		</div>
  </td>
  </tr>
<tr>
  <td valign="top">
  		<div class="lblCodField" style="width:30px; border-top:0">110</div>
        <div class="lblTxtField" style="width:150px; border-top:0">Asi. Insc. de Fábrica</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="insfabr" name="insfabr" class="cajac" style="width:150px" maxlength="20" />
		</div>
        <div class="lblCodField" style="width:30px; border-top:0">111</div>
        <div class="lblTxtField" style="width:140px; border-top:0">Fec. Insc. de Fábrica</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="fecinsf" name="fecinsf" class="cajac" style="width:110px" maxlength="10" />
		</div>
  </td>
  </tr>
</table>
</div>
<br />