<h1>DESCRIPCIÓN DEL BIEN COMÚN</h1>
<div style="margin-top:5px">
	<table class="tableContentc" width="100%">
    <tr>
    <td>
    	<div class="lblCodField" style="width:25px">54</div>
        <div class="lblTxtField" style="width:250px;">Clasificación del Predio</div>
        <div class="lblCodField" style="width:25px">55</div>
        <div class="lblTxtField" style="width:250px;">Predio Catastral En</div>
        <div class="lblCodField" style="width:25px">56</div>
        <div class="lblTxtField" style="width:145px;">Código de Uso</div>
        <div class="lblCodField" style="width:25px">57</div>
        <div class="lblTxtField" style="width:200px;">Uso del Predio Catastral</div>
        <div class="lblCodField" style="clear:left; width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
        <select name="cidclas" id="cidclas" class="comboc" style="width:248px"></select>
		</div>
        <div class="lblCodField" style="width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
        <select name="cidpcat" id="cidpcat" class="comboc" style="width:248px"></select>
		</div>
        <div class="lblCodField" style="width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
        <select name="cidusos" id="cidusos" class="comboc" style="width:368px"></select>
		</div>
    </td>
    </tr>
    <tr>
    <td>
    	<div class="lblCodField" style="width:25px; border-top:0">58</div>
        <div class="lblTxtField" style="width:90px; border-top:0">Estructuración</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="estruct" type="text" class="cajac" id="estruct" style="width:50px" maxlength="20" />
        </div>
        <div class="lblCodField" style="width:25px; border-top:0">59</div>
        <div class="lblTxtField" style="width:100px; border-top:0">Zonificación</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="zonific" type="text" class="cajac" id="zonific" style="width:60px" maxlength="20" />
        </div>
        <div class="lblCodField" style="width:25px; border-top:0">60</div>
        <div class="lblTxtField" style="width:110px; border-top:0">Area Terr. Título</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="areterr" type="text" class="cajac" id="areterr" style="width:62px" maxlength="14" />
        </div>
        <div class="lblCodField" style="width:25px; border-top:0">61</div>
        <div class="lblTxtField" style="width:110px; border-top:0">Area Terr. Declar.</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="aredecl" type="text" class="cajac" id="aredecl" style="width:62px" maxlength="14" />
        </div>
        <div class="lblCodField" style="width:25px; border-top:0">62</div>
        <div class="lblTxtField" style="width:110px; border-top:0">Area Terr. Verif.</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="areveri" type="text" class="cajac" id="areveri" style="width:61px" maxlength="14" />
        </div>
    </td>
    </tr>
    <tr>
    <td valign="top">
    	<div style="padding-top:15px"></div>
    	<div class="lblTxtField" style="width:165px;">Linderos de Lote (ML)</div>
        <div class="lblCodField" style="width:25px;">63</div>
        <div class="lblTxtField" style="width:95px;">Med. en Campo</div>
        <div class="lblCodField" style="width:25px;">64</div>
        <div class="lblTxtField" style="width:110px;">Med. Según Título</div>
        <div class="lblCodField" style="width:25px;">65</div>
        <div class="lblTxtField" style="width:95px;">Col. en Campo</div>
        <div class="lblCodField" style="width:25px;">66</div>
        <div class="lblTxtField" style="width:110px;">Col. Según Título</div>
        <div class="lblTxtField" style="clear:left; width:165px; border-top:0">Frente</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="fremeca" type="text" class="cajac" id="fremeca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="fremeti" type="text" class="cajac" id="fremeti" style="width:134px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="frecoca" type="text" class="cajac" id="frecoca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="frecoti" type="text" class="cajac" id="frecoti" style="width:134px" maxlength="14" />
        </div>
        <div class="lblTxtField" style="clear:left; width:165px; border-top:0">Derecha</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="dermeca" type="text" class="cajac" id="dermeca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="dermeti" type="text" class="cajac" id="dermeti" style="width:134px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="dercoca" type="text" class="cajac" id="dercoca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="dercoti" type="text" class="cajac" id="dercoti" style="width:134px" maxlength="14" />
        </div>
        <div class="lblTxtField" style="clear:left; width:165px; border-top:0">Izquierda</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="izqmeca" type="text" class="cajac" id="izqmeca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="izqmeti" type="text" class="cajac" id="izqmeti" style="width:134px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="izqcoca" type="text" class="cajac" id="izqcoca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="izqcoti" type="text" class="cajac" id="izqcoti" style="width:134px" maxlength="14" />
        </div>
        <div class="lblTxtField" style="clear:left; width:165px; border-top:0">Fondo</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="fonmeca" type="text" class="cajac" id="fonmeca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="fonmeti" type="text" class="cajac" id="fonmeti" style="width:134px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="foncoca" type="text" class="cajac" id="foncoca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="foncoti" type="text" class="cajac" id="foncoti" style="width:134px" maxlength="14" />
        </div>
    </td>
    </tr>
    <tr>
    	<td>
        <div style="padding-top:10px"></div>
        <h1 style="text-align:left; padding:3px 0 5px 0">SERVICIOS BÁSICOS COMUNES</h1>
        <table class="tableContentc" width="100%">
        <tr>
        <td>        	
            <div class="lblCodField" style="width:25px">67</div>
            <div class="lblTxtField" style="width:60px;">Luz</div>
            <div class="lblObjField" style="border-left:0; padding:2px 5px 3px 5px">
          	<input type="checkbox" id="servluz" name="servluz" value="1"/>
        	</div>
            <div class="lblCodField" style="width:25px;">68</div>
            <div class="lblTxtField" style="width:60px;">Agua</div>
            <div class="lblObjField" style="border-left:0; padding:2px 5px 3px 5px">
          	<input type="checkbox" id="seragua" name="seragua" value="1"/>
        	</div>
            <div class="lblCodField" style="width:25px;">69</div>
            <div class="lblTxtField" style="width:60px;">Teléfono</div>
            <div class="lblObjField" style="border-left:0; padding:2px 5px 3px 5px">
          	<input type="checkbox" id="telefon" name="telefon" value="1"/>
        	</div>
            <div class="lblCodField" style="width:25px;">70</div>
            <div class="lblTxtField" style="width:60px;">Desague</div>
            <div class="lblObjField" style="border-left:0;padding:2px 5px 3px 5px">
          	<input type="checkbox" id="desague" name="desague" value="1"/>
        	</div>
            
            <div style="clear:left; padding-top:15px"></div>
            <div class="lblCodField" style="width:25px">71</div>
            <div class="lblTxtField" style="width:110px;">N° Sum. Luz</div>
            <div class="lblObjField" style="border-left:0;">
          	<input name="sumiluz" type="text" class="cajac" id="sumiluz" style="width:180px" maxlength="20" />
        	</div>
            <div class="lblCodField" style="width:25px;">72</div>
            <div class="lblTxtField" style="width:110px;">N° Cont. Agua</div>
            <div class="lblObjField" style="border-left:0;">
          	<input name="conagua" type="text" class="cajac" id="conagua" style="width:180px" maxlength="20" />
        	</div>
            <div class="lblCodField" style="width:25px;">73</div>
            <div class="lblTxtField" style="width:110px;">N° Teléfono</div>
            <div class="lblObjField" style="border-left:0;">
          	<input name="ntelefo" type="text" class="cajac" id="ntelefo" style="width:180px" maxlength="20" />
        	</div>
        </td>
        </tr>
        </table>
        </td>
    </tr>
    </table>
</div>