<h1>RECAPITULACIÓN DE EDIFICIOS</h1>
<input type="hidden" id="oldEdiItems" name="oldEdiItems">
<div style="margin-top:5px">
<table class="tableContentc" width="100%">
<tr>
  <td valign="top">
  <div id="gridFicBcoEdi"></div>
  </td>
  <td valign="top">
  	<div class="divButtons" style="margin-top:0">
        <table>
        <tr id="rowAddEdi">
        <td style="padding:3px"><input type="button" id="btnAddEdi" name="btnAddEdi" value="Agregar" style="width:80px" /></td>
        </tr>        
        <tr id="rowSaveEdi">
        <td style="padding:3px"><input type="button" id="btnSaveEdi" name="btnSaveEdi" value="Guardar" style="width:80px" /></td>
        </tr>
        <tr id="rowEditEdi">
        <td style="padding:3px"><input type="button" id="btnEditEdi" name="btnEditEdi" value="Editar" style="width:80px" /></td>
        </tr>
        <tr id="rowCancelEdi">
        <td style="padding:3px"><input type="button" id="btnCancelEdi" name="btnCancelEdi" value="Cancelar" style="width:80px" /></td>
        </tr>
        <tr>
        <td style="padding:3px"><input type="button" id="btnDelEdi" name="btnDelEdi" value="Eliminar" style="width:80px"/></td>
        </tr>
        </table>
    </div>    
  </td>
  <td valign="top" style="padding-left:5px">
  <div class="contentBoxBr" style="background-color:#E6FFFF; width:240px">
  <table class="tableContent" width="100%">
  	<tr><td>ATC</td><td>-</td><td>Área de Terreno Común</td></tr>
    <tr><td>ACC</td><td>-</td><td>Área Construida Común</td></tr>
    <tr><td>AOIC</td><td>-</td><td>Área de Otras Instal. Comunes</td></tr>
  </table>
  </div>
  </td>
</tr>
<tr>
	<td colspan="3">
    <div id="divAddEdi" style="margin-bottom:5px">
    <table class="tableContentc">
    <tr>
    <td>
    	<input type="hidden" id="actEdi" name="actEdi">
        <input type="hidden" id="idcbreedi" name="idcbreedi">
        <div class="lblCodField" style="width:30px; border-bottom:0">128</div>
        <div class="lblTxtField" style="width:60px; border-bottom:0">Edificio</div>
        <div class="lblCodField" style="width:30px; border-bottom:0">129</div>
        <div class="lblTxtField" style="width:80px; border-bottom:0">Porcent.(%)</div>
        <div class="lblCodField" style="width:30px; border-bottom:0">130</div>
        <div class="lblTxtField" style="width:100px; border-bottom:0">ATC</div>
        <div class="lblCodField" style="width:30px; border-bottom:0">131</div>
        <div class="lblTxtField" style="width:100px; border-bottom:0">ACC</div>
        <div class="lblCodField" style="width:30px; border-bottom:0">132</div>
        <div class="lblTxtField" style="width:100px; border-bottom:0">AOIC</div>
        
        <div class="lblObjField" style="clear:left;">
        <input name="edifici1" type="text" class="cajac" id="edifici1" style="width:88px" maxlength="2">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="nporcen1" type="text" class="cajac" id="nporcen1" style="width:109px" maxlength="20">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="nratcm21" type="text" class="cajac" id="nratcm21" style="width:129px" maxlength="20">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="nraccm21" type="text" class="cajac" id="nraccm21" style="width:129px" maxlength="20">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="naoicm21" type="text" class="cajac" id="naoicm21" style="width:129px" maxlength="20">
        </div>
    </td>
    </tr>
    </table>
  	</div>
    </td>
</tr>
</table>
</div>
<h1>RECAPITULACIÓN DE BIENES COMUNES</h1>
<input type="hidden" id="oldBieItems" name="oldBieItems">
<div style="margin-top:5px">
<table class="tableContentc" width="100%">
<tr>
  <td valign="top">
  <div id="gridFicBcoBie"></div>
  </td>
  <td valign="top">
  	<div class="divButtons" style="margin-top:0">
        <table>
        <tr id="rowAddBie">
        <td style="padding:3px"><input type="button" id="btnAddBie" name="btnAddBie" value="Agregar" style="width:80px" /></td>
        </tr>        
        <tr id="rowSaveBie">
        <td style="padding:3px"><input type="button" id="btnSaveBie" name="btnSaveBie" value="Guardar" style="width:80px" /></td>
        </tr>
        <tr id="rowEditBie">
        <td style="padding:3px"><input type="button" id="btnEditBie" name="btnEditBie" value="Editar" style="width:80px" /></td>
        </tr>
        <tr id="rowCancelBie">
        <td style="padding:3px"><input type="button" id="btnCancelBie" name="btnCancelBie" value="Cancelar" style="width:80px" /></td>
        </tr>
        <tr>
        <td style="padding:3px"><input type="button" id="btnDelBie" name="btnDelBie" value="Eliminar" style="width:80px"/></td>
        </tr>
        </table>
    </div>    
  </td>
  <td valign="top" style="padding-left:5px">
  <div class="contentBoxBr" style="background-color:#E6FFFF; width:240px; padding-top:5px; padding-bottom:5px">
  <table class="tableContent" width="100%">
  	<tr><td>N°</td><td>-</td><td>Orden de Unidades</td></tr>
    <tr><td>%</td><td>-</td><td>Porcentaje de Bien Común</td></tr>
    <tr><td>ATC</td><td>-</td><td>Área de Terreno Común</td></tr>
    <tr><td>ACC</td><td>-</td><td>Área Construida Común</td></tr>
    <tr><td>AOIC</td><td>-</td><td>Área de Otras Instal. Comunes</td></tr>
  </table>
  </div>
  </td>
</tr>
<tr>
	<td colspan="3">
    <div id="divAddBie" style="margin-top:2px;">
    <table class="tableContentc">
    <tr>
    <td>
    	<input type="hidden" id="actBie" name="actBie">
        <input type="hidden" id="idcbrebie" name="idcbrebie">
        <div class="lblCodField" style="width:30px; border-bottom:0">133</div>
        <div class="lblTxtField" style="width:30px; border-left:0; border-bottom:0">N°</div>
        <div class="lblTxtField" style="width:70px; border-left:0; border-bottom:0">Edificación</div>
        <div class="lblTxtField" style="width:60px; border-left:0; border-bottom:0">Entrada</div>
        <div class="lblTxtField" style="width:50px; border-left:0; border-bottom:0">Piso</div>
        <div class="lblTxtField" style="width:50px; border-left:0; border-bottom:0">Unidad</div>
        <div class="lblCodField" style="width:25px; border-left:0; border-bottom:0">89</div>
        <div class="lblTxtField" style="width:35px; border-left:0; border-bottom:0">(%)</div>
        <div class="lblCodField" style="width:30px; border-left:0; border-bottom:0">134</div>
        <div class="lblTxtField" style="width:50px; border-left:0; border-bottom:0">ATC</div>
        <div class="lblCodField" style="width:30px; border-left:0; border-bottom:0">131</div>
        <div class="lblTxtField" style="width:50px; border-left:0; border-bottom:0">ACC</div>
        <div class="lblCodField" style="width:30px; border-left:0; border-bottom:0">132</div>
        <div class="lblTxtField" style="width:50px; border-left:0; border-bottom:0">AOIC</div>
        
        <div class="lblObjField" style="clear:left;">
        <input name="nroorde2" type="text" class="cajac" id="nroorde2" style="width:58px" maxlength="4">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="redific2" type="text" class="cajac" id="redific2" style="width:69px" maxlength="2">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="rentrad2" type="text" class="cajac" id="rentrad2" style="width:59px" maxlength="2">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="refpiso2" type="text" class="cajac" id="refpiso2" style="width:49px" maxlength="2">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="refunid2" type="text" class="cajac" id="refunid2" style="width:49px" maxlength="4">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="nporcen2" type="text" class="cajac" id="nporcen2" style="width:59px" maxlength="20">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="nratcm22" type="text" class="cajac" id="nratcm22" style="width:79px" maxlength="20">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="nraccm22" type="text" class="cajac" id="nraccm22" style="width:79px" maxlength="20">
        </div>
        <div class="lblObjField" style="border-left:0;">
        <input name="naoicm22" type="text" class="cajac" id="naoicm22" style="width:79px" maxlength="20">
        </div>
    </td>
    </tr>
    </table>
  	</div>
    </td>
</tr>
</table>
</div>