<h1>INFORMACIÓN COMPLEMENTARIA</h1>
<div style="margin-top:5px">
<table class="tableContentc">
<tr>
  <td valign="top">
  		<div class="lblCodField" style="width:30px;">119</div>
        <div class="lblTxtField" style="width:419px; border-right:0">Mantenimiento</div>
        <div class="lblCodField" style="clear:left; border-top:0; width:30px">&nbsp;</div>
        <div class="lblObjField" style="border-top:0; border-right:0">
        <select name="cidmant" id="cidmant" class="comboc" style="width:418px"></select>
		</div>
  </td>
  <td valign="top">
  		<div class="lblCodField" style="width:30px;">113</div>
        <div class="lblTxtField" style="width:301px;">Area de Terreno Invadidad (m2)</div>
        
        <div class="lblCodField" style="clear:left; width:30px; border-top:0">&nbsp;</div>
        <div class="lblTxtField" style="width:150px; border-top:0">En Lote Colindante</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="lotecol" name="lotecol" class="cajac" style="width:150px" maxlength="14" />
		</div>
        <div class="lblCodField" style="clear:left; width:30px; border-top:0">&nbsp;</div>
        <div class="lblTxtField" style="width:150px; border-top:0">En Jardín de Aislamiento</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="jaraisl" name="jaraisl" class="cajac" style="width:150px" maxlength="14" />
		</div>
        <div class="lblCodField" style="clear:left; width:30px; border-top:0">&nbsp;</div>
        <div class="lblTxtField" style="width:150px; border-top:0">En Area Pública</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="arepubl" name="arepubl" class="cajac" style="width:150px" maxlength="14" />
		</div>
        <div class="lblCodField" style="clear:left; width:30px; border-top:0">&nbsp;</div>
        <div class="lblTxtField" style="width:150px; border-top:0">En Area Intangible</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="areinta" name="areinta" class="cajac" style="width:150px" maxlength="14" />
		</div>
  </td>
</tr>
</table>
</div>
<div style="margin-top:5px">
<table class="tableContentc" width="100%">
<tr>
  <td colspan="2" valign="top">
  <div style="margin-top:15px">
    <table class="tableContentc">
    <tr>
      <td valign="top">
      		<div class="lblCodField" style="width:30px; border-bottom:0">114</div>
            <div class="lblTxtField" style="width:150px; border-bottom:0">Condición de Declarante</div>
            <div class="lblObjField" style="border-left:0; border-bottom:0">
            <select name="ciddecla" id="ciddecla" class="comboc" style="width:268px"></select>
            </div>
            <div class="lblCodField" style="clear:left; width:30px;">116</div>
            <div class="lblTxtField" style="width:150px;">Estado de la Ficha</div>
            <div class="lblObjField" style="border-left:0">
            <select name="cidestf" id="cidestf" class="comboc" style="width:268px"></select>
            </div>            
      </td>
      <td valign="top">
      		<div class="lblCodField" style="width:30px;">&nbsp;</div>
            <div class="lblTxtField" style="width:468px;">Observaciones</div>
            <div class="lblObjField" style="clear:left; border-top:0">
              <textarea name="vobserv" class="cajac" id="vobserv" style="width:496px; height:50px"></textarea>
            </div>
      </td>
    </tr>
  	</table>
  </div>
  </td>
</tr>
</table>
</div>
<br />