<h1>OBRAS COMPLEMENTARIAS / OTRAS INSTALACIONES</h1>
<input type="hidden" id="oldInsItems" name="oldInsItems">
<div style="margin-top:5px">
<table class="tableContentc" width="100%">
<tr>
  <td colspan="2">
  <div id="gridFicBcoInstal"></div>
  </td>
</tr>
<tr>
  <td valign="top">
        <div id="divAddInstal" style="margin-top:10px;">
        <table class="tableContentc" width="100%">
        <tr>
        <td>
        	<input type="hidden" id="actInstal" name="actInstal">
            <input type="hidden" id="idcminsta" name="idcminsta">
            <div class="lblCodField" style="width:55px; border-bottom:0">90 - 91</div>
            <div class="lblTxtField" style="width:350px; border-bottom:0">Código - Descripción</div>            
            <div class="lblCodField" style="width:25px; border-bottom:0">88</div>
            <div class="lblTxtField" style="width:350px; border-bottom:0">Ubica Const. Antiregla. (UCA)</div>
            <div class="lblObjField" style="clear:left">
            <select name="cidinst" id="cidinst" class="comboc" style="width:403px"></select>
            </div>
            <div class="lblObjField" style="border-left:0">
            <select name="uconanti" id="uconanti" class="comboc" style="width:374px"></select>
            </div>
        </td>
        </tr>
        <tr>
        <td style="padding-top:10px">            
            <div class="lblCodField" style="width:25px">75</div>
            <div class="lblTxtField" style="width:80px;">Fecha Const.</div>
            <div class="lblCodField" style="width:25px">76</div>
            <div class="lblTxtField" style="width:10px; border-bottom:0">&nbsp;</div>
            <div class="lblCodField" style="width:25px">77</div>
            <div class="lblTxtField" style="width:10px; border-bottom:0">&nbsp;</div>
            <div class="lblCodField" style="width:25px">78</div>
            <div class="lblTxtField" style="width:10px; border-bottom:0">&nbsp;</div>
            <div class="lblTxtField" style="width:280px; border-left:0; text-align:center">Dimensiones Verificadas</div>
            <div class="lblCodField" style="width:25px;">95</div>
            <div class="lblTxtField" style="width:120px; border-bottom:0; border-left:0; text-align:center">Producto Total</div>
            <div class="lblCodField" style="width:25px;">96</div>
            <div class="lblTxtField" style="width:120px; border-bottom:0; border-left:0; text-align:center">Unidad de Medida</div>
            
            <div class="lblTxtField" style="clear:left; width:50px; border-top:0; text-align:center">Mes</div>
            <div class="lblTxtField" style="width:55px; border-left:0; border-top:0; text-align:center">Año</div>
            <div class="lblTxtField" style="width:35px; border-left:0; border-top:0; text-align:center">MEP</div>
            <div class="lblTxtField" style="width:35px; border-left:0; border-top:0; text-align:center">ECS</div>
            <div class="lblTxtField" style="width:35px; border-left:0; border-top:0; text-align:center">ECC</div>
            <div class="lblCodField" style="width:25px; border-top:0;">92</div>
            <div class="lblTxtField" style="width:68px; border-top:0">Largo</div>
            <div class="lblCodField" style="width:25px; border-top:0;">93</div>
            <div class="lblTxtField" style="width:68px; border-top:0">Ancho</div>
            <div class="lblCodField" style="width:25px; border-top:0;">94</div>
            <div class="lblTxtField" style="width:69px; border-top:0">Alto</div>
            <div class="lblTxtField" style="width:145px; border-left:0; border-top:0">&nbsp;</div>
            <div class="lblTxtField" style="width:145px; border-left:0; border-top:0">&nbsp;</div>
            
            <div class="lblObjField" style="clear:left; border-top:0;">
            <input name="mesconsi" type="text" class="cajac" id="mesconsi" style="width:48px" maxlength="2">
            </div>
            <div class="lblObjField" style="border-left:0; border-top:0;">
            <input name="anioconsi" type="text" class="cajac" id="anioconsi" style="width:54px" maxlength="4">
            </div>
            <div class="lblObjField" style="border-left:0; border-top:0;">
            <input name="iddepcli" type="text" class="cajac" id="iddepcli" style="width:34px" maxlength="1">
            </div>
            <div class="lblObjField" style="border-left:0; border-top:0;">
            <input name="iddepmai" type="text" class="cajac" id="iddepmai" style="width:34px" maxlength="1">
            </div>
            <div class="lblObjField" style="border-left:0; border-top:0;">
            <input name="iddepcoi" type="text" class="cajac" id="iddepcoi" style="width:34px" maxlength="1">
            </div>
            <div class="lblObjField" style="border-left:0; border-top:0;">
            <input name="dmlargo" type="text" class="cajac" id="dmlargo" style="width:92px" maxlength="9">
            </div>
            <div class="lblObjField" style="border-left:0; border-top:0;">
            <input name="dmancho" type="text" class="cajac" id="dmancho" style="width:92px" maxlength="9">
            </div>
            <div class="lblObjField" style="border-left:0; border-top:0;">
            <input name="dmaltos" type="text" class="cajac" id="dmaltos" style="width:93px" maxlength="9">
            </div>
            <div class="lblObjField" style="border-left:0; border-top:0;">
            <input name="protota" type="text" class="cajac" id="protota" style="width:144px" maxlength="9">
            </div>
            <div class="lblObjField" style="border-left:0; border-top:0;">
            <input name="vunimed" type="text" class="cajac" id="vunimed" style="width:144px" maxlength="2">
            </div>
        </td>
        </tr>
        </table>
        </div>
  </td>
  <td valign="top" align="right">
		<div class="divButtons" style="width:110px">
        <table>
        <tr id="rowAddInstal">
        <td style="padding:3px"><input type="button" id="btnAddInstal" name="btnAddInstal" value="Agregar" style="width:80px" /></td>
        </tr>        
        <tr id="rowSaveInstal">
        <td style="padding:3px"><input type="button" id="btnSaveInstal" name="btnSaveInstal" value="Guardar" style="width:80px" /></td>
        </tr>
        <tr id="rowEditInstal">
        <td style="padding:3px"><input type="button" id="btnEditInstal" name="btnEditInstal" value="Editar" style="width:80px" /></td>
        </tr>
        <tr id="rowCancelInstal">
        <td style="padding:3px"><input type="button" id="btnCancelInstal" name="btnCancelInstal" value="Cancelar" style="width:80px" /></td>
        </tr>
        <tr>
        <td style="padding:3px"><input type="button" id="btnDelInstal" name="btnDelInstal" value="Eliminar" style="width:80px"/></td>
        </tr>
        </table>
    	</div>
  </td>
</tr>
</table>
</div>