     <table width="100%">
                <tr>
                  <td width="18%" valign="top"><label for="dpFechaVisita">Fecha:</label></td>
                  <td colspan="4"><input name="dpFechaVisita" type="text" class="caja" id="dpFechaVisita" readonly="readonly" /></td>
                  </tr>
                   <tr>
                  <td><label for="cbNotificadores">Notificador:</label> </td>
                  <td colspan="4">
                    <select name="cbNotificadores" id="cbNotificadores" class="combo">
                    </select></td>
                  </tr>
                <tr>
                  <td><label for="txtdniNotificador">Nro. de DNI:</label></td>
                  <td width="13%"><input type="text" name="txtdniNotificador" id="txtdniNotificador" class="caja"/></td>
                  <td width="15%">&nbsp;</td>
                  <td width="16%" align="right">&nbsp;</td>
                  <td width="38%">&nbsp;</td>
                  </tr>
                <tr>
                  <td>Firma de Notificador</td>
                  <td>
                  <div id="radioFirmaNot" >
                            <input name="rdFirmaNot" type="radio" id="rdFirmaNotSi" value="1" />
                            <label for="rdFirmaNotSi">Si</label>
                            <input name="rdFirmaNot" type="radio" id="rdFirmaNotNo"  value="0"  checked="checked"/>
                            <label for="rdFirmaNotNo">No</label>
                  </div> 
                  </td>
                  <td>&nbsp;</td>
                  <td align="right">&nbsp;</td>
                  <td>&nbsp;</td>
                  </tr>
               
                </table>