<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta; ?>js/js_multaspredio.js"></script>
<form id="frmultedit">
<input type="hidden" name="codigo" id='codigo' value="<?php echo $this->codigo ?>" size="10" class="caja"/>
<div>
        <fieldset class="ui-widget ui-widget-content" style="padding: 8px;">
   		  <legend style="margin-left:5px">Datos del Contribuyente:</legend>
            <table class="tableContent">
			    <tr>
			    <td><span>C&oacute;digo:</span></td>
			    <td><div id="divCodigo">...........</div></td>
			    <td style='padding-left:30px'><span>Documento:</span></td>
			    <td><div id="divDocu">...........</div></td>
			    <td style='padding-left:30px'><span>Contribuyente:</span></td>
			    <td><div id="divContri">...........</div></td>
			    </tr>
			    <tr>
			    <td><span>Direcci&oacute;n:</span></td>
			    <td colspan="5"><div id="divDirec">...........</div></td>
			    </tr>		    
			</table>
        </fieldset>
        </div>
        <br />
<fieldset class="ui-widget ui-widget-content">


	<div class="contentForm">
	  <table class="tableContent" width="100%">
	 
	      <tr>
	        <td width="18%" height="25"><span>A&ntilde;o de Deuda:</span></td>
	        <td width="35%"><select name="anios_deuda" id="anios_deuda" class="combo" style="width:100px"></select></td>
	      </tr>
	      
	      <tr>
          <td><span>Tributo: </span></td>
	        <td><select name="cmbImporteanual" id='cmbImporteanual' class="combo" style="width:200px">
	          </select></td>
          	<td width="9%"><span>Importe Trimestral: </span></td>
	        <td width="38%"><input name="cant" id="cant" type="text" class="caja" value="0.00" /></td>
			
	        <td><input type="button" name="btnAgregar" id='btnAgregar' value='Agregar'></td>
			<td><input type="button" name="btnVerMultas" id='btnVerMultas' value='Ver Multas'></td>
			
	       
			
	        </tr>
	      <tr>
	        <td><span>Sub Tributo: </span></td>
	        <td><select name="cmbSubtributo" id='cmbSubtributo' class="combo" style="width:200px">
	          </select></td>
	        <td><span>Derecho de Emisi&oacute;n: </span></td>
	        <td><input name="der_emision" id="der_emision" type="text" class="caja" value='0.00' /></td>
	        <td><input type="button" name="btnEliminar" id='btnEliminar' value='Eliminar'></td>
			</tr>
	      <tr>
	        
	       
	        <td><span>Periodo: </span></td>
	        <td><table>
	          <tr align="center">
	            <td>1</td>
	            <td>2</td>
	            <td>3</td>
	            <td>4</td>
	            </tr>
	          <tr>
	            <td><input type="checkbox" name="chkPeriodo" id="chkPeriodo" value='01' checked='checked'/></td>
	            <td><input type="checkbox" name="chkPeriodo" id="chkPeriodo1" value='02'/></td>
	            <td><input type="checkbox" name="chkPeriodo" id="chkPeriodo2" value='03'/></td>
	            <td><input type="checkbox" name="chkPeriodo" id="chkPeriodo3" value='04'/></td>
	            </tr>
	          </table></td>
	        </tr>
			
	      <tr>
	        <td><span>Tipo Obligaci&oacute;n: </span></td>
	        <td><select name="tipo_obligacion" id='tipo_obligacion' class="combo" style="width:200px">
              <option value='09'>Fiscalizacion</option>
		      </select></td>
	      </tr>
		  
		  
		  <tr>
	        <td><span>Fecha: </span></td>
	        <td><input name="txtSalida" id="txtSalida" type="text" class="cajaoff" readonly size="17" /></td>
	      </tr>
		  
		  <tr>
	        <td><span>Fecha Vencimiento: </span></td>
	        <td><input name="txtfechavenci" id="txtfechavenci" type="text" class="cajaoff" readonly size="17" /></td>
	      </tr>
			
			
	      <tr>
	        <td><span>Observaciones: </span></td>
	        <td><textarea name="observacion" rows="3" class="caja" id="observacion" style="width:200px"></textarea></td>
	      </tr>
	   		
	      </table>
	</div>     
	
</fieldset>

	<div>
		<fieldset class="ui-widget ui-widget-content">
		<legend style="margin-left:5px">Predios:</legend>
		<div id="gridMultastribu"></div>
		</fieldset>
	</div>

	
	<div>
		<fieldset class="ui-widget ui-widget-content">
		<legend style="margin-left:5px">Generar Multas:</legend>
		<div id="gridMulta"></div>
		</fieldset>
	</div>

<div class="divButtons">
	<table class="tableContent">
	<tr>
		
		<td><input name="btnGenerar" id='btnGenerar' value='Generar' type="button"></td>
		<td><input name="btnSalir" id='btnSalir' value='Salir' type="button"></td>
	</tr>            
	</table>
</div>
</form>