<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Mantusuario.js"></script>
<div id="contentBox" class="ui-content-tabs">
	<ul>
    	<li class="contentBoxHead" style="padding:0 0 2px 5px"><?php echo $this->title;?></li>
    </ul>
    <div class="contentBox">
	    <fieldset class="ui-widget ui-widget-content">
		    <legend style="margin-left:5px">Criterios:</legend>
	        <div class="contentForm">
	   		<table class="tableContent">
              <tr>
              <td>
              <label>
              <input name="rdCriterio" id="rdC1" type="radio" value="C" checked/><b> Código</b>
              </label>
              </td>
              <td>
              <label>
              <input name="rdCriterio" id="rdC3" type="radio" value="N" /><b> Nombre</b>
              </label>
              </td>
			  <td>
              <label>
              <input name="rdCriterio" id="rdC4" type="radio" value="U" /><b> Usuario</b>
              </label>
              </td>
              <td><input name="txtCriterio" id="txtCriterio" type="text" class="caja" size="20" maxlength="100" /></td>
			  <td><span>Área: </span></td>
			  <td><select id="cmbAre" name="cmbAre" class="combo" style="width:200px"></select></td>
			  <td><span>Perfil: </span></td>
			  <td><select id="cmbPerf" name="cmbPerf" class="combo"></select></td>
              <td><span>Estado: </span></td>
			  <td><select id="cmbEst" name="cmbEst" class="combo"></select></td>
              <td><input type="button" id="btnBusUsuario" value="Buscar" /></td>
              </tr>
            </table>	    
	    	</div>
	    </fieldset>
	    <br/>
	    <div id="gridUsuario"></div>
	    <br/>
	    <div class="divButtons">
		    <table border="0" cellpadding="0" cellspacing="0" width="100%">
		    <tr>
		    <td style="padding-left:5px">
		    <input type="button" id="btnNuevoUsuario" value="Nuevo Usuario" />
		    <input type="button" id="btnNuevaCajaUsuario" value="Nueva Caja" />
		    </td>
		    <td></td>
		    </table>
		</div>
    </div>
</div>
<div id="popup"></div>