<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Mantusuario_password.js"></script>
<form id="frm_password">
<input type="hidden" name="hidIdUsuario" id="hidIdUsuario">
<div>
    <fieldset class="ui-widget ui-widget-content">
        <legend style="margin-left:5px">Ingresar Contraseña:</legend>
        <div class="contentForm">
        	<table class="tableContent" width="100%">
			    <tr>
			      <td><span id="lblNuevaContr">Nueva Contraseña:</span>  </td>
			      <td><input name="txtNuevaContr" id="txtNuevaContr" type="password" class="caja" size="20" maxlength="100" value="<?php echo $this->pass;?>"/></td>
			      </tr>
			      
			      <tr>
			      <td><span id="lblconfirContr">Confirmar Contraseña:</span>  </td>
			      <td><input name="txtConfirContr" id="txtConfirContr" type="password" class="caja" size="20" maxlength="100" value="<?php echo $this->confir;?>"/></td>
			      </tr>
			      	      			      
			  
			    </table>	    
        </div>
    </fieldset>	    
</div>
</form>
<div class="divButtons">
    <table class="tableContent">
    <tr>
    <td><input type="button" name="btnGrabaPassword" id="btnGrabaPassword" value="Grabar" /></td>
    <td><input type="button" name="btnSalirPassword" id="btnSalirPassword" value="Salir" /></td>
    </table>
</div>
