<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>

<style type="text/css">
.invisible {display: none; }
</style>

<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Buscontricoac.js"></script>

<form id="frmBuscontricoac">
<div>
    <div>
	    <fieldset class="ui-widget ui-widget-content">
		    <legend style="margin-left:5px">Criterios:</legend>
	        <div class="contentForm">
	   		<table class="tableContent">
              <tr>
              <td>
              <label>
              <input name="rdCriteriobuscoac" id="rdCriteriobuscoac1" type="radio" value="J" checked/><b> Código</b>
              </label>
              </td>
              <td>
              <label>
              <input name="rdCriteriobuscoac" id="rdCriteriobuscoac2" type="radio" value="K" /><b> Nombres</b>
              </label>
              </td>
			   <td>
              <label>
              <input name="rdCriteriobuscoac" id="rdCriteriobuscoac4" type="radio" value="L" /><b> Razón Social</b>
              </label>
              </td>
              <td>
              <label>
              <input name="rdCriteriobuscoac" id="rdCriteriobuscoac3" type="radio" value="M" /><b> Documento</b>
              </label>
              </td>              
              </tr>
			  </table>
			  <table class="tableContent"> 
			  <tr>
				<td colspan="4">
				<div style="float:left">
					<div id="J" class="visible"><input name="txtCriteriobuscoac" id="txtCriteriobuscoac" type="text" class="caja" size="20" maxlength="100" style="text-transform: uppercase"/></div>
					<div id="K" class="invisible">Nombres <input name="txtCriterioNombrebuscoac" id="txtCriterioNombrebuscoac" type="text" class="caja" size="40" maxlength="100" style="text-transform: uppercase"/> 
												  Apellido Paterno <input name="txtCriterioAPaternobuscoac" id="txtCriterioAPaternobuscoac" type="text" class="caja" size="30" maxlength="100" style="text-transform: uppercase"/>
												  Apellido Materno <input name="txtCriterioAMaternobuscoac" id="txtCriterioAMaternobuscoac" type="text" class="caja" size="30" maxlength="100" style="text-transform: uppercase"/></div>
					<div id="L" class="invisible"><input name="txtCriterioRazonbuscoac" id="txtCriterioRazonbuscoac" type="text" class="caja" size="40" maxlength="100" style="text-transform: uppercase"/></div>
					<div id="M" class="invisible"><input name="txtDocumentobuscoac" id="txtDocumentobuscoac" type="text" class="caja" size="20" maxlength="100" style="text-transform: uppercase"/></div>
				</div>
					<div style="float:right"><input type="button" id="btnSearchcontri" value="Buscar" /></div>
				</td>
			  </tr>
            </table>	    
	    	</div>
	    </fieldset>
	    <br/>
	    <div id="gridBuscontricoac"></div>
	    <br/>
	   
    </div>
</div>
</form>
<!--  Z  X  Y  V     -->