<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Mantuit.js"></script>
<div id="contentBox" class="ui-content-tabs">
	<ul>
    	<li class="contentBoxHead" style="padding:0 0 2px 5px"><?php echo $this->title;?></li>
    </ul>
    <div class="contentBox">
        <fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Valor UIT</legend>
            <div class="contentForm">
            <table class="tableContent" width="100">
             <tr>
             <td>Año</td>
             <td><select name="cb_anno" id="cb_anno" class="combo" ><option>---</option></select></td>
             <td><input name="btnbuscar" id="btnbuscar" type='button' value="Buscar" ></td>
             </tr>
            </table>	    
            </div>
        </fieldset>	
        <br/>	
        <div id="gridUIT"></div>	
        <br/>
        <div class="divButtons">
            <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
            <td style="padding-left:5px">
            <input type="button" name="btnNuevo" id="btnNuevo" value="Nuevo UIT" />
            <input type="button" name="btnsalir" id="btnsalir" value="Eliminar UIT" />
            </td>
            <td></td>
            </table>
        </div>
    </div>
</div>