<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta; ?>js/js_Cataspersona.js"></script>
<div id="contentBox" class="ui-content-tabs">
	<ul>
    	<li class="contentBoxHead" style="padding:0 0 2px 5px"><?php echo $this->title;?></li>
    </ul>
    <div class="contentBox">
	    <fieldset class="ui-widget ui-widget-content">
		    <legend style="margin-left:5px">Criterios:</legend>
	        <div class="contentForm">
	   		<table class="tableContent">
              <tr>
              <td>
              <label>
              <input id="rdCriterio1" name="rdCriterio" type="radio" value="C" checked/><b> Código</b>
              </label>
              </td>
              <td>
              <label>
              <input id="rdCriterio2" name="rdCriterio" type="radio" value="N" /><b> Nombre / Razón Social</b>
              </label>
              </td>
              <td>
              <label>
              <input id="rdCriterio3" name="rdCriterio" type="radio" value="D" /><b> Documento</b>
              </label>
              </td>
              <td>
              <label>
              <input id="rdCriterio4" name="rdCriterio" type="radio" value="O" /><b> Cod. Rentas</b>
              </label>
              </td>              
              <td><input name="txtCriterio" id="txtCriterio" type="text" class="caja" size="30" maxlength="100" style="text-transform:uppercase" /></td>
              <td><input type="button" id="btnSearchCPerson" value="Buscar" /></td>
              </tr>
            </table>	    
	    	</div>
	    </fieldset>
	    <br/>
	    <div id="gridCPerson"></div>
	    <br/>
	    <div class="divButtons">
		    <table border="0" cellpadding="0" cellspacing="0" width="100%">
		    <tr>
		    <td style="padding-left:5px">
		    <input type="button" id="btnNewCPerson" value="Nuevo" />
		    <input type="button" id="btnRefreshCPerson" value="Actualizar" />
		    </td>
		    <td></td>
		    </table>
		</div>
    </div>
</div>