<div id="contentBox" class="ui-content-tabs">
	<div id="content-main">
		<table width="100%" border="0" cellpadding="0" cellspacing="0">
		<tr>
			<td width="15%" align="left" style="border-top:2px #43B0DB solid">
            <div style="font-family: Open Sans,lucida grande,Segoe UI,arial,verdana,lucida sans unicode,tahoma,sans-serif;font-size: 13px;color: #3d464d;font-weight: normal;"><h2>C&oacute;digo :</h2></div>
            </td>
			<td width="13%" style="border-top:2px #43B0DB solid">
            <div style="padding-left:5px;font-family: Open Sans,lucida grande,Segoe UI,arial,verdana,lucida sans unicode,tahoma,sans-serif;font-size: 13px;color: #3d464d;font-weight: normal;"><h2>0000092223</h2></div>
            </td>
			<td width="8%" style="border-top:2px #43B0DB solid"><div style="font-family: Open Sans,lucida grande,Segoe UI,arial,verdana,lucida sans unicode,tahoma,sans-serif;font-size: 13px;color: #3d464d;font-weight: normal;"><h2>Nombre :</h2></div>
            </td>
			<td width="59%" style="border-top:2px #43B0DB solid"><div style="font-family: Open Sans,lucida grande,Segoe UI,arial,verdana,lucida sans unicode,tahoma,sans-serif;font-size: 13px;color: #3d464d;font-weight: normal;"><h2>Miguel Quispe Torres</h2></div>
            </td>
			<td width="5%" rowspan="2" align="right" style="border-top:2px #43B0DB solid">
            <img src='<?php echo $this->ruta; ?>img/band.jpg' />
            </td>
		</tr>
		<tr>
			<td width="15%" align="left">
            	<div style="font-family: Open Sans,lucida grande,Segoe UI,arial,verdana,lucida sans unicode,tahoma,sans-serif;font-size: 13px;color: #3d464d;font-weight: normal;"><h2>Direcci&oacute;n Fiscal :</h2></div>
            </td>
			<td colspan="3">
            <div style="padding-left:5px;font-family: Open Sans,lucida grande,Segoe UI,arial,verdana,lucida sans unicode,tahoma,sans-serif;font-size: 13px;color: #3d464d;font-weight: normal;"><h2>URB. ALAMEDA DE EL PINAR - CLL. 11 MZN. Q LTE. 05
</h2></div>
            </td>
		  </tr>
		<tr>
			<td width="15%" align="left">
            <div style="font-family: Open Sans,lucida grande,Segoe UI,arial,verdana,lucida sans unicode,tahoma,sans-serif;font-size: 13px;color: #3d464d;font-weight: normal;"><h2>Documento :</h2></div>
            </td>
			<td width="13%">
            <div style="padding-left:5px;font-family: Open Sans,lucida grande,Segoe UI,arial,verdana,lucida sans unicode,tahoma,sans-serif;font-size: 13px;color: #3d464d;font-weight: normal;"><h2>DNI-42066094</h2></div>
            </td>
			<td width="8%">
            </td>
			<td width="59%">
            </td>
			<td align="right" width="5%"><div style="padding-right:5px; font-family: Open Sans,lucida grande,Segoe UI,arial,verdana,lucida sans unicode,tahoma,sans-serif;font-size: 13px;color: #3d464d;font-weight: normal;"><h2>2014</h2></div>
            </td>
		</tr>
		</table>
	</div>
</div>