<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Bandecostascontri_formu.js"></script>
<form id="frmcostascontri">
<input type="hidden" id="ximp_insol" name="ximp_insol" />
<input type="hidden" id="xidrecibo" name="xidrecibo" />
<input type="hidden" id="xdeuda" name="xdeuda" />
<input type="hidden" id="xflag" name="xflag" />
<input type="hidden" id="xestadocosta" name="xestadocosta" />
<input type="hidden" id="xestadogasto" name="xestadogasto" />
<div>	
	<div>
		<fieldset class="ui-widget ui-widget-content" style="padding: 8px;">
    		<div style="float:left; padding-right:40px">
    			<table class="tableContent" width="100%">
			    <tr>
			    <td><span id="lblCodigo">Código:</span></td>
			    <td><div id="divCodigo"><?php echo $this->varcodigo;?></div>
				<div><input type="hidden" id="txtcodigo2" name="txtcodigo2"></div>
				</td>
			    </tr>
			    <tr>
			    <td><span id="lblNombre">Contribuyente:</span></td>
			    <td><div id="divNombre"><?php echo $this->varnombre;?></div></td>
			    </tr>
			    <tr>
			    <td><span id="lblDocumen">Nro. Documento:</span></td>
			    <td><div id="divDocumen"><?php echo $this->vardocumen;?></div></td>
			    </tr>			
			    <tr>
			    <td><span id="lblDomicilio">Domicilio Fiscal:</span></td>
			    <td><div id="divDomicilio" style="width:380px"><?php echo $this->vardomicilio;?></div></td>
			    </tr>
				
				<tr>
			    <td><span id="lblExpediente">Expediente:</span></td>
			    <td><input type="text" id="txtexpediente" name="txtexpediente" class="caja"/></td>
			    </tr>
				
			    </table>
    		</div>    	
    	</fieldset>
	</div>	
	</br>
	

	
	<div>
	<fieldset class="ui-widget ui-widget-content" style="padding: 8px;">
    <legend style="margin-left:5px">Detalle de Pago:</legend>
    <div style="float:left">
        <div><input type="hidden" id="actTupa" name="actTupa"></div>	
        <div>
            <div id="gridCostas"></div>		
        </div>
        <div style="margin:5px 0 10px 0" id="divestado">
            <table class="tableContent">
                <tr>
                    <td id="rowAddTupa" style="padding:3px"><input type="button" id="btnAddTupa" name="btnAddTupa" value="Agregar" style="width:80px" /></td>
                    <td id="rowSaveTupa" style="padding:3px"><input type="button" id="btnSaveTupa" name="btnSaveTupa" value="Guardar" style="width:80px" /></td>
                    <td id="rowEditTupa" style="padding:3px"><input type="button" id="btnEditTupa" name="btnEditTupa" value="Editar" style="width:80px" /></td>
                    <td id="rowCancelTupa" style="padding:3px"><input type="button" id="btnCancelTupa" name="btnCancelTupa" value="Cancelar" style="width:80px" /></td>
                    <td style="padding:3px"><input type="button" id="btnDelTupa" name="btnDelTupa" value="Eliminar" style="width:80px"/></td>
					 <td style="padding:3px"><input type="button" id="btnGenerar" name="btnGenerar" value="Generar" /></td>
                <!--    <td style="padding:3px"><input type="button" id="btnAddDeuda" name="btnAddDeuda" value="Deuda Calculada" style="width:120px"/></td>-->
                </tr>
            </table>
          </div>
        <div id="divCalculo">
            <table class="hovertable">
              <tr>
                <th style="display:none"><span>Idcosta</span></th>
                 <th style="display:none"><span>Idrecibo</span></th>
                <th><span>Tipo</span></th>
                <th><span>Subtipo</span></th>
                <th><span>Concepto</span></th>
                <th><span>Monto</span></th>
                <th><span>Cantidad</span></th>
                <th><span>Total</span></th>
              </tr>
              <tr>
                <td style="display:none"><div>
                  <input name="txtidcosta" type="text" class="cajaoff" id="txtidcosta" style="width:50px" readonly >
                </div></td>
                <td style="display:none"><div>
                  <input name="txtidrecibo" type="text" class="cajaoff" id="txtidrecibo" style="width:50px" readonly >
                </div></td>
                <td><div>
                  <input name="txttipo" type="text" class="cajaoff" id="txttipo" style="width:50px" readonly>
                </div></td>
                <td><div>
                  <input name="txtsubtipo" type="text" class="cajaoff" id="txtsubtipo" style="width:50px" readonly>
                </div></td>
                <td>
                <input type="text" name="nom_pago_diver" id="nom_pago_diver" class="caja" style="text-transform:uppercase; width:280px" >
                </td>
                <td><input name="txtprecio" type="text" class="caja" id="txtprecio" style="width:80px;text-align:right"  value="0.00"></td>
                <td><input name="txtcantidad" type="text" class="caja" id="txtcantidad" style="width:80px;text-align:right" maxlength="5" ></td>
                <td><input name="txttotal" type="text" class="cajaoff" id="txttotal" style="width:80px;text-align:right"  value="0.00" readonly ></td>
              </tr>
            </table>
        </div>
	</div>
	<div style="float:right">
		  <table align="right">
					<tr>
					  <td><b>Monto de la Deuda:</b></td>
					  <td style="padding:5px"><input name="txtDeuda" id="txtDeuda" type="text" class="cajaoff" style="width:60px;text-align:right"  readonly="readonly" value='0.00' /></td>
					</tr>
					<tr>
					  <td><b>Gastos:</b></td>
					  <td style="padding:5px"><input name="txtGastos" id="txtGastos" type="text" class="cajaoff" style="width:60px;text-align:right"  readonly="readonly" value='0.00' /></td>
					</tr>
                    <tr>
                      <td><b>Costas Procesales:</b></td>
                      <td style="padding:5px"><input name="txtTotPag" id="txtTotPag" type="text" class="cajaoff" style="width:60px;text-align:right"  readonly value='0.00' /></td>
                     
                    </tr>
					<tr>
                      <td><b>Monto Total:</b></td>
                      <td style="padding:5px"><input name="txtMontotot" id="txtMontotot" type="text" class="cajaoff" style="width:60px;text-align:right"  readonly  value='0.00'/></td>                     
                    </tr>
					<!--
					<tr>
                      <td><b>Monto Total(5%):</b></td>
                      <td style="padding:5px"><input name="txtMontoporce" id="txtMontoporce" type="text" class="cajaoff" style="width:60px;text-align:right"  readonly  value='0.00'/></td>                     
                    </tr>
					<tr>
                      <td><b>TOTAL:</b></td>
                      <td style="padding:5px"><input name="txtTotalfin" id="txtTotalfin" type="text" class="cajaoff" style="width:60px;text-align:right"  readonly  value='0.00'/></td>                     
                    </tr>
					-->
           </table>
	
	</div>
	
	</fieldset>
	</div>
	<div class="divButtons">
                <!--  <input type="button" name="btnImpPag" id="btnImpPag" value="Guardar" />-->                 
				<!--   <input type="button" name="btnImprimir" id="btnImprimir" value="Imprimir" /> -->
					<input type="button" name="btnReporteliqui" id="btnReporteliqui" value="Reporte" />
				    <input type="button" name="btnSalir" id="btnSalir" value="Salir" />
    </div>
</div>
</form>