<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Catasmanturba_formu.js"></script>
<form id="frmcataurbani">
<input  type="hidden"  name="txtCodcataurba_urba" id="txtCodcataurba_urba">
<div>
    <fieldset class="ui-widget ui-widget-content">
        <legend style="margin-left:5px"></legend>
        <div class="contentForm">
        	<table class="tableContent" width="100%">
			    <tr>
			      <td><span id="lblCodigo">Código:</span></td>
			      <td><input name="txtCodcataurba" id="txtCodcataurba" type="text" class="caja" size="10" /></td>
			    </tr>
			    
			    <tr>
			      <td><span id="lblTipo">Tipo:</span></td>
			      <td><select name="cmbTipourba" id="cmbTipourba" class="combo"><option>[Seleccione]</option></select></td>
			    </tr>
			     		
				<tr>
			      <td><span id="lblNombre">Nombre:</span></td>
				  <td><input name="txtNomurba" id="txtNomurba" type="text" class="caja" size="30" style="text-transform:uppercase;" /></td>
			    </tr>  
			    
			    <tr>
			      <td colspan="7">
                  <div class="divButtons">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                    <td style="padding-left:5px">
           	          <input type="button" name="btnGrabaUrba" id="btnGrabaUrba" value="Grabar" />
                      <input type="button" name="btnSalirUrba" id="btnSalirUrba" value="Salir" />
                    </td>
                    </tr>
                    </table>
                  </div>
                  </td>
		      </tr>
			    
		    </table>	    
        </div>
    </fieldset>	    
</div>
<div ID="MSG_ERROR"></div>
</form>