<?php header('Content-Type: text/html; charset=iso-8859-1');?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Cartareq_formulistarcartasreq.js"></script>

    
<form id="formListaFisca" name="formListaFisca">

<div id="contentBox3" class="ui-content-tabs">					
	<ul>
    	<li class="contentBoxHead" style="padding:0 0 2px 5px">CARTAS DE PRESENTACION Y REQ. DE DOC. ACTUALES DEL CONTRIBUYENTE: </li>
    </ul>

    <div id="contenidoFormUsuario" class="contentBox">
	    <div id="radioButton">
          <table class="tableContent" width="100%">
          <tr>
            <td width="24%"><label>CODIGO DE CONTRIB. :</label></td>
            <td width="59%">
            <input name="codContrib" type="hidden" class="cajaoff" id="codContrib" readonly="readonly" />
            <span><?php echo $this->codContrib;?></span>
            </td>
            <td width="17%" rowspan="2"><img src="img/icono_documento.png" width="40" height="40" /></td>
          </tr>
          <tr>
            <td><label for="txtContrib">CONTRIBUYENTE: &nbsp; </label></td>
            <td><span><?php echo $this->contribuyente;?></span></td>
            </tr>
        </table>
	    </div><br />

      <div id="gridFisca"></div>
		<div class="divButtons">
		    <table border="0" cellpadding="0" cellspacing="0" width="100%">
		    <tr>
			    <td style="padding-left:5px">
				    <!--<input type="button" id="btnNewFisca" name="btnNewFisca" value="Nueva Carta de Presentaci&oacute;n y Req." />-->

<button type="button" style="width:256px;border-radius: 1px;font-family: tahoma,arial,verdana,sans-serif;text-align:left; padding-left:5px" id="btnNewFisca" name="btnNewFisca">Nueva Carta de Presentaci&oacute;n y Req.</button>

<button type="button" style="width:106px;border-radius: 1px;font-family: tahoma,arial,verdana,sans-serif;text-align:left; padding-left:5px" id="btnVerActas">Ver Actas</button>
<button type="button" style="width:106px;border-radius: 1px;font-family: tahoma,arial,verdana,sans-serif;text-align:left; padding-left:5px" name="btnCancelFisca" id="btnCancelFisca">Cancelar</button>

<!--<input type="button" name="btnCancelFisca" id="btnCancelFisca" value="Cancelar" />-->
			    </td>
		    	<td>
		    	</td>
		    </tr>
		    </table>
		</div>
    </div>
</div>

<!--                    -->




</form>