<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>

<script type="text/javascript" src="<?php echo $this->ruta; ?>js/js_Cartareq.js"></script>
<form id="formContribuyente">
<div id="contentBox" class="ui-content-tabs">					
	<ul>
    	<li class="contentBoxHead" style="padding:0 0 2px 5px"><?php echo $this->title;?></li>
    </ul>

    <div id="contenidoFormUsuario" class="contentBox">
	    <div id="radioButton">
        <input type="radio" id="BCodigo" name="rdBuscarPor" checked="" value="C">
	    <label for="BCodigo">C&oacute;digo&nbsp;&nbsp;</label>
	    <input type="radio" id="BContribuyente" name="rdBuscarPor"  value="CO">
	    <label for="BContribuyente">Contribuyente&nbsp;&nbsp;	 </label>        
           	  
	    <input name="txtBValor" id="txtBValor" type="text" class="caja" size="40" />
	    <input type="button" id="btnSearchContribuyente" name="btnSearchContribuyente" value="Buscar"/>
        
	    </div><br>
	    <div id="gridContri"></div>
		<div class="divButtons">
		    <table border="0" cellpadding="0" cellspacing="0" width="100%">
		    <tr>
			    <td style="padding-left:5px">
				    <input type="button" id="btnNewContribuyente" name="btnNewContribuyente" value="Nuevo Contribuyente" /></td>
		    	<td>
		    	</td>
		    </tr>
		    </table>
		</div>
    </div>
</div>
</form>