<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>

<script>
Ext.onReady(function(){
    Ext.QuickTips.init();
    
	$("input[type='button']").button();	
	
});

function exportarContriDetalleSec(){
	
	var showResult = function(btn){
		if(btn=='yes'){
			
			
			data = "?id_dist="+$('#txtId_dist').val()+"&id_sector="+$('#txtId_sect').val()+"&id_anio="+$('#txtAnio').val();					
			window.open(urljs+"rptgeneralcps/exportardetcontrisec"+data);
		}
	};
	confirmMessage('Exportar','Desea exportar los datos?',showResult);	
}

</script>
<div>	
	<input type="hidden" id="txtId_dist" name="txtId_dist" />
	<input type="hidden" id="txtId_sect" name="txtId_sect"/>
	<input type="hidden" id="txtAnio" name="txtAnio"/>
	

	<table class="tableContent">		
		<tr>            
			<td><input name="btnExpDetCPSExcelSec" id="btnExpDetCPSExcelSec" type="button" value="Exportar a Excel" /></td>
		</tr>            
	</table>
</div>

  
