<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script>
var mod = '<?php echo $this->mod; ?>';
</script>
<style type="text/css">
.invisible {display: none; }
</style>
<script type="text/javascript" src="<?php echo $this->ruta; ?>js/js_Mantcontri.js"></script>
<form id="frmContri">
<div id="contentBox" class="ui-content-tabs">
	<ul>
    	<li class="contentBoxHead" style="padding:0 0 2px 5px"><?php echo $this->title;?></li>
    </ul>
    <div id="contenidoForm" class="contentBox">
	    <fieldset class="ui-widget ui-widget-content">
		    <legend style="margin-left:5px">Criterios:</legend>
	        <div class="contentForm">
	   		<table class="tableContent">
              <tr>
              <td>
              <label>
              <input name="rdCriterio" id="rdCriterio1" type="radio" value="C" checked/><b> Código</b>
              </label>
              </td>
              <td>
              <label>
              <input name="rdCriterio" id="rdCriterio2" type="radio" value="N" /><b> Nombres</b>
              </label>
              </td>
			   <td>
              <label>
              <input name="rdCriterio" id="rdCriterio4" type="radio" value="R" /><b> Razón Social</b>
              </label>
              </td>
              <td>
              <label>
              <input name="rdCriterio" id="rdCriterio3" type="radio" value="D" /><b> Documento</b>
              </label>
              </td>              
              </tr>
			  </table>
			  <table class="tableContent"> 
			  <tr>
				<td colspan="4">
				<div style="float:left">
					<div id="C" class="visible"><input name="txtCriterio" id="txtCriterio" type="text" class="caja" size="20" maxlength="100" style="text-transform: uppercase"/></div>
					<div id="N" class="invisible">Nombres <input name="txtCriterioNombre" id="txtCriterioNombre" type="text" class="caja" size="40" maxlength="100" style="text-transform: uppercase"/> 
												  Apellido Paterno <input name="txtCriterioAPaterno" id="txtCriterioAPaterno" type="text" class="caja" size="30" maxlength="100" style="text-transform: uppercase"/>
												  Apellido Materno <input name="txtCriterioAMaterno" id="txtCriterioAMaterno" type="text" class="caja" size="30" maxlength="100" style="text-transform: uppercase"/></div>
					<div id="R" class="invisible"><input name="txtCriterio" id="txtCriterioRazon" type="text" class="caja" size="40" maxlength="100" style="text-transform: uppercase"/></div>
					<div id="D" class="invisible"><input name="txtDocumento" id="txtDocumento" type="text" class="caja" size="20" maxlength="100" style="text-transform: uppercase"/></div>
				</div>
					<div style="float:right"><input type="button" id="btnSearchContri" value="Buscar" /></div>
				</td>
			  </tr>
            </table>	    
	    	</div>
	    </fieldset>
	    <br/>
	    <div id="gridContri"></div>
	    <br/>
	    <div class="divButtons">
		    <table border="0" cellpadding="0" cellspacing="0" width="100%">
		    <tr>
		    <td style="padding-left:5px">
		    <input type="button" id="btnNewContri" value="Nuevo" />
		    <input type="button" id="btnRefreshContri" value="Actualizar" />
			<input type="button" id="btnPagoTupa" value="Nuevo Pago Tupa" />
		    </td>
		    <td></td>
		    </table>
		</div>
    </div>
</div>
</form>