<fieldset class="ui-widget ui-widget-content">
    <div class="contentForm">
    	<div style="float:left; margin-right:5px">
        	<fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Arbitrios:</legend>
            <div class="contentForm">
            <table class="tableContent">
              <tr>
              <td><span id="lblTipPredio">Afecto:</span></td>
              <td><input type="checkbox"></td>
              </tr>
              <tr>
              <td><span id="lblTipPredio">Afecto Desde:</span></td>
              <td>
                <select name="cmbUso" id="cmbUso" class="combo"><option>[mm]</option></select>
                <select name="cmbUso2" id="cmbUso2" class="combo"><option>[aaaa]</option></select>
              </td>
              </tr>
              <tr>
                <td><span id="lblTipPredio">Afecto Hasta:</span></td>
                <td><select name="cmbUso" id="cmbUso" class="combo">
                  <option>[mm]</option>
                </select>
                  <select name="cmbUso2" id="cmbUso2" class="combo">
                    <option>[aaaa]</option>
                  </select></td>
              </tr>
              <tr>
                <td><span id="lblNro">Parque:</span></td>
                <td><input name="txtNro" id="txtNro" type="text" class="caja" size="10" maxlength="100" /></td>
              </tr>
              <tr>
                <td><span id="lblNro">Observaciones:</span></td>
                <td><textarea name="txtNro2" cols="45" rows="4" class="caja" id="txtNro2"></textarea></td>
              </tr>
            </table>
            </div>
            </fieldset>
        </div>
        <div style="float:left; margin-left:5px">
        	<fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Serenazgo:</legend>
            <div class="contentForm">
            <table class="tableContent">
              <tr>
              <td><span id="lblTipPredio">Afecto:</span></td>
              <td><input type="checkbox"></td>
              </tr>
              <tr>
              <td><span id="lblTipPredio">Afecto Desde:</span></td>
              <td>
                <select name="cmbUso" id="cmbUso" class="combo"><option>[mm]</option></select>
                <select name="cmbUso2" id="cmbUso2" class="combo"><option>[aaaa]</option></select>
              </td>
              </tr>
              <tr>
                <td><span id="lblTipPredio">Afecto Hasta:</span></td>
                <td><select name="cmbUso" id="cmbUso" class="combo">
                  <option>[mm]</option>
                </select>
                  <select name="cmbUso2" id="cmbUso2" class="combo">
                    <option>[aaaa]</option>
                  </select></td>
              </tr>
              <tr>
                <td><span id="lblNro">Observaciones:</span></td>
                <td><textarea name="txtNro2" cols="45" rows="6" class="caja" id="txtNro2"></textarea></td>
              </tr>
            </table>
            </div>
            </fieldset>
        </div>
        <br style="clear:both"/>
        <br/>
        <fieldset class="ui-widget ui-widget-content">
        <legend style="margin-left:5px">Uso de Arbitrios y Serenazgo:</legend>
        <div class="contentForm">
        <table class="tableContent">
          <tr>
          <td><span id="lblTipPredio">Limpieza P&uacute;blica:</span></td>
          <td><select name="cmbTipPredio" id="cmbTipPredio" class="combo"><option>[Seleccione]</option></select></td>
          </tr>
          <tr>
          <td><span id="lblTipPredio">Relleno Sanitario:</span></td>
          <td><select name="cmbUso" id="cmbUso" class="combo"><option>[Seleccione]</option></select></td>
          </tr>
          <tr>
          <td><span id="lblTipPredio">Parques y Jardines:</span></td>
          <td><select name="cmbTipPredio" id="cmbTipPredio"  class="combo"><option>[Seleccione]</option></select></td>
          </tr>
          <tr>
          <td><span id="lblTipPredio">Serenazgo:</span></td>
          <td><select name="cmbTipPredio" id="cmbTipPredio" class="combo"><option>[Seleccione]</option></select></td>
          </tr>
        </table>
        </div>
        </fieldset>
        <br/>
    </div>
</fieldset>