<fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">Otras Instalaciones:</legend>
    <div class="contentForm">
    	<table id="detalleInstal" class="hovertable">
        <tr>
			<th><center>Descripción</center></th>
            <th><center>Largo</center></th>
            <th><center>Ancho</center></th>
            <th><center>Alto</center></th>
            <th><center>Valor Est.</center></th>
            <th>
            <center>
            <input type="hidden" id="cDetInstal" value="0"/>
            <input type="button" id="btnAddDetInstal" value=" Agregar " class="boton" style="margin:0;"/>
            </center>
            </th>
        </tr>        
        </table>
    </div>
</fieldset>