<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_historicopredio.js"></script>

<form id="frmbajapredio">
<input type="hidden" name="actionHr" id="actionHr">
<div>
    <fieldset class="ui-widget ui-widget-content">
        <legend style="margin-left:5px">Datos Generales del Predio:</legend>
        <div class="contentForm">
        	<table class="tableContent" width="100%">
			    <tr>
			    <td width="114"><span id="lblCodigo">C&oacute;digo:</span></td>
			    <td><div id="divECodigo"></div></td>
			    </tr>
			    <tr>
			    <td><span id="lblAnexo">Contribuyente:</span></td>
			    <td><div id="divENombre"></div></td>
			    </tr>
			    <tr>
			    <td><span id="lblSAnexo">C&oacute;digo Pred.</span></td>
			    <td><div id="divCodPred"></div></td>
			    </tr>
                <tr>
			    <td><span id="lblAnexo">Anexo:</span></td>
			    <td><div id="divSAnexo"></div></td>
			    </tr>
                <tr>
			    <td><span id="lblSAnexo">Direcci&oacute;n Pred.:</span></td>
			    <td><div id="divDireccion"></div></td>
			    </tr>
                <tr>
			    <td><span id="lblSAnexo">A&ntilde;o</span></td>
			    <td><div id="divAnno"></div></td>
			    </tr>

            </table>
            <input type="hidden" id="hd_ECodigo" name="hd_ECodigo" />
            <input type="hidden" id="hd_CodPred" name="hd_CodPred" />
            <input type="hidden" id="hd_SAnexo" name="hd_SAnexo" />
            <input type="hidden" id="hd_anno" name="hd_anno" />
			<input type="hidden" id="hd_direccion" name="hd_direccion" />

            
        </div>
    </fieldset>	    
</div>
<!--<br style="clear:both"><br/>-->
</br>
<div id="gridHistorico"></div>

</br>

<div class="divButtons">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
    <td style="padding-left:5px">
	<input type="button" value="Cerrar" id="btnCerrar" />
    </td>
    <td></td>
    </table>
</div>

</form>
