<fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">Otras Instalaciones:</legend>
    <div class="contentForm">
    	<div style="height:400px; width:880px; border:1px #a6c9e2 solid; overflow:auto">
    	<table id="detalleInstal" class="hovertable">
        <tr>
	        <th><center>Codigo</center></th>
	        <th><center>Descripci&oacute;n de Instalaci&oacute;n</center></th>
	        <th><center>Unid. de Medida</center></th>
	        <th><center>MEP</center></th>
	        <th><center>ECS</center></th>
	        <th><center>ECC</center></th>
	        <th><center>Alto</center></th>
	        <th><center>Largo</center></th>
	        <th><center>Ancho</center></th>
	        <th><center>Mes</center></th>
	        <th><center>A&ntilde;o</center></th>
	        <th><center>Cantidad</center></th>
	        <th><center>Valor Total</center></th>
	        <th><center>Afecto</center></th>
            <th>
            <center>
            <input type="hidden" id="cDetInstal" value="0"/>
            <input type="button" id="btnAddDetInstal" value=" Agregar " class="boton" style="margin:0;"/>
            </center>
            </th>
        </tr>
        </table>
        </diwv>
    </div>
</fieldset>

