<fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">Características del Predio:</legend>
    <div class="contentForm">
        <div style="float:left; margin-right:5px">
        	<fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Descripción:</legend>
            <div class="contentForm">
            <table class="tableContent">
              
              <tr>
              <td><span id="lblTipPredio">Uso:</span></td>
              <td>
              <select name="cmbUso" id="cmbUso" class="combo" style="width: 200px;">
              <option>[Seleccione]</option>
              <option value="1">Ocultar Pisos</option>
              <option value="2">Mostrar Pisos</option>
              </select>
              </td>
              </tr>
              <tr>
              <td><span id="lblTipPredio">Ubicacion Predio:</span></td>
              <td><select name="cmbTipPredio" id="cmbTipPredio" class="combo" style="width: 200px;"></select></td>
              </tr>
              <tr>
              <td><span id="lblTipPredio">Estado de construcción:</span></td>
              <td><select name="cmbEstadoConst" id="cmbEstadoConst" class="combo" style="width: 200px;"></select></td>
              </tr>
              <tr>
              <td><span id="lblTipPredio">Condición de la propiedad:</span></td>
              <td><select name="cmbCondicion" id="cmbCondicion" class="combo" style="width: 200px;"></select></td>
              </tr>
			 			 			  
			  <tr>
              <td><span id="lblTipoAdqui">Tipo de Adquisici&oacute;n:</span></td>
              <td><select name="cmbTipoAdqui" id="cmbTipoAdqui" class="combo" style="width: 200px;"></select></td>
              </tr>
              <tr>
                <td><span id="lblNro">Nro. Pisos:</span></td>
                <td><input name="txtNroPiso" id="txtNroPiso" type="text" class="cajaoff" size="10" maxlength="100" readonly value="<?php echo $this->num_piso;?>"/></td>
              </tr>
              <tr>
                <td><span id="lblNro">Nro. Cond:</span></td>
                <td><input name="txtNroCond" id="txtNroCond" type="text" class="cajaoff" size="10" maxlength="100" readonly value="<?php echo $this->num_condo;?>" /></td>
              </tr>
              <tr>
                <td><span id="lblNro">Area de terreno (m2):</span></td>
                <td><input name="txtAreaTerreno" id="txtAreaTerreno" type="text" class="caja" size="10" maxlength="100" value="<?php echo $this->area_terreno;?>" /></td>
              </tr>
               <tr>
                <td><span id="lblNro">Area de Comun (m2):</span></td>
                <td><input name="txtAreaComun" id="txtAreaComun" type="text" class="caja" size="10" maxlength="100" value="<?php echo $this->area_comun;?>" /></td>
              </tr>
              <tr>
                <td><span id="lblNro">Porcentage Propiedad:</span></td>
                <td><input name="txtPorcenPropiedad" id="txtPorcenPropiedad" type="text" class="caja" size="10" maxlength="100" value="<?php echo $this->porcen_propiedad;?>" data-v-min="0" data-v-max="100.00" />
					<input name="txtHiddenPorcen" id="txtHiddenPorcen" type="hidden" value="<?php echo $this->porcen_propiedad;?>" />
					<input name="txtPorcenPropiedad2" id="txtPorcenPropiedad2" type="hidden" value="<?php echo $this->porcen_propiedad;?>" />
                %</td>
              </tr>
			<tr>
			<td><span id="lblAreaUso">Area Uso:</span></td>
			<td><input name="txtAreaUso" id="txtAreaUso" type="text" class="caja" size="20" value="<?php echo $this->area_uso;?>"/></td>
			</tr>
			<tr>
			<td><span id="lblNro">Frontis:</span></td>
              <td><input name="txtFrontis" id="txtFrontis" type="text" class="caja" size="10" maxlength="100" value="<?php echo $this->frontis;?>" /></td>
			</tr>
			<tr>
			<td><span id="lblFondo">Fondo:</span></td>
              <td><input name="txtFondo" id="txtFondo" type="text" class="caja" size="10" maxlength="100" value="<?php echo $this->fondo;?>" /></td>
			</tr>
               <tr>
                <td><span id="lblNro">Predio Afecto</span></td>
                <td><input type="checkbox" name="chAfectoPred" id ="chAfectoPred" value="1" /> 
                  Afecto
				</td>
              </tr>

			  
              </table>
            </div>
            </fieldset>            
        </div>
        <div style="float:left; margin:0 6px 0 6px">
		
        <fieldset class="ui-widget ui-widget-content" style="padding: 0 0 0 12px;">
            <legend style="margin-left:5px">Datos compra y/o venta:</legend>
            <div class="contentForm">
            <table class="tableContent">
              <tr>
              <td><span id="lblFecAdqui">F. Afectaci&oacute;n:</span></td>
              <td><input name="txtFecAdqui" id="txtFecAdqui" type="text" class="caja" size="12" maxlength="10" value="<?php echo $this->fec_compra;?>" /></td>
              </tr>
              <tr>
              <td><span id="lblFecTrans">F. Adquisicion:</span></td>
              <td><input name="txtFecTrans" id="txtFecTrans" type="text" class="caja" size="12" maxlength="10" value="<?php echo $this->fec_venta;?>"/></td>
              </tr>
              <tr>
                <td><span id="lblFecAdqui">Predio vendido</span></td>
                <td><input type="checkbox" id="chbVendido" name="chbVendido" value="1"></td>
              </tr>
            </table>
            </div>
        </fieldset>
       
		</div>
		
		<div  style="float:left; margin:0 6px 0 11px">
        <fieldset class="ui-widget ui-widget-content" style="padding-top: 12px;">
        <legend style="margin-left:6px">Doc. sobre la construcci&oacute;n:</legend>
        <div class="contentForm">
        <table class="tableContent">
          <tr>
          <td><span id="lblFecAdqui"><input type="checkbox" name="chbLicencia" id ="chbLicencia" value="1"> Licencia de construcción</span></td>
          </tr>
          <tr>
          <td><span id="lblFecAdqui"><input type="checkbox" name="chbConformidad" id ="chbConformidad" value="1"> Conformidad de obra</span></td>
          </tr>
          <tr>
          <td><span id="lblFecAdqui"><input type="checkbox" name="chbDeclaracionFab" id ="chbDeclaracionFab" value="1"> Declaración de fábrica</span></td>
          </tr>
        </table>
		
        </div>
        
      
        </fieldset>
		 
        </div>
		
        <div style="float:left; margin:4px 6px 0px 6px"><!-- margin-left:5px-->
        	<fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Servicios:</legend>
            <div class="contentForm">
            <table class="tableContent">
              <tr>
              <td><span id="lblFecAdqui">Sum. Agua:</span></td>
              <td><input name="txtAgua" id="txtAgua" type="text" class="caja" size="20" maxlength="10" value="<?php echo $this->sum_luz;?>" style="text-transform:uppercase;"/></td>
              </tr>
              <tr>
              <td><span id="lblFecAdqui">Sum. Luz:</span></td>
              <td><input name="txtLuz" id="txtLuz" type="text" class="caja" size="20" maxlength="10" value="<?php echo $this->sum_agua;?>" style="text-transform:uppercase;"/></td>
              </tr>
            </table>
            </div>
            </fieldset>
            <br/>
		</div>
		
		<div style="float:left; margin:4px 6px 0px 6px">
		
            <fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Códigos Alternos:</legend>
            <div class="contentForm">
            <table class="tableContent">
              <tr>
              <td><span id="lblFecAdqui">Cod. Predio:</span></td>
              <td><input name="txtCodPred" id="txtCodPred" type="text" class="caja" size="20" maxlength="10" style="text-transform:uppercase;"/></td>
              </tr>
            </table>
            </div>
            </fieldset>
			
          
		</div>
		
		<div style="float:left; margin:0 0 0 6px">
            <fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Glosa:</legend>
            <div class="contentForm">
            <table class="tableContent">
				<tr>
				<td><span>Motivo Declaracion: </span></td>
				<td><select name="cmbMotivoDec" id="cmbMotivoDec" class="combo" style="width: 150px;"></select></td>
				</tr>
			
				<tr>
				<td><span>Motivo Registro:</span></td>
				<td><select name="cmbMotivoReg" id="cmbMotivoReg" class="combo" style="width: 150px;"></select></td>
				
				</tr>
              <tr>
			  <td><span>Glosa:</span> </td>
              <td><textarea name="txtObs" cols="30" rows="3" style="text-transform:uppercase;" class="caja" id="txtObs"><?php echo $this->obs;?></textarea></td>
              </tr>
            </table>
            </div>
            </fieldset>
        </div>
		
		<div style="float:left; margin:4px 0 0 6px">
            <fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Condición Especial:</legend>
            <div class="contentForm">
            <table class="tableContent">
			
			  <tr>
				<td colspan="1"><span id="lblInterior">Condición Especial:</span></td>
				<td colspan="3"><select name="cmbCondicionpredio" id="cmbCondicionpredio" class="combo" style="width: 200px;"></select></td>
			  </tr>
			  
			  <tr>
			    <td colspan="1"><span>Refer. Documento:</span> </td>
			    <td colspan="3"><input name="txtDocEspecial" id="txtDocEspecial" type="text" class="caja" size="20" maxlength="50" value="<?php echo $this->txtDocEspecial;?>" style="text-transform:uppercase;"/></td>
			  </tr>
			  
			  <tr>
			    <td><span>Nro Documento:</span> </td>
			    <td><input name="txtNroDocEspecial" id="txtNroDocEspecial" type="text" class="caja" size="20" maxlength="50" value="<?php echo $this->txtNroDocEspecial;?>" style="text-transform:uppercase;"/></td>
				
				<td><span>Fecha Documento:</span> </td>
			    <td><input name="txtFechDocEspecial" id="txtFechDocEspecial" type="text" class="caja" size="20" maxlength="10" value="<?php echo $this->txtFechDocEspecial;?>" style="text-transform:uppercase;"/></td>
			  </tr>
			
			  <tr>
			    <td><span>Fecha Inicial:</span> </td>
			    <td><input name="txtFechDocEspecialInicial" id="txtFechDocEspecialInicial" type="text" class="caja" size="20" maxlength="10" value="<?php echo $this->txtFechDocEspecialInicial;?>" style="text-transform:uppercase;"/></td>
				
				<td><span>Fecha Final: </span></td>
			    <td><input name="txtFechDocEspecialFinal" id="txtFechDocEspecialFinal" type="text" class="caja" size="20" maxlength="10" value="<?php echo $this->txtFechDocEspecialFinal;?>" style="text-transform:uppercase;"/></td>
			  </tr>
				
            </table>
            </div>
            </fieldset>
        </div>
		
		<div style="float:left; margin:4px 0 0 6px">
            <fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Situación Predio:</legend>
            <div class="contentForm">
            <table class="tableContent">
			
			  <tr>
				<td colspan="1"><span id="lblInterior">Predio:</span></td>
				<td colspan="3"><select name="cmbSituacionPredio" id="cmbSituacionPredio" class="combo" style="width: 200px;"></select></td>
			  </tr>
			  
			  <tr>
			    <td colspan="1"><span>Documento:</span> </td>
			    <td colspan="3"><input name="txtSituacionDocumento" id="txtSituacionDocumento" type="text" class="caja" size="20" maxlength="50" value="<?php echo $this->txtSituacionDocumento;?>" style="text-transform:uppercase;"/></td>
			  </tr>		  
			  <tr>
			    <td><span>Nro Documento:</span> </td>
			    <td><input name="txtSituacionNroDoc" id="txtSituacionNroDoc" type="text" class="caja" size="20" maxlength="50" value="<?php echo $this->txtSituacionNroDoc;?>" style="text-transform:uppercase;"/></td>
				
				<td><span>Fecha Documento:</span> </td>
			    <td><input name="txtSituacionFechDoc" id="txtSituacionFechDoc" type="text" class="caja" size="20" maxlength="50" value="<?php echo $this->txtSituacionFechDoc;?>" style="text-transform:uppercase;"/></td>
			  </tr>
				
            </table>
            </div>
            </fieldset>
        </div>
		<div style="float:left; margin:4px 6px 0px 6px">
		
            <fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Fiscalizacion del Predio:</legend>
            <div class="contentForm">
            <table class="tableContent">
              <tr>
              <td><span id="lblFecAdqui">Fecha Fiscalizacion:</span></td>
              <td><input name="txtFechaFisca" id="txtFechaFisca" type="text" class="caja" size="20" maxlength="50" style="text-transform:uppercase;" value="<? echo $this->txtFechaFisca;?>"/></td>
              </tr>
			  <tr>
              <td><span id="lblFecAdqui">Nro Declaracion Fiscalizacon:</span></td>
              <td><input name="txtNroFisca" id="txtNroFisca" type="text" class="caja" size="20" maxlength="50" style="text-transform:uppercase;" value="<? echo $this->txtNroFisca;?>"/></td>
              </tr>
            </table>
            </div>
            </fieldset>
			
          
		</div>
		
        <br style="clear:both"/>
    </div>
    <DIV ID="MSG_ERROR"></DIV>
</fieldset>