<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Catasmantsector_formu.js"></script>
<form id="frmcatasector">
<input  type="hidden"  name="txtCodcatasector_sector" id="txtCodcatasector_sector">
<div>
    <fieldset class="ui-widget ui-widget-content">
        <legend style="margin-left:5px"></legend>
        <div class="contentForm">
        	<table class="tableContent" width="100%">
			    <tr>
			      <td><span id="lblCodigo">Código:</span></td>
			      <td><input name="txtCodcatasector" id="txtCodcatasector" type="text" class="caja" size="10" /></td>
			    </tr>			    		     		
				<tr>
			      <td><span id="lblNombre">Nombre:</span></td>
				  <td><input name="txtNomsector" id="txtNomsector" type="text" class="caja" size="30" style="text-transform:uppercase;" /></td>
			    </tr>  
			    
			    <tr>
			      <td colspan="7">
                  <div class="divButtons">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                    <td style="padding-left:5px">
           	          <input type="button" name="btnGrabaSector" id="btnGrabaSector" value="Grabar" />
                      <input type="button" name="btnSalirSector" id="btnSalirSector" value="Salir" />
                    </td>
                    </tr>
                    </table>
                  </div>
                  </td>
		      </tr>
			    
		    </table>	    
        </div>
    </fieldset>	    
</div>
<div ID="MSG_ERROR"></div>
</form>