<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script>
var mod = '<?php echo $this->mod; ?>';
</script>
<style type="text/css">
.invisible {display: none; }
</style>
<script type="text/javascript" src="<?php echo $this->ruta; ?>js/js_Mantcontri.js"></script>

<link rel="stylesheet" href="<?php echo $this->ruta; ?>css/bootstrap.min.css">

<form id="frmContri">

<div id="contentBox" class="ui-content-tabs">
	<ul>
    	<li class="contentBoxHead" style="padding:0 0 2px 5px"><?php echo $this->title;?></li>
    </ul>
    <div id="contenidoForm" class="contentBox">
	    <fieldset class="ui-widget ui-widget-content">
		    <legend style="margin-left:5px">Criterios:</legend>
	        <div class="contentForm">
	   		<table class="tableContent">
              <tr>
	              <td>
		              
		              <input name="rdCriterio" id="rdCriterio1" type="radio" value="C" checked/>
		              <label for='rdCriterio1'>Código</label>
	              </td>
	              <td>
		              <input name="rdCriterio" id="rdCriterio2" type="radio" value="N" />
		              <label for='rdCriterio2'>Nombres</label>
	              </td>
				   <td>
		              <input name="rdCriterio" id="rdCriterio4" type="radio" value="R" />
		              <label for='rdCriterio4'>Razón Social</label>
	              </td>
	              <td>
		              <input name="rdCriterio" id="rdCriterio3" type="radio" value="D" />
		              <label for='rdCriterio3'>Documento</label>
	              </td>
				  <td>
		              <input name="rdCriterio" id="rdCriterio5" type="radio" value="P" />
		              <label for='rdCriterio5'>Direccion Predio</label>
	              </td>              
              </tr>
			  </table>
			  <table id="BusquedaContri" class="tableContent"> 
			  <tr>
				<td colspan="4">
				<div style="float:left">
					<div id="C" class="visible"><input name="txtCriterio" id="txtCriterio" type="text" class="caja" size="20" maxlength="100" style="text-transform: uppercase"/></div>
					<div id="N" class="invisible">Nombres <input name="txtCriterioNombre" id="txtCriterioNombre" type="text" class="caja" size="40" maxlength="100" style="text-transform: uppercase"/> 
												  Apellido Paterno <input name="txtCriterioAPaterno" id="txtCriterioAPaterno" type="text" class="caja" size="30" maxlength="100" style="text-transform: uppercase"/>
												  Apellido Materno <input name="txtCriterioAMaterno" id="txtCriterioAMaterno" type="text" class="caja" size="30" maxlength="100" style="text-transform: uppercase"/></div>
					<div id="R" class="invisible"><input name="txtCriterio" id="txtCriterioRazon" type="text" class="caja" size="40" maxlength="100" style="text-transform: uppercase"/></div>
					<div id="D" class="invisible"><input name="txtDocumento" id="txtDocumento" type="text" class="caja" size="20" maxlength="100" style="text-transform: uppercase"/></div>
				</div>
					<div style="float:right"><span class="glyphicon glyphicon-search"><input type="button" id="btnSearchContri" value="Buscar"/> </span></div>
				</td>
			  </tr>
            </table>

			<table id="Busquedapredio" style="display:none;" class="tableContent"> 
			  <tr>
				<td colspan="4">
				<div style="float:left">
					
					<div id="P"> 
							Año <select name="cb_annobus" id="cb_annobus" class="combo"><?php echo $this->cb_anno;?></select>	
							Via <input name="txt_viabus" id="txt_viabus" type="text" class="caja" size="10" maxlength="100" style="text-transform: uppercase"/> <input type="button" name='btn_Busvia' id="btn_Busvia">
							Nro <input name="txt_busnro" id="txt_busnro" type="text" class="caja" size="10" maxlength="100" style="text-transform: uppercase"/>
							Dpto <input name="txt_busdpto" id="txt_busdpto" type="text" class="caja" size="10" maxlength="100" style="text-transform: uppercase"/>
							Mza. <input name="txt_busmaza" id="txt_busmaza" type="text" class="caja" size="10" maxlength="100" style="text-transform: uppercase"/>
							Lte. <input name="txt_buslte" id="txt_buslte" type="text" class="caja" size="10" maxlength="100" style="text-transform: uppercase"/>
							Sub Lte. <input name="txt_sublte" id="txt_sublte" type="text" class="caja" size="10" maxlength="100" style="text-transform: uppercase"/>
					</div>
				</div>
					<div style="float:right">
						<input type="button" id="btnSearchPredio" value="Buscar"  />
					</div>
				</td>
			  </tr>
            </table>
			
	    	</div>
	    </fieldset>
	    <br/>
	    <div id="gridContri"></div>
	    <br/>
	    <div class="divButtons">
		    <table border="0" cellpadding="0" cellspacing="0" width="100%">
		    <tr>
		    <td style="padding-left:5px">
		    <input type="button" id="btnNewContri" value="Nuevo"  />
		    <input type="button" id="btnRefreshContri" value="Actualizar" />
			<!--<input type="button" id="btnPagoTupa" value="Nuevo Pago Tupa" />-->
		    </td>
		    <td></td>
		    </table>
		</div>
    </div>
</div>
</form>