<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Mantvias_arancel.js"></script>
<form id="frm_arancel">
<input name="codviaescondido" id='codviaescondido' type="text" style="display:none;" value=<?php echo $this->codvia?>>
<div>
    <fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">Detalle de Arancel:</legend>
    	<div class="contentForm">
        <table class="tableContent" width="100">
        <tr>
              <td><span>Año</span></td>
              <td><select name="cb_anno" id="cb_anno" class="combo" ><option>[Seleccione]</option></select></td>
              <td><span>Arancel:</span></td>
          	  <td><input name="txtarancel" id="txtarancel" type="text" class="caja" size="5" ></td>
        </tr>
        </table>
        </div>
        <br style="clear:both">
    </fieldset>
    <br/>
    <div id="gridArancel"></div>
    <br/>
    <div class="divButtons">
        <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
        <td style="padding-left:5px">
          <input type="button" name="btnSaveArancel" id="btnSaveArancel" value="Guardar" />
          <input type="button" name="btnCloseArancel" id="btnCloseArancel" value="Salir" />
        </td>
        <td></td>
        </table>
    </div>
</div>
</form>