<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Mantarancel_editar.js"></script>
<form id="frm_editarancel">
<input name="codvia1" id='codvia1' type="text" style="display:none;" value=<?php echo $this->codvia?>>
<input name="cb_anno1" id="cb_anno1" type="text" style="display:none;">
<div>
    <fieldset class="ui-widget ui-widget-content">
        <legend style="margin-left:5px">Actualizar de Arancel:</legend>
        <div class="contentForm">
        	<table class="tableContent" width="100">
        	<tr><td><span>Codigo</span></td>
        	<td><input name="codvia" id='codvia' class="cajaoff" type="text" value="<?php echo $this->codvia?>" disabled></td>
        	</tr>
        	<tr>
			      <td><span>Anio</span></td>
			      <td><input name="cb_anno2" id="cb_anno2" class="cajaoff" type="text" disabled></td>
          	</tr>
          	<tr>
          		  <td><span>Arancel:</span></td>
          	 	  <td><input name="txtarancel1" id="txtarancel1" class="caja" type="text" ></td>
          	</tr>	          	 
   		</table>
        </div>
		</fieldset>
        <div class="divButtons">
            <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
            <td style="padding-left:5px">
            <input type="button" name="btnSaveEditArancel" id="btnSaveEditArancel" value="Grabar" />
            <input type="button" name="btnCloseEditArancel" id="btnCloseEditArancel" value="Salir" />
            </td>
            </table>
        </div>
</div>
</form>
	    