<script type="text/javascript" src="js/js_rptgeneralcont.js"></script>

<style>
	a:link {
		font-size: 18px; font-style: normal;color:#0000FF;
	}    /* unvisited link */
	a:visited {
		color:#0000FF;
	} /* visited link */
	a:hover {
		color:#DF0101;
	}   /* mouse over link */
	a:active {
		font-size: 18px; font-style: normal;color:#0000FF;
	}  /* selected link */
</style>
<table cellpadding="0" cellspacing="0" border="0" width="100%">
	<tr>
		<td align="left"><a id="lnkopcion1" href="#" onclick="javascript:abrirventana(1);">1. Saldos Mensual</a>
		</td>
	</tr>																													
</table>