
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Municipalidad Distrital de Comas</title>
<style type="text/css">
<!--
@media print {
	BODY {
		font-size: 14pt;
		font-family: Arial;
	}
}

@media screen {
	BODY {
		font-size: 12pt;
		font-family: Arial;
	}
}

@media screen , print {
	BODY {
		color: #000000;
	}
}

body {
	margin-left: 0px;
	margin-right: 0px;
}

.Estilo2 {
	font-size: 2px;
	font-weight: bold;
}

.Estilo4 {
	font-size: 14px;
	font-weight: bold;
}

.Estilo6 {
	font-size: 12px
}

.Estilo7 {
	font-size: 10px;
	font-weight: bold;
}

.Estilo8 {
	font-size: 10px
}

.MasGrande {
	font-size: 14px
}

body,td,th {
	font-family: Arial;
}
-->
</style>

		 <script language="javascript">
		window.print();
	//	window.close();
		</script> 
</head>
<body>
<!--
		<div style="position:absolute;left:0;top:0;height:25;">
		<input type="button" name="imprimir" id="btnprint" style="visibility:visible;" value="Imprimir" onClick="ocultar();">
		</div>
		-->
<table width="100%" style="border: 0px solid"  id="muni">
	<tr>
    <td>&nbsp;</td>
		<td height="24" colspan="2" class="Estilo6"><b> SIGMUN-Caja;<br>
		Sub Gerencia de Tesoreria<br>
		RUC: 20131373661</b>
		  <hr align="left" width="100%">
	  </td>
      <td height="24" colspan="2" class="Estilo6" align="right">Página 1 de 1;</td>
      <td width="25">&nbsp;</td>
	</tr>
	<tr>
    <td>&nbsp;</td>
		<td height="10" colspan="4" class="Estilo7" align="right">Mov : 2222222: Pagina 1 de 1</td>
        <td>&nbsp;</td>
	</tr>
	<tr>
    <td>&nbsp;</td>
   
		<td width="89" align="left"  class="Estilo6">Fecha/Hora:</td>
        <td width="753">&nbsp;</td>
        <td width="586">Mov.Cajero:   </td>
        <td>caja:  </td>
        
        <td>&nbsp;</td>
	</tr>
	<tr>
		<td width="31" height="21" class="Estilo8">&nbsp;</td>
		
        <td>Contrib: </td>
        <td>&nbsp;</td>
  		<td>&nbsp;</td>      
        <td width="173" height="21"  class="Estilo8" id="datosrec1"></td>
        
        <td>&nbsp;</td>
        
	</tr>
	<tr>
		<td height="21" class="Estilo8">&nbsp;</td>
		<td height="21" colspan="5" class="Estilo8" id="datosrec6">Dom.Fiscal:</td>
	</tr>
	<tr>
		<td height="21" class="Estilo8">&nbsp;</td>
		<td height="21" colspan="5" class="Estilo8" id="datosper1">Concepto:</td>
	</tr>
	<tr>
		<td height="21" class="Estilo8">&nbsp;</td>
		<td height="21" colspan="4" class="Estilo8" id="datosrec18">
        <table width="100%">
        <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>Año</td><td>Per.</td><td>Insol</td><td>Reaj</td><td>Der Emi</td><td>Int Capi</td><td>Int</td><td>Benf</td><td>Tot Pago</td></tr>
        <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
        
        </table>
        
        </td>
        <td height="21" class="Estilo8">&nbsp;</td>
	</tr>
	<tr>
		<td height="24" class="Estilo8">&nbsp;</td>
        <td height="24" class="Estilo8">FIRMA/SELLO</td>
        <td height="24" class="Estilo8">&nbsp;</td>
		<td height="21" colspan="2" class="Estilo8" id="datosrec17">TOTAL PAGADO:  Nuevos Soles</td>
        <td height="24" class="Estilo8">&nbsp;</td>
	</tr>
	<tr>
    <td height="24" class="Estilo8">&nbsp;</td>
    <td height="24" class="Estilo8">cajero:</td>
		<td height="25" colspan="3" class="Estilo6" align="center" id="datosrec15"></td>
        <td height="24" class="Estilo8">&nbsp;</td>
	</tr>

	<tr>
    <td height="24" class="Estilo8">&nbsp;</td>
    		<td height="25" colspan="4" class="Estilo6" align="center" id="datosrec15">SON :  Nuevos Soles</td>
        <td height="24" class="Estilo8">&nbsp;</td>
	</tr>
    
	<tr>
		<td colspan="6" align="center">
		
		</td>
	</tr>

	<tr>
		<td colspan="6" class="Estilo8" id="datosrec"></td>
	</tr>
	<tr>
		<td colspan="6" class="Estilo8" align="left" id="codcajero"></td>
	</tr>
	<tr>
		<td colspan="6" class="Estilo8" align="left" id="fechaserver"></td>
	</tr>
	<tr>
		<td colspan="6" height="30">.</td>
	</tr>
</table>
</body>
</html>