<html>
<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<title>Municipalidad Distrital de Independencia</title>
		<script language="javascript">
		//window.print();
		//window.close();
		</script>
		<style type="text/css">
			BODY{
				padding-right: 0px;
				padding-left: 0px;
				padding-bottom: 0px;
				margin: 0px;
				padding-top: 0px;
				font-family: tahoma;
				background-color: white;
				font-size: 15px;
			}

			table{
				font-size: 15px;
			}

			.tabla_cuerpo {
				font-family: tahoma;
				font-size: 13px;
				border: 0px none ;
				background-color: #FFFFFF;
			}


			.recibo_pre_t2 {
				margin: 0px;
				padding: 0px;
				width: 100%;
			}

			.recibo_pre_t3 {
				margin: 0px;
				padding: 0px;
				width: 100%;
				border-collapse:collapse;
			}
			.recibo_pre_t3 TD {
				vertical-align: text-top;
				font-size: 13px;
			}
			.recibo_titulo_t1{

			}

			.recibo_cabecera_columas_1{
				text-decoration:underline;
			}
			.recibo_total_1{
				font-weight: bold;
			}

			.txt_total_paginas
			{
				PADDING-RIGHT: 0px;
				PADDING-LEFT: 0px;
				FONT-SIZE: 15px;
				PADDING-BOTTOM: 0px;
				COLOR: black;
				PADDING-TOP: 0px;
				FONT-STYLE: normal;
				FONT-FAMILY: tahoma;
				BACKGROUND-COLOR: white;
				border: 0px solid white;
			}
			.noVisible { VISIBILITY: hidden }

			BODY { PADDING-RIGHT: 0px; PADDING-LEFT: 0px; PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-TOP: 0px }
		</style>
</head>
<body onkeydown="onKeyDown();" onLoad="imprime()">
</br>
<table id="DataList1" cellspacing="0" border="0" width="80%">
<tr>
<td>

<?php echo $this->varhtml;?>

</td>
</tr>
</table>
<script language="javascript">
	function imprime(){
window.print();
window.close();
	}
</script>
</body>
</html>