<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Bandedocumen_expediente.js"></script>
<form id="frmexpediente">
<input type="hidden" name="txtValorexpe" id="txtValorexpe">   
<input type="hidden" name="txtNumexpe" id="txtNumexpe">  
<input type="hidden" name="txtAnoexpe" id="txtAnoexpe">  

<input type="hidden" name="txtNumeroexpe" id="txtNumeroexpe">  
<input type="hidden" name="txtAnioexpe" id="txtAnioexpe"> 
<input type="hidden" name="txtCodigoex" id="txtCodigoex"> 
<div >
    <fieldset class="ui-widget ui-widget-content">
      <legend style="margin-left:5px"></legend>
        <div class="contentForm">
	    	<div class="contentBox" style="padding:0 0 0 0px">   <!-- arriba derecha abajo izquierda -->
	    		<fieldset class="ui-widget ui-widget-content" style="padding: 8px;">
		    	 <legend style="margin-left:5px">Expedientes</legend>
		    	 	<table class="tableContent">
		    	 	  <tr>
					   <td width="100"><span id="lblNro">Nro Expediente:</span></td>
					   <td colspan="3"><input name="txtNroexpe" id="txtNroexpe" type="text" class="caja" size="20" maxlength="7"/> -
					   <input name="txtAniosexpe" id="txtAniosexpe" type="text" class="caja" size="20" maxlength="4" style="text-transform:uppercase;"/></td>
					  </tr>
		    	 	  <tr>
					   <td width="80"><span id="lblCodigo">Código:</span></td>
					   <td colspan="3"><input name="txtCodigoexpe" id="txtCodigoexpe" type="text" class="cajaoff" readonly size="20" /></td>
					  </tr>
					  <tr>
					   <td width="80"><span id="lblContribuyente">Contribuyente:</span></td>
					   <td colspan="3"><input name="txtContribuyenteexpe" id="txtContribuyenteexpe" type="text" class="cajaoff" readonly size="40" /></td>
					  </tr>
					  <tr>
					   <td width="80"><span id="lblUsuario">Ejecutor:</span></td>
					   <td colspan="3"><input name="txtEjecutivo" id="txtEjecutivo" type="text" class="cajaoff" readonly size="20" />
					   <select name="cmbEjecutivo" id="cmbEjecutivo" class="combo"><option>[Seleccione]</option></select></td>
					  </tr>
					  <tr>
					   <td width="80"><span id="lblUsuario">Auxiliar:</span></td>
					   <td colspan="3"><input name="txtAuxiliar" id="txtAuxiliar" type="text" class="cajaoff" readonly size="20" />
					   <select name="cmbAuxiliar" id="cmbAuxiliar" class="combo"><option>[Seleccione]</option></select></td>
					  </tr>
					  <tr>
					   <td width="80"><span id="lblFecha">Fecha:</span></td>
					   <td><input name="txtFechaexpe" id="txtFechaexpe" type="text" class="caja" size="12"/></td>	
					   <td><span id="lblFecha">Fecha Proyección:</span></td>
					   <td><input name="txtFechaexpeproyec" id="txtFechaexpeproyec" type="text" class="caja" size="12"/></td>				  	
					  </tr>
					  <tr>
			    	   <td width="80"><span id="lblObservaciones">Observaciones:</span></td>
			     	   <td colspan="3"><textarea name="txtObservaciones" id="txtObservaciones" cols="50" rows="3" class="caja" style="text-transform:uppercase;"></textarea></td>
			    	  </tr>	
					  <tr>
			    	   <td width="80"><span id="lblmemo">Memo:</span></td>
			     	   <td colspan="3"><textarea name="txtMemo" id="txtMemo" cols="50" rows="2" class="caja" style="text-transform:uppercase;"></textarea></td>
			    	  </tr>	
				    </table> 
				</fieldset>
	    	</div> 
	    	
	    	<div style="padding:0 8px 0 8px">
				<table id="detallesExpediente" class="hovertable" width="100%">
	              <tr>
		              <th><center><b>Documentos</b></center></th>
		              <th><center><b>Monto Total</b></center></th>
	              </tr>	            
	            </table>
			</div>
			
			<div style="padding:10px 5px 0 0">
				<table class="tableContent" align="right">
	              <tr>
	              	  <td><span id="lblMonto">Total:</span></td>
		              <td><input name="txtTotal" id="txtTotal" type="text" class="cajaoff" readonly size="8" style="text-align:right;font-weight:bold"/></td>
	              </tr>	              
	            </table>	
			</div>

		    <div class="contentForm">           
		       <div class="divButtons">
			    <table class="tableContent">
			     <tr>
			      <td style="padding-left:5px">
				    <input type="button" name="btnGrabaexpe" id="btnGrabaexpe" value="Grabar" />
					<input type="button" name="btnImpriexpe" id="btnImpriexpe" value="Imprimir REC" /> 
					<input type="button" name="btnImpriexpece" id="btnImpriexpece" value="Imprimir CEDULA" /> 
				    <input type="button" name="btnSalidaexpe" id="btnSalidaexpe" value="Salir" />
				  </td>
				 </tr>
			    </table>
			   </div>           
		    </div>
    
     
   </div>   
  </fieldset>
</div>
</form>
