<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Bandedocumen_recep.js"></script>
<form id="frmrecep">
<input type="text" name="txtValorexpe" id="txtValorexpe">   
<input type="text" name="txtNumexpe" id="txtNumexpe">  
<input type="text" name="txtAnoexpe" id="txtAnoexpe">  
<input type="text" name="txtorden" id="txtorden">  
</form>
