<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Mantingresos_formu.js"></script>
<form id="frmingreso">
<input type="hidden" name="actionIngreso" id="actionIngreso">
<div>
    <fieldset class="ui-widget ui-widget-content">
        <legend style="margin-left:5px"></legend>
        <div class="contentForm">
        	<table class="tableContent" width="100%">
			    <tr>
			      <td><span id="lblCodigo">Código:</span></td>
			      <td><input name="txtCodIngreso" id="txtCodIngreso" type="text" class="cajaoff" size="10"  readonly value="<?php echo $this->cod;?>" /></td>
			    </tr>
			    
			    <tr>
			      <td><span id="lblDescripcion">Descripón:</span></td>
			      <td><input name="txtDesIngreso" id="txtDesIngreso" type="text" class="caja" size="50" style="text-transform:uppercase;" value="<?php echo $this->nombre;?>"/></td>
			    </tr>
		     <!-- style="text-transform: uppercase"  -->
			    <tr>
			      <td><span id="lblResumen">Resumen:</span></td>
			      <td><input name="txtResumen" id="txtResumen" type="text" class="caja" size="50"  style="text-transform:uppercase;" value="<?php echo $this->resumen;?>"/></td>
			    </tr>
			    
			     <tr>
			      <td><span id="lblPartida">Partida:</span></td>
			      <td><input name="txtPartida" id="txtPartida" type="text" class="cajaoff" readonly size="50" maxlength="100" value="<?php echo $this->partida;?>"/></td>
			      <td><select name="cmbPartida" id="cmbPartida" class="combo"><option>[Seleccione]</option></select></td>
			    </tr>
			    
			    <tr>
			      <td><span id="lblContable">Contable:</span></td>
			      <td><select name="cmbContable" id="cmbContable" class="combo"><option>[Seleccione]</option></select></td>
			    </tr>
			    
			    <tr>
			      <td><span id="lblUit">UIT:</span></td>
			      <td><input name="txtUit" id="txtUit" type="text" class="caja" size="50" maxlength="100" value="<?php echo $this->porc_uit;?>"/></td>
			    </tr>
			    
			    <tr>
			      <td><span id="lblMonto">Monto:</span></td>
			      <td><input name="txtMonto" id="txtMonto" type="text" class="caja" size="50" maxlength="100" value="<?php echo $this->valor;?>"/></td>
			    </tr>
			    
			     <tr>
			      <td><span id="lblFuente">Fuente:</span></td>
			      <td><select name="cmbFuentes" id="cmbFuentes" class="combo"><option>[Seleccione]</option>
			      															<option>08</option>
			      															<option>09</option></select></td>
			    </tr>
			    
			    <tr>
			      <td><span id="lblArea">Area:</span></td>
			      <td><select name="cmbArea" id="cmbArea" class="combo"><option>[Seleccione]</option></select></td>
			    </tr>
			    
			    <tr>
			      <td colspan="7">
                  <div class="divButtons">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                    <td style="padding-left:5px">
           	          <input type="button" name="btnGrabaIngreso" id="btnGrabaIngreso" value="Grabar" />
                      <input type="button" name="btnSalirIngresos" id="btnSalirIngresos" value="Salir" />
                    </td>
                    <td></td>
                    </table>
                  </div>
                  </td>
		      </tr>
			    
		    </table>	    
        </div>
    </fieldset>	    
</div>
<div ID="MSG_ERROR"></div>
</form>