<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>

<script type="text/javascript" src="<?php echo $this->ruta; ?>js/js_tesoreportes.js"></script>
<div id="contentBox" class="ui-content-tabs">
	<ul>
    	<li class="contentBoxHead" style="padding:0 0 2px 5px"><?php echo $this->title;?></li>
    </ul>
    <div class="contentBox">
	    <fieldset class="ui-widget ui-widget-content">
		    <legend style="margin-left:5px">Reporte Tesoreria:</legend>
	        <div class="contentForm">
	   		<table class="tableContent">
              <tr>
              <td>
              <label><b>Tipo de Reporte: </b>
                <select id="tiporpt" class="combo" style="width:250px;">
	            	<!--<option value="0">Seleccionar...</option>
	            	--><option value="1">Reporte de Parte Diario</option>
	            	<!--<option value="2">Reporte de Tipo de Ingreso</option>
	            --></select>
              </label>
              </td>
              <td>
				<label><b>Desde: </b>
					<input name="tesodesde" id="tesodesde" type="text" value="<?php echo $this->tesodesde;?>" class="caja" size="20" maxlength="100" />
				</label>
			  </td>
              <td>
				<label><b>Hasta: </b>
					<input name="tesohasta" id="tesohasta" type="text" value="<?php echo $this->tesohasta;?>" class="caja" size="20" maxlength="100" />
				</label>
			  </td>
			  <td>
              <label><b>Cajeros: </b>
                <select id="cmbcajas" class="combo" style="width:100px;">
				</select>
              </label>
              </td>
              <td>
              <td><input type="button" id="btnbuscarecibos" value="Buscar" /></td>
              </tr>
            </table>	    
	    	</div>
	    </fieldset>
	    <br/>
	    <div id="gridRecibos"></div>
	    <br/>
	    <b> Total:  </b><input type="text" id="txttotal" value="0.00" class="cajaoff" size="20" maxlength="100" readonly style="text-align:right; width:95px;" />
	    <div class="divButtons">
		    <table border="0" cellpadding="0" cellspacing="0" width="100%">
		    <tr>
		    <td style="padding-left:5px">
				<input type="button" id="btnprintRpt" value="Imprimir Reporte" />
		    </td>
		    <td>
				<input type="button" id="btnprintPartidas" value="Reporte Partidas" />
			</td>
			</tr>
		    </table>
		</div>
    </div>
</div>