<script type="text/javascript" src="<?php echo $this->ruta; ?>js/js_Tesomenuemitidos.js"></script>

<table id="table3" cellspacing="1" cellpadding="1" width="500" border="0" align="center">
		<tr>
		<td style="height: 18px" nowrap>Fecha (D/M/A):</td>
		<td style="height: 18px">
			<input name="fecha" type="text"  id="fecha" class="caja" />
		</td>
	</tr>
	<tr>
		<td align="center" colspan="3">
			<br>
			<br>
			<br>
			<input type="button" name="btnaceptar" value="Aceptar" id="btnaceptar" />
			<input type="button" name="btnvolver" value="Volver" id="btnvolver" />
		</td>
	</tr>
</table>