<script type="text/javascript" src="<?php echo $this->ruta; ?>js/js_Tesomenuemitidos.js"></script>

<table id="table3" cellspacing="1" cellpadding="1" width="500" border="0" align="center">
	<tr>
		<td style="height: 17px" nowrap>Movimiento:</td>
		<td colspan="2"><input name="txtmovimiento" type="text" id="txtmovimiento"  class="caja"/></td>
	</tr>
	<tr>
		<td align="center" colspan="3">
			<br>
			<br>
			<br>
			<input type="button" name="btnaceptar" value="Aceptar" id="btnaceptar" />
			<input type="button" name="btnvolver" value="Volver" id="btnvolver" />
		</td>
	</tr>
</table>