<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	<title>Municipalidad Distrital de Independencia</title>
	<style type="text/css">
		BODY{
			padding: 0px;
			margin: 0px;
			font-family: tahoma;
			font-style: normal;
			page-break-after: avoid;
			page-break-before: avoid;
			page-break-inside: avoid;
			background-color: #FFF;
		}
		.text1{
			font-family: tahoma;
			font-size:11px;
			letter-spacing:2px;
		}
		.text2{
			font-family: tahoma;
			font-size:12px;
			letter-spacing:2px;
		}
		.text3{
			font-family: tahoma;
			font-size:15px;
			letter-spacing:2px;
		}
		.text4{
			font-family: tahoma;
			font-size:11px;
			letter-spacing:2px;
		}
	</style>
</head>
<body>
<div style="padding-left:20px">
	<table width="100%">
		<tr>
			<td>
			<table align="right" class="text1">
			<tr>
			<td align="right">Fecha y Hora Reporte:</td>
			<td align="left"><?php echo $this->fecha_imprime; ?>&nbsp;&nbsp;&nbsp;&nbsp;</td>
			</tr>
			<tr>
				<td align="right">Usuario:</td> 
				<td align="left"><?php echo $this->usuario; ?></td>
			</tr>
			</table>
			</td>
		</tr>
		<tr>
			<td align="center">
			<h1 class="text3">
			Municipalidad Distrital de Independencia<br/>
			Resúmen de conceptos
			</h1>
			</td>
		</tr>
		<tr>
			<td>
			<table class="text2" align="center" width="70%">
				<tr>
					<td align="right">Fecha Inicio:</td>
					<td align="left" id="fecha_desde"><?php echo $this->fecha_desde; ?></td>
					<td style='padding-left:20px' align="right">Fecha Fin:</td>
					<td id="fecha_hasta"><?php echo $this->fecha_hasta; ?></td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td align="right" style='padding-left:20px'><?php echo $this->texto; ?></td>
					<td><?php echo $this->cajero; ?></td>
				</tr>
			</table>
			</td>
		</tr>
		<tr>
			<td>
			<table class="text2" width="100%" cellpadding=0; cellspacing=0; border=0>
				<tr>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Tipo Op.</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Concepto</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Sub-Concepto</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Total</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Insoluto</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Reajuste</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Interes</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Emision</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Descuento</th>
				</tr>
				<?php echo $this->strHtml; ?>
			</table>
			</td>
		</tr>
	</table>
	<br>
<table id="table3" cellspacing="1" cellpadding="1" width="300" border="1" align="center">
	<tr>
		<td>&nbsp;</td>
		<td align="center"><strong>abono</strong></td>
	</tr>
	<tr>
		<td><strong>Insoluto</strong></td>
		<td align="right">
			<span id="lblinsolutoa"><?php echo $this->insoluto; ?></span></td>
	</tr>
	<tr>
		<td><strong>Der.Emi</strong></td>
		<td align="right">
			<span id="lblderemia"><?php echo $this->gastosad; ?></span></td>
	</tr>
	<tr>
		<td><strong>Reajuste</strong></td>
		<td align="right">
			<span id="lblreajustea"><?php echo $this->reajuste; ?></span></td>
	</tr>
	<tr>
		<td><strong>Intereses</strong></td>
		<td align="right">
			<span id="lblinteresesa"><?php echo $this->ninteres; ?></span></td>
	</tr>
	<!--<tr>
		<td><strong>Costas</strong></td>
		<td align="right">
			<span id="lblcostasa">0.00</span></td>
	</tr>
	<tr>
		<td><strong>Gastos</strong></td>
		<td align="right">
			<span id="lblgastosa">0.00</span></td>
	</tr>-->
	<tr>
		<td><strong>Descuentos</strong></td>
		<td align="right">
			<span id="lbldescuentosa"><?php echo $this->descuent; ?></span></td>
	</tr>
	<!--<tr>
		<td><strong>Total</strong></td>
		<td align="right">
			<span id="lbltotala"><?php echo $this->ntotales; ?></span></td>
	</tr>-->
</table>
<table align="center">		
<tr>
<td style="height: 21px" colspan="5" align="center">TOTAL RECAUDADO=
	<span id="lbltotalsuma"><b><?php echo $this->ntotales; ?></b></span><br>
	<br>
	<br>
	<span id="label9"><font size="2">NOTA: No se considera ningún recibo extornado</font></span>
</td>
</tr>
</table>
</div>
</body>
</html>