<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	<title>Municipalidad Distrital de Independencia</title>
	<style type="text/css">
		BODY{
			padding: 0px;
			margin: 0px;
			font-family: tahoma;
			font-style: normal;
			page-break-after: avoid;
			page-break-before: avoid;
			page-break-inside: avoid;
			background-color: #FFF;
		}
		.text1{
			font-family: tahoma;
			font-size:11px;
			letter-spacing:2px;
		}
		.text2{
			font-family: tahoma;
			font-size:12px;
			letter-spacing:2px;
		}
		.text3{
			font-family: tahoma;
			font-size:15px;
			letter-spacing:2px;
		}
		.text4{
			font-family: tahoma;
			font-size:11px;
			letter-spacing:2px;
		}
	</style>
</head>
<body>
<div style="padding-left:20px">
	<table width="100%">
		<tr>
			<td>
			<table align="right" class="text1">
			<tr>
			<td align="right">Fecha y Hora Reporte:</td>
			<td align="left"><?php echo $this->fecha_imprime; ?>&nbsp;&nbsp;&nbsp;&nbsp;</td>
			</tr>
			<tr>
				<td align="right">Usuario:</td> 
				<td align="left"><?php echo $this->usuario; ?></td>
			</tr>
			</table>
			</td>
		</tr>
		<tr>
			<td align="center">
			<h1 class="text3">
			Municipalidad Distrital de Independencia<br/>
			Recibos Emitidos (detallado)
			</h1>
			</td>
		</tr>
        <table class="text2">
        <tr>
						<th style="width:190px;">Nro.Recibo: <?php echo $this->movimiento;?></th>
						<td></td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
                    
					<tr>
                         <th colspan="4">
                         <?php echo $this->textcontri;?> 
                         <?php echo $this->codcontri;?>
                         <?php echo $this->textspacio;?>
                         Nombre: <?php echo $this->contribuyente;?>
                         </th>
			
					</tr>
                    </table>
		<!--<tr>
			<td>
			<table class="text2" align="center" width="70%">
				<tr>
					<td align="right">Fecha Inicio:</td>
					<td align="left" id="fecha_desde"></table>?php echo $this->fecha_desde; ?></td>
					<td style='padding-left:20px' align="right">Fecha Fin:</td>
					<td id="fecha_hasta"></table>?php echo $this->fecha_hasta; ?></td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td align="right" style='padding-left:20px'></table>?php echo $this->texto; ?></td>
					<td></?php echo $this->cajero; ?></td>
				</tr>
			</table>
			</td>
		</tr>-->
		<tr>
			<td>
			<table class="text2" width="100%" cellpadding=0; cellspacing=0; border=0>
				<tr>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Caja</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Mov.</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Mov. Caja</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Fecha</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Código</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Nombre</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Cpto.</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Sub.</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Año</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">INS</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">REA</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">INT</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">DE</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">TOT</th>
					<th height="25" style="border-top:1px #000 dotted; border-bottom:1px #000 dotted">Ex.</th>
				</tr>
				<?php echo $this->strHtml; ?>
			</table>
			</td>
		</tr>
	</table>
	<br>
	<table  align="center" width="50%" class="text2">
	  <tr>
		<td colspan="2" ><h1 class="text3">SIN EXTORNAR</h1></td>
		<td width="60">&nbsp;</td>
		<td colspan="2"><h1 class="text3">EXTORNADOS</h1></td>
	  </tr>
	  <tr>
		<td align="left" style="padding-top:6px">Efectivo</td>
		<td align="right" style="padding-top:6px"><?php echo $this->efectivo;?></td>
		<td>&nbsp;</td>
		<td align="left" style="padding-top:6px">Efectivo</td>
		<td align="right"><?php echo $this->extorno_efectivo;?></td>
	  </tr>
	  <tr>
		<td>Cheque </td>
		<td align="right"><?php echo $this->mcheques;?></td>
		<td>&nbsp;</td>
		<td>Cheque </td>
		<td align="right"><?php echo $this->extorno_mcheques;?></td>
	  </tr>
	  <tr>
		<td align="left" style="padding-top:6px"><h1 class="text4">TOTAL SIN EXTORNO</h1></td>
		<td align="right"><?php echo $this->total;?></td>
		<td>&nbsp;</td>
		<td align="left" style="padding-top:6px"><h1 class="text4">TOTAL EXTORNADOS</h1></td>
		<td align="right"><?php echo $this->extorno_total;?></td>
	  </tr>
	</table>
</div>
</body>
</html>