<h1>CARACTERÍSTICAS DE LA TITULARIDAD</h1>
<div style="margin-top:5px">
	<table class="tableContentc" width="100%">
    <tr>
    <td colspan="2">
    	<div class="lblCodField" style="width:25px">46</div>
        <div class="lblTxtField" style="width:250px;">Condición del Titular</div>
        <div class="lblCodField" style="width:25px">47</div>
        <div class="lblTxtField" style="width:250px;">Forma de Adquisición</div>
        <div class="lblCodField" style="width:25px">48</div>
        <div class="lblTxtField" style="width:145px;">Fecha de Adquisición</div>
        <div class="lblCodField" style="width:25px">49</div>
        <div class="lblTxtField" style="width:200px;">Cond. Esp. Predio</div>
        <div class="lblCodField" style="clear:left; width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
        <select name="cidtitu" id="cidtitu" class="comboc" style="width:248px"></select>
		</div>
        <div class="lblCodField" style="width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
        <select name="cidadqu" id="cidadqu" class="comboc" style="width:248px"></select>
		</div>
        <div class="lblCodField" style="width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
        <input type="text" id="feadqui" name="feadqui" class="cajac" style="width:143px" maxlength="10" />
        </div>
        <div class="lblCodField" style="width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
        <select name="cidcond" id="cidcond" class="comboc" style="width:198px"></select>
		</div>
    </td>
    <tr>
    <td>
    	<div class="lblCodField" style="border-top:0; width:25px">50</div>
        <div class="lblTxtField" style="border-top:0; width:125px;">Nro. Resolución</div>
        <div class="lblCodField" style="border-top:0; width:25px">51</div>
        <div class="lblTxtField" style="border-top:0; width:100px;">Porcentaje (%)</div>
        <div class="lblCodField" style="border-top:0; width:25px">52</div>
        <div class="lblTxtField" style="border-top:0; width:115px;">F. Inicio</div>
        <div class="lblCodField" style="border-top:0; width:25px">53</div>
        <div class="lblTxtField" style="border-top:0; width:110px;">F. Vencimiento</div>
        <div class="lblCodField" style="clear:left; width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
          <input name="nroreso" type="text" class="cajac" id="nroreso" style="width:123px" maxlength="10" />
        </div>
        <div class="lblCodField" style="width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
          <input name="nporcen" type="text" class="cajac" id="nporcen" style="width:98px" maxlength="20" />
        </div>
        <div class="lblCodField" style="width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
          <input name="fecinic" type="text" class="cajac" id="fecinic" style="width:113px" maxlength="10" />
        </div>
        <div class="lblCodField" style="width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
          <input name="fecvenc" type="text" class="cajac" id="fecvenc" style="width:108px" maxlength="10" />
        </div>
    </td>
    </tr>
    <tr>
      <td colspan="2"></tr>
	</table>
</div>
<br/>
<h1>DESCRIPCIÓN DEL PREDIO</h1>
<div style="margin-top:5px">
	<table class="tableContentc" width="100%">
    <tr>
    <td colspan="3">
    	<div class="lblCodField" style="width:25px">54</div>
        <div class="lblTxtField" style="width:250px;">Clasificación del Predio</div>
        <div class="lblCodField" style="width:25px">55</div>
        <div class="lblTxtField" style="width:250px;">Predio Catastral En</div>
        <div class="lblCodField" style="width:25px">56</div>
        <div class="lblTxtField" style="width:145px;">Código de Uso</div>
        <div class="lblCodField" style="width:25px">57</div>
        <div class="lblTxtField" style="width:200px;">Uso del Predio Catastral</div>
        <div class="lblCodField" style="clear:left; width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
        <select name="cidclas" id="cidclas" class="comboc" style="width:248px"></select>
		</div>
        <div class="lblCodField" style="width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
        <select name="cidpcat" id="cidpcat" class="comboc" style="width:248px"></select>
		</div>
        <div class="lblCodField" style="width:25px; border-top:0">&nbsp;</div>
        <div class="lblObjField" style="border-top:0">
        <select name="cidusos" id="cidusos" class="comboc" style="width:368px"></select>
		</div>
    </td>
    </tr>
    <tr>
    <td colspan="3">
    	<div class="lblCodField" style="width:25px; border-top:0">58</div>
        <div class="lblTxtField" style="width:90px; border-top:0">Estructuración</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="estruct" type="text" class="cajac" id="estruct" style="width:50px" maxlength="20" />
        </div>
        <div class="lblCodField" style="width:25px; border-top:0">59</div>
        <div class="lblTxtField" style="width:100px; border-top:0">Zonificación</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="zonific" type="text" class="cajac" id="zonific" style="width:60px" maxlength="20" />
        </div>
        <div class="lblCodField" style="width:25px; border-top:0">60</div>
        <div class="lblTxtField" style="width:110px; border-top:0">Area Terr. Título</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="areterr" type="text" class="cajac" id="areterr" style="width:62px" maxlength="14" />
        </div>
        <div class="lblCodField" style="width:25px; border-top:0">61</div>
        <div class="lblTxtField" style="width:110px; border-top:0">Area Terr. Declar.</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="aredecl" type="text" class="cajac" id="aredecl" style="width:62px" maxlength="14" />
        </div>
        <div class="lblCodField" style="width:25px; border-top:0">62</div>
        <div class="lblTxtField" style="width:110px; border-top:0">Area Terr. Verif.</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="areveri" type="text" class="cajac" id="areveri" style="width:61px" maxlength="14" />
        </div>
    </td>
    </tr>
    <tr>
    <td valign="top">
    	<div class="lblTxtField" style="width:80px; border-top:0">Lind. de Lte</div>
        <div class="lblCodField" style="width:25px; border-top:0">63</div>
        <div class="lblTxtField" style="width:95px; border-top:0">Med. en Campo</div>
        <div class="lblCodField" style="width:25px; border-top:0">64</div>
        <div class="lblTxtField" style="width:110px; border-top:0">Med. Según Título</div>
        <div class="lblCodField" style="width:25px; border-top:0">65</div>
        <div class="lblTxtField" style="width:95px; border-top:0">Col. en Campo</div>
        <div class="lblCodField" style="width:25px; border-top:0">66</div>
        <div class="lblTxtField" style="width:110px; border-top:0">Col. Según Título</div>
        <div class="lblTxtField" style="clear:left; width:80px; border-top:0">Frente</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="fremeca" type="text" class="cajac veryFBC" id="fremeca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="fremeti" type="text" class="cajac veryFBC" id="fremeti" style="width:134px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="frecoca" type="text" class="cajac veryFBC" id="frecoca" style="width:119px" maxlength="200" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="frecoti" type="text" class="cajac veryFBC" id="frecoti" style="width:134px" maxlength="200" />
        </div>
        <div class="lblTxtField" style="clear:left; width:80px; border-top:0">Derecha</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="dermeca" type="text" class="cajac veryFBC" id="dermeca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="dermeti" type="text" class="cajac veryFBC" id="dermeti" style="width:134px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="dercoca" type="text" class="cajac veryFBC" id="dercoca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="dercoti" type="text" class="cajac veryFBC" id="dercoti" style="width:134px" maxlength="14" />
        </div>
        <div class="lblTxtField" style="clear:left; width:80px; border-top:0">Izquierda</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="izqmeca" type="text" class="cajac veryFBC" id="izqmeca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="izqmeti" type="text" class="cajac veryFBC" id="izqmeti" style="width:134px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="izqcoca" type="text" class="cajac veryFBC" id="izqcoca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="izqcoti" type="text" class="cajac veryFBC" id="izqcoti" style="width:134px" maxlength="14" />
        </div>
        <div class="lblTxtField" style="clear:left; width:80px; border-top:0">Fondo</div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="fonmeca" type="text" class="cajac veryFBC" id="fonmeca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="fonmeti" type="text" class="cajac veryFBC" id="fonmeti" style="width:134px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="foncoca" type="text" class="cajac veryFBC" id="foncoca" style="width:119px" maxlength="14" />
        </div>
        <div class="lblObjField" style="border-top:0; border-left:0">
          <input name="foncoti" type="text" class="cajac veryFBC" id="foncoti" style="width:134px" maxlength="14" />
        </div>
    </td>
    <td valign="top">
        <h1 style="text-align:left; padding:3px 0 3px 0">SERVICIOS BÁSICOS</h1>
        <table class="tableContentc" width="100%">
        <tr>
        <td>
            <div class="lblCodField" style="width:25px">67</div>
            <div class="lblTxtField" style="width:60px;">Luz</div>
            <div class="lblObjField" style="border-left:0; padding:2px 5px 3px 5px">
          	<input type="checkbox" id="servluz" name="servluz" value="1"/>
        	</div>
            <div class="lblCodField" style="clear:left; width:25px; border-top:0;">68</div>
            <div class="lblTxtField" style="width:60px; border-top:0;">Agua</div>
            <div class="lblObjField" style="border-left:0; border-top:0; padding:2px 5px 3px 5px">
          	<input type="checkbox" id="seragua" name="seragua" value="1"/>
        	</div>
            <div class="lblCodField" style="clear:left; width:25px; border-top:0;">69</div>
            <div class="lblTxtField" style="width:60px; border-top:0;">Teléfono</div>
            <div class="lblObjField" style="border-left:0; border-top:0; padding:2px 5px 3px 5px">
          	<input type="checkbox" id="telefon" name="telefon" value="1"/>
        	</div>
            <div class="lblCodField" style="clear:left; width:25px; border-top:0;">70</div>
            <div class="lblTxtField" style="width:60px; border-top:0;">Desague</div>
            <div class="lblObjField" style="border-left:0; border-top:0; padding:2px 5px 3px 5px">
          	<input type="checkbox" id="desague" name="desague" value="1"/>
        	</div>
        </td>
        </tr>
        </table>    
    </td>
    <td valign="top">
    <div style="padding:9px"></div>
    <table class="tableContentc" width="100%">
        <tr>
        <td>
            <div class="lblCodField" style="width:25px">71</div>
            <div class="lblTxtField" style="width:90px;">N° Sum. Luz</div>
            <div class="lblObjField" style="border-left:0;">
          	<input name="sumiluz" type="text" class="cajac" id="sumiluz" style="width:120px" maxlength="20" />
        	</div>
            <div class="lblCodField" style="clear:left; width:25px; border-top:0;">72</div>
            <div class="lblTxtField" style="width:90px; border-top:0;">N° Cont. Agua</div>
            <div class="lblObjField" style="border-left:0; border-top:0;">
          	<input name="conagua" type="text" class="cajac" id="conagua" style="width:120px" maxlength="20" />
        	</div>
            <div class="lblCodField" style="clear:left; width:25px; border-top:0;">73</div>
            <div class="lblTxtField" style="width:90px; border-top:0;">N° Teléfono</div>
            <div class="lblObjField" style="border-left:0; border-top:0;">
          	<input name="ntelefo" type="text" class="cajac" id="ntelefo" style="width:120px" maxlength="20" />
        	</div>
        </td>
        </tr>
    </table>
    </td>
    </tr>
    </table>
</div>