<h1>IDENTIFICACIÓN DEL TITUTAL CATASTRAL</h1>
<br />
<fieldset class="ui-widget ui-widget-content">
	<div class="contentForm">
		<table class="tableContentc">
			<tr>
				<td colspan="3">
				<div style="margin:10px 5px 20px 0; float:left">
				<input type="button" id="btnSelectTitu" name="btnSelectTitu" value="&raquo; Seleccionar al Titular Catastral" style="height:30px; width:250px" />
				</div>
				<div style="margin:10px 0 20px 0; float:left">
				<input type="button" id="btnShowTitu" name="btnShowTitu" value="&raquo; Ver Datos del Titular Catastral" style="height:30px; width:230px" />
				</div>
				<div style="margin:10px 0 20px 5px; float:left">
				<input type="button" id="btnDelTitu" name="btnDelTitu" value="&raquo; Limpiar Datos" style="height:30px; width:150px" />
				</div>
				</td>
			</tr>
			<tr>
			  <td width="326">
			  <div class="lblCodField" style="width:25px">26</div>
			  <div class="lblTxtField" style="width:150px; border-bottom:0; border-left:0">
			  Tipo Doc. Identidad
			  </div>
			  <div class="lblObjField" style="border-bottom:0; border-left:0">
			  <input type="text" name="txtTipDocTitu" id="txtTipDocTitu" class="cajacoff" style="width:150px" readonly />
			  </div>
			  </td>
			  <td>&nbsp;</td>
			  <td width="326">
			  <div class="lblCodField" style="width:25px">27</div>
			  <div class="lblTxtField" style="width:150px; border-bottom:0; border-left:0">
			  Nro. Documento
			  </div>
			  <div class="lblObjField" style="border-bottom:0; border-left:0">
			  <input type="text" name="txtNumDocTitu" id="txtNumDocTitu" class="cajacoff" style="width:150px" readonly />
			  </div>
			  </td>
			</tr>
			<tr>
			  <td colspan="3">
			  <div class="lblCodField" style="width:25px">28</div>
			  <div class="lblTxtField" style="width:150px; border-left:0">
			  Nombres
			  </div>
			  <div class="lblObjField" style="border-left:0">
			  <input type="text" name="txtNomTitu" id="txtNomTitu" class="cajacoff" style="width:484px" readonly />
			  </div>
			  </td>
			</tr>
			<tr>
			  <td>
			  <div class="lblCodField" style="width:25px; border-top:0;">29</div>
			  <div class="lblTxtField" style="width:150px; border-top:0; border-bottom:1px #6EA7D1 solid; border-left:0">
			  Apellido Paterno
			  </div>
			  <div class="lblObjField" style="border-top:0; border-left:0">
			  <input type="text" name="txtApePatTitu" id="txtApePatTitu" class="cajacoff" style="width:150px" readonly />
			  </div>
			  </td>
			  <td style="border-bottom:0;">&nbsp;</td>
			  <td>
			  <div class="lblCodField" style="width:25px; border-top:0;">30</div>
			  <div class="lblTxtField" style="width:150px; border-top:0; border-left:0">
			  Apellido Materno
			  </div>
			  <div class="lblObjField" style="border-top:0; border-left:0">
			  <input type="text" name="txtApeMatTitu" id="txtApeMatTitu" class="cajacoff" style="width:150px" readonly />
			  </div>
			  </td>
			</tr>
		</table>
		<br />
		<br/>	    
	</div>
</fieldset>