<h1>INSCRIPCIÓN DEL PREDIO CATASTRAL EN EL REGISTRO DE PREDIOS</h1>
<div style="margin-top:10px">
<table class="tableContentc">
<tr>
  <td valign="top">
  		<div class="lblCodField" style="width:30px">104</div>
        <div class="lblTxtField" style="width:150px;">Tipo Partida Registral</div>
        <div class="lblObjField" style="border-left:0">
        <select name="cidregi" id="cidregi" class="comboc" style="width:150px"></select>
		</div>
        <div class="lblCodField" style="width:30px">105</div>
        <div class="lblTxtField" style="width:140px;">Número</div>
        <div class="lblObjField" style="border-left:0">
        <input type="text" id="vnumero" name="vnumero" class="cajac" style="width:110px" maxlength="20" />
		</div>
        <div class="lblCodField" style="width:30px">106</div>
        <div class="lblTxtField" style="width:120px;">Fojas</div>
        <div class="lblObjField" style="border-left:0">
        <input type="text" id="vafojas" name="vafojas" class="cajac" style="width:180px" maxlength="20" />
		</div>
  </td>
</tr>
<tr>
  <td valign="top">
  		<div class="lblCodField" style="width:30px; border-top:0">107</div>
        <div class="lblTxtField" style="width:150px; border-top:0">Asiento</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="asiento" name="asiento" class="cajac" style="width:150px" maxlength="20" />
		</div>
        <div class="lblCodField" style="width:30px; border-top:0">108</div>
        <div class="lblTxtField" style="width:140px; border-top:0">Fec. Insc. del Predio</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="fecinsp" name="fecinsp" class="cajac" style="width:110px" maxlength="10" />
		</div>
        <div class="lblCodField" style="width:30px; border-top:0">109</div>
        <div class="lblTxtField" style="width:120px; border-top:0">Declar. de Fábrica</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <select name="cidfabr" id="cidfabr" class="comboc" style="width:180px"></select>
		</div>
  </td>
  </tr>
<tr>
  <td valign="top">
  		<div class="lblCodField" style="width:30px; border-top:0">110</div>
        <div class="lblTxtField" style="width:150px; border-top:0">Asi. Insc. de Fábrica</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="insfabr" name="insfabr" class="cajac" style="width:150px" maxlength="20" />
		</div>
        <div class="lblCodField" style="width:30px; border-top:0">111</div>
        <div class="lblTxtField" style="width:140px; border-top:0">Fec. Insc. de Fábrica</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="fecinsf" name="fecinsf" class="cajac" style="width:110px" maxlength="10" />
		</div>
  </td>
  </tr>
</table>
</div>
<br/>
<h1>EVALUACIÓN DEL PREDIO CATASTRAL</h1>
<div style="margin-top:10px">
<table class="tableContentc">
<tr>
  <td valign="top">
  		<div class="lblCodField" style="width:30px;">112</div>
        <div class="lblTxtField" style="width:300px; border-right:0">Evaluación del Predio Catastral</div>
        <div class="lblCodField" style="clear:left; border-top:0; width:30px">&nbsp;</div>
        <div class="lblObjField" style="border-top:0; border-right:0">
        <select name="cideval" id="cideval" class="comboc" style="width:299px"></select>
		</div>
  </td>
  <td valign="top">
  		<div class="lblCodField" style="width:30px;">113</div>
        <div class="lblTxtField" style="width:301px;">Area de Terreno Invadidad (m2)</div>
        
        <div class="lblCodField" style="clear:left; width:30px; border-top:0">&nbsp;</div>
        <div class="lblTxtField" style="width:150px; border-top:0">En Lote Colindante</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="lotecol" name="lotecol" class="cajac" style="width:150px" maxlength="14" />
		</div>
        <div class="lblCodField" style="clear:left; width:30px; border-top:0">&nbsp;</div>
        <div class="lblTxtField" style="width:150px; border-top:0">En Jardín de Aislamiento</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="jaraisl" name="jaraisl" class="cajac" style="width:150px" maxlength="14" />
		</div>
        <div class="lblCodField" style="clear:left; width:30px; border-top:0">&nbsp;</div>
        <div class="lblTxtField" style="width:150px; border-top:0">En Area Pública</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="arepubl" name="arepubl" class="cajac" style="width:150px" maxlength="14" />
		</div>
        <div class="lblCodField" style="clear:left; width:30px; border-top:0">&nbsp;</div>
        <div class="lblTxtField" style="width:150px; border-top:0">En Area Intangible</div>
        <div class="lblObjField" style="border-left:0; border-top:0">
        <input type="text" id="areinta" name="areinta" class="cajac" style="width:150px" maxlength="14" />
		</div>
  </td>
</tr>
</table>
</div>