<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Recibomodi.js"></script>
<form id="frmrecibomodi">

<div >
     <fieldset class="ui-widget ui-widget-content">
        <legend style="margin-left:5px"></legend>
        <div class="contentForm">
        	<table class="tableContent" width="100%">
				<!--
				<tr>
			      <td><span id="lblUsuario">Nro Documento:</span></td>
			      <td><input name="txtNumdocu" id="txtNumdocu" type="text" class="caja" size="40" maxlength="100" style="text-transform:uppercase;"  /></td>
			    </tr>		
				-->	
			    <tr>
			      <td><span id="lblUsuario">Usuario:</span></td>
			      <td><input name="txtUsuario" id="txtUsuario" type="text" class="cajaoff" size="40" maxlength="100" style="text-transform:uppercase;" readonly /></td>
			    </tr>
			     		    
			    <tr>
			      <td><span id="lblGlosa">Glosa:</span></td>
			      <td><textarea name="txtGlosa" id="txtGlosa" cols="33" rows="3" class="caja" style="text-transform:uppercase;"></textarea> </td>
			    </tr>
				
				
			    
			    <tr>
			      <td colspan="7">
                  <div class="divButtons">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                    <td style="padding-left:5px">
           	          <input type="button" name="btnGenerarRecibo" id="btnGenerarRecibo" value="Generar" />
                      <input type="button" name="btnSalirRecibo" id="btnSalirRecibo" value="Salir" />
                    </td>
                    </tr>
                    </table>
                  </div>
                  </td>
		      </tr>
			    
		    </table>	    
        </div>
    </fieldset>	 
</div>
</form>
