<fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">Características del Predio:</legend>
    <div class="contentForm">
    	<fieldset class="ui-widget ui-widget-content">
	    <legend style="margin-left:5px">Ubicación:</legend>
        <div class="contentForm">
        	<div style="float:left">
           	<table class="tableContent">
			<tr>
			    <td><span id="lblCp">CP:</span></td>
			    <td colspan="3"><input name="txtCp" id="txtCp" type="text" class="cajaoff" size="100" maxlength="100" readonly value="<?php echo $this->nombre_cp;?>" /></td>
			    </tr>
			    <tr>
			    <td><span id="lblVia">Vía:</span></td>
			    <td><input name="txtVia" id="txtVia" type="text" class="cajaoff" size="50" maxlength="100" readonly value="<?php echo $this->nombre_via;?>"/></td>
			    <td><span id="lblCvia">Código:</span></td>
			    <td><input name="txtCvia" id="txtCvia" type="text" class="cajaoff" size="34" maxlength="100" readonly value="<?php echo $this->cod_via;?>" /></td>
			    </tr>
			    <tr>
			    <td><span id="lblDir">Dir:</span></td>
			    <td colspan="3"><input name="txtDir" id="txtDir" type="text" class="caja" size="100" maxlength="100" value="<?php echo $this->direccion;?>" style="text-transform:uppercase;"/></td>
			</tr>
		    </table>
            </div>
            <!-- <div style="float:left">
            	<input type="button" id="btnCopiar" value="Copiar Predio" />
            </div>-->
             <div style="float:left">
				<input type="button" id="btnBusVia" value="Buscar Via" />
			</div>
        	<div style="clear:both">
            <table class="tableContent">
              <tr>
              <td><span id="lblNro">Nro:</span></td>
              <td><input name="txtNro" id="txtNro" type="text" class="caja" size="10" maxlength="4" value="<?php echo $this->nro;?>" style="text-transform:uppercase;"/></td>
              <td><span id="lblNro">Dpto:</span></td>
              <td><input name="txtDpto" id="txtDpto" type="text" class="caja" size="10" maxlength="4" value="<?php echo $this->num_dpto;?>" style="text-transform:uppercase;"/></td>
              <td><span id="lblNro">Mza:</span></td>
              <td><input name="txtMza" id="txtMza" type="text" class="caja" size="10" maxlength="4" value="<?php echo $this->num_mza;?>" style="text-transform:uppercase;"/></td>
              <td><span id="lblNro">Lte:</span></td>
              <td><input name="txtLte" id="txtLte" type="text" class="caja" size="10" maxlength="4" value="<?php echo $this->num_lote;?>" style="text-transform:uppercase;"/></td>
              <td><span id="lblNro">Sub Lte:</span></td>
              <td><input name="txtSubLte" id="txtSubLte" type="text" class="caja" size="10" maxlength="4" value="<?php echo $this->num_sublote;?>" style="text-transform:uppercase;"/></td>
              <td><span id="lblNro">Frontis:</span></td>
              <td><input name="txtFrontis" id="txtFrontis" type="text" class="caja" size="10" maxlength="100" value="<?php echo $this->frontis;?>" /></td>
              </tr>
            </table>
            </div>        	    
        </div>
        </fieldset>
        <br/>
        <div style="float:left; margin-right:5px">
        	<fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Descripción:</legend>
            <div class="contentForm">
            <table class="tableContent">
              
              <tr>
              <td><span id="lblTipPredio">Uso:</span></td>
              <td>
              <select name="cmbUso" id="cmbUso" class="combo" style="width: 200px;">
              <option>[Seleccione]</option>
              <option value="1">Ocultar Pisos</option>
              <option value="2">Mostrar Pisos</option>
              </select>
              </td>
              </tr>
              <tr>
              <td><span id="lblTipPredio">Tipo de predio urbano:</span></td>
              <td><select name="cmbTipPredio" id="cmbTipPredio" class="combo" style="width: 200px;"></select></td>
              </tr>
              <tr>
              <td><span id="lblTipPredio">Estado de construcción:</span></td>
              <td><select name="cmbEstadoConst" id="cmbEstadoConst" class="combo" style="width: 200px;"></select></td>
              </tr>
              <tr>
              <td><span id="lblTipPredio">Condición de la propiedad:</span></td>
              <td><select name="cmbCondicion" id="cmbCondicion" class="combo" style="width: 200px;"></select></td>
              </tr>
              <tr>
                <td><span id="lblNro">Nro. Pisos:</span></td>
                <td><input name="txtNroPiso" id="txtNroPiso" type="text" class="cajaoff" size="10" maxlength="100" readonly value="<?php echo $this->num_piso;?>"/></td>
              </tr>
              <tr>
                <td><span id="lblNro">Nro. Cond:</span></td>
                <td><input name="txtNroCond" id="txtNroCond" type="text" class="caja" size="10" maxlength="100" value="<?php echo $this->num_condo;?>" /></td>
              </tr>
              <tr>
                <td><span id="lblNro">Area de terreno (m2):</span></td>
                <td><input name="txtAreaTerreno" id="txtAreaTerreno" type="text" class="caja" size="10" maxlength="100" value="<?php echo $this->area_terreno;?>" /></td>
              </tr>
               <tr>
                <td><span id="lblNro">Area de Comun (m2):</span></td>
                <td><input name="txtAreaComun" id="txtAreaComun" type="text" class="caja" size="10" maxlength="100" value="<?php echo $this->area_comun;?>" /></td>
              </tr>
              <tr>
                <td><span id="lblNro">Porcentage Propiedad:</span></td>
                <td><input name="txtPorcenPropiedad" id="txtPorcenPropiedad" type="text" class="caja" size="10" maxlength="100" value="<?php echo $this->porcen_propiedad;?>" />
                %</td>
              </tr>
               <tr>
                <td><span id="lblNro">Predio Afecto</span></td>
                <td><input type="checkbox" name="chAfectoPred" id ="chAfectoPred" value="1" /> 
                  Afecto
</td>
              </tr>
              </table>
            </div>
            </fieldset>            
        </div>
        <div style="float:left; margin:0 5px 0 5px">
        <fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Datos compra y/o venta:</legend>
            <div class="contentForm">
            <table class="tableContent">
              <tr>
              <td><span id="lblFecAdqui">F. Adquisición:</span></td>
              <td><input name="txtFecAdqui" id="txtFecAdqui" type="text" class="caja" size="12" maxlength="10" value="<?php echo $this->fec_compra;?>" /></td>
              </tr>
              <tr>
              <td><span id="lblFecTrans">F. Transferencia:</span></td>
              <td><input name="txtFecTrans" id="txtFecTrans" type="text" class="caja" size="12" maxlength="10" value="<?php echo $this->fec_venta;?>"/></td>
              </tr>
              <tr>
                <td><span id="lblFecAdqui">Predio vendido</span></td>
                <td><input type="checkbox"></td>
              </tr>
            </table>
            </div>
        </fieldset>
        <br/>
        <fieldset class="ui-widget ui-widget-content">
        <legend style="margin-left:5px">Doc. sobre la construcción:</legend>
        <div class="contentForm">
        <table class="tableContent">
          <tr>
          <td><span id="lblFecAdqui"><input type="checkbox" name="chbLicencia" id ="chbLicencia" value="1"> Licencia de construcción</span></td>
          </tr>
          <tr>
          <td><span id="lblFecAdqui"><input type="checkbox" name="chbConformidad" id ="chbConformidad" value="1"> Conformidad de obra</span></td>
          </tr>
          <tr>
          <td><span id="lblFecAdqui"><input type="checkbox" name="chbDeclaracionFab" id ="chbDeclaracionFab" value="1"> Declaración de fábrica</span></td>
          </tr>
        </table>
        </div>
        </fieldset>
        </div>
        <div style="float:left; margin-left:5px">
        	<fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Servicios:</legend>
            <div class="contentForm">
            <table class="tableContent">
              <tr>
              <td><span id="lblFecAdqui">Sum. Agua:</span></td>
              <td><input name="txtAgua" id="txtAgua" type="text" class="caja" size="20" maxlength="10" value="<?php echo $this->sum_luz;?>" style="text-transform:uppercase;"/></td>
              </tr>
              <tr>
              <td><span id="lblFecAdqui">Sum. Luz:</span></td>
              <td><input name="txtLuz" id="txtLuz" type="text" class="caja" size="20" maxlength="10" value="<?php echo $this->sum_agua;?>" style="text-transform:uppercase;"/></td>
              </tr>
            </table>
            </div>
            </fieldset>
            <br/>
            <fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Códigos Alternos:</legend>
            <div class="contentForm">
            <table class="tableContent">
              <tr>
              <td><span id="lblFecAdqui">Cod. Predio:</span></td>
              <td><input name="txtCodPred" id="txtCodPred" type="text" class="caja" size="20" maxlength="10" style="text-transform:uppercase;"/></td>
              </tr>
            </table>
            </div>
            </fieldset>
            <br/>
            <fieldset class="ui-widget ui-widget-content">
            <legend style="margin-left:5px">Observaciones:</legend>
            <div class="contentForm">
            <table class="tableContent">
              <tr>
              <td><textarea name="txtObs" cols="30" rows="3" style="text-transform:uppercase;" class="caja" id="txtObs"><?php echo $this->obs;?></textarea></td>
              </tr>
            </table>
            </div>
            </fieldset>
        </div>
        <br style="clear:both"/>
    </div>
    <DIV ID="MSG_ERROR"></DIV>
</fieldset>