<fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">&nbsp;VIII. Detalle de Pago</legend>
    <div class="contentForm">
    	<table id="detallePago" class="hovertable" width="100%">
        <tr>
			<th><center>N° Recibo</center></th>
        	<th><center>Fecha</center></th>
            <th><center>Observación</center></th>
            <th><center>Monto</center></th>
        </tr>
        <tr>
        	<td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>    
   	  </table>
        <br/>
        <div class="contentBoxBr" style="width:300px; float:right">
        <table class="tableContent">
          <tr>
          <td><span id="lblPagPen">Pago Pendiente:</span></td>
          <td><span id="lblPagPenVal" style="color:red">0.00</span></td>
          <td><span id="lblPagRea">Pago Realizado:</span></td>
          <td><span id="lblPagReaVal" style="color:blue">0.00</span></td>
          </tr>
        </table>
        </div>
        <br style="clear:both">
    </div>
</fieldset>
<br/>
<fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">&nbsp;IX. Parámetros</legend>
    <div class="contentForm">
    <textarea name="txtNro9" rows="3" class="caja" id="txtNro10" style="width:100%"></textarea>
    </div>
</fieldset>
<br/>
<fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">&nbsp;IX. Datos Opcionales</legend>
    <div class="contentForm">
    <table class="tableContent" width="100%">
      <tr>
      <td><span id="lblTipAuto">N° INDECI:</span></td>
      <td><input name="txtNro4" id="txtNro5" type="text" class="cajaoff" size="10" maxlength="100" readonly /></td>
      <td><span id="lblTipAuto">N° FOLIOS INICIAL:</span></td>
      <td><input name="txtNro2" id="txtNro2" type="text" class="caja" size="10" maxlength="100" /></td>
      </tr>
      <tr>
        <td colspan="4"><span id="lblTipPredio">Observación del Expediente:</span></td>
      </tr>
      <tr>
        <td colspan="4"><textarea name="txtNro7" rows="3" class="caja" id="txtNro8" style="width:100%"></textarea></td>
      </tr>
    </table>
    </div>
</fieldset>
<br/>
<fieldset class="ui-widget ui-widget-content">
    <legend style="margin-left:5px">&nbsp;X. Datos Opcionales</legend>
    <div class="contentForm">
    <table class="tableContent" width="100%">
      <tr>
      <td><label><input id="chkCarSol" type="checkbox"> <span id="lblCarSol">ORD. 48-2003 (DISCAPACIDAD)</span></label></td>
      <td><span id="lblTipAuto">N° CONADIS:</span></td>
      <td><input name="txtNro2" id="txtNro2" type="text" class="caja" size="10" maxlength="100" /></td>
      </tr>
    </table>
    </div>
</fieldset>
