<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>

<style type="text/css">
.invisible {display: none; }
</style>

<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Verbajapre.js"></script>

<form id="frmBusbajpre">
<div>
    <div>
	       					
		<input type="hidden" id="txtCodigo" name="txtCodigo" />			
	    	
	    <br/>
	    <div id="gridVerbajapred"></div>
	    <br/>
	   
    </div>
</div>
</form>