<?php header('Content-Type: text/html; charset=iso-8859-1');?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_Fiscalizacionpredio_muestrainstalacion.js"></script>
<div style="overflow:visible;">
	<div style="margin-left:3px;float:left; width:755px" id='xgridInstalacion'></div>
	<div style="margin-right:3px;float:right;" id='btnsInstalacion'></div>
</div>

<div class="divButtons">
	<table class="tableContent">
	<tr>
		<td style="padding-right:43px;padding-top:6px;padding-bottom:4px;">
			<button type="button" style="width:116px;border-radius: 1px;font-family: tahoma,arial,verdana,sans-serif;text-align:left; padding-left:5px" id="btnCerrarxInstalacion">Cerrar</button>
		</td>
	</tr>
	<td style="padding-left:40px"></td>
	</table>
</div>
