<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script type="text/javascript" src="<?php echo $this->ruta;?>js/js_detallefrac.js"></script>
<form id="frmListadofrac">

<input type="hidden" name="actionFraccionamiento" id="actionFraccionamiento">

		<fieldset class="ui-widget ui-widget-content" style="padding: 8px;">
    		<div style="float:left; padding-right:40px">
    			<table class="tableContent" width="100%">
			    <tr>
			    <td><span id="lblCodigo">Código:</span></td>
			    <td><div id="divCodFracc"></div></td>
			    </tr>
			    <tr>
			    <td><span id="lblNombre">Contribuyente:</span></td>
			    <td><div id="divNombre"></div></td>
			    </tr>
			    </table>
    		</div>
    	</fieldset>
	
<div id="gridListado">
</div>

<div class="divButtons">
	<table class="tableContent" width="100%">
		<tr>
			<td style="padding-left:5px">
			    <input type="button" id="btnSalir" value="Salir" />
				<input type="button" id="btnReporteFracc" value="Reporte" />
			</td>
		</tr>
    </table>
</div>
</form>