<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>

<script>
var codigocaja='<?php echo $this->codigocaja ?>';
var data1='<?php echo $this->data; ?>';
</script>

<script type="text/javascript" src="<?php echo $this->ruta; ?>js/js_Tesocaja.js"></script>
<form id="frmcaja" >
	<div class="contentBoxMain">
    	<div>
        <fieldset class="ui-widget ui-widget-content" style="padding: 8px;">
   		  <legend style="margin-left:5px">Datos del Contribuyente:</legend>
            <table class="tableContent">
			    <tr>
			    <td><span>Código:<input style='display:none;' type="text" name="txtcod" id="txtcod" value='<?php echo $this->codigocaja ?>' /></span></td>
			    <td><div id="divCodigo">...........</div></td>
			    <td style='padding-left:30px'><span>Documento:</span></td>
			    <td><div id="divDocu">...........</div></td>
			    <td style='padding-left:30px'><span>Contribuyente:</span></td>
			    <td><div id="divContri">...........</div></td>
			    </tr>
			    <tr>
			    <td><span>Dirección:</span></td>
			    <td colspan="5"><div id="divDirec">...........</div></td>
			    </tr>		    
			</table>
        </fieldset>
        </div>
        <br/>
        <div style="float:left; padding-right:5px">
        	<fieldset class="ui-widget ui-widget-content" style="padding: 8px;">
	    		<legend style="margin-left:5px">Concepto:</legend>
	    		<div class="contentBoxBrSup">
                <label><input type="checkbox" id="chkTotConceptos" > <span>Todos/Ninguno</span></label>
                </div>
                <div class="contentBoxBr" style="background-color:#E6FFFF; height:100px; width:130px; overflow:auto">
                <table width="100%">
                <tr>
                    <td><label><input type="checkbox" id="conceptos[]" name="conceptos[]" value="*02.01*"> Predial</label></td>
                  </tr>
                    <tr>
                    <td><label><input type="checkbox" id="conceptos[]" name="conceptos[]" value="*11.00*,*11.04*"> Arbitrios</label></td>
                    </tr>
                    <tr>
                    <td><label><input type="checkbox" id="conceptos[]" name="conceptos[]" value="*12.23*"> Fracc. </label></td>
                    </tr>
					<tr>
                    <td><label><input type="checkbox" id="conceptos[]" name="conceptos[]" value="*90.29*"> Multa </label></td>
                    </tr>
					<tr>
                    <td><label><input type="checkbox" id="conceptos[]" name="conceptos[]" value="*90.00*"> Costas </label></td>
                    </tr>
					<tr>
                    <td><label><input type="checkbox" id="conceptos[]" name="conceptos[]" value="*90.09*"> Gastos </label></td>
                    </tr>
					<tr>
                    <td><label><input type="checkbox" id="conceptos[]" name="conceptos[]" value="*90.32*"> FRAnt </label></td>
                    </tr>
					<tr>
                    <td><label><input type="checkbox" id="conceptos[]" name="conceptos[]" value="*00.00*"> COAnt </label></td>
                    </tr>
                    <tr>
                    <td><label><input type="checkbox" id="conceptos[]" name="conceptos[]" value="*44.69*"> Licencia </label></td>
                    </tr>
					</table>
                </div>
            </fieldset>
        </div>
        <div style="float:left; padding-right:5px">
        	<fieldset class="ui-widget ui-widget-content" style="padding: 8px;">
	    		<legend style="margin-left:5px">Periodo:</legend>
	    		<div class="contentBoxBrSup">
	    		<label><input id="chkTotPeriodos" type="checkbox"> <span>Todos/Ninguno</span></label></div>
                <div id="boxCajaPeriodo" class="contentBoxBr" style="background-color:#E6FFFF; height:100px; width:130px; overflow:auto">
                 
                </div>
            </fieldset>
        </div>
        <div style="float:left; padding-right:5px">
        	<fieldset class="ui-widget ui-widget-content" style="padding: 8px;">
	    		<legend style="margin-left:5px">Arbitrio:</legend>
	    		<div class="contentBoxBrSup">
	    		<label><input id="chkTotArbitrio" type="checkbox"> <span>Todos/Ninguno</span></label></div>
                <div class="contentBoxBr" style="background-color:#E6FFFF; height:100px; width:130px">
                <table width="100%">                    
                    <tr>
                    <td><label><input type="checkbox" id="chkarbitrio[]" name="chkarbitrio[]" value="*11.02*"> Barrido Vías</label></td>
                    </tr>
                    <tr>
                    <td><label><input type="checkbox" id="chkarbitrio[]" name="chkarbitrio[]" value="*11.01*"> Recol. Res.</label></td>
                    </tr>
                    <tr>
                    <td><label><input type="checkbox" id="chkarbitrio[]" name="chkarbitrio[]" value="*11.03*"> Parq. Jard.</label></td>
                    </tr>
                    <tr>
					<td><label><input type="checkbox" id="chkarbitrio[]" name="chkarbitrio[]" value="*11.04*"> Serenazgo.</label></td>                    
                    </tr>
                </table>	    
                </div>
            </fieldset>
        </div>
        <div style="float:left; padding-right:5px">
        	<fieldset class="ui-widget ui-widget-content" style="padding: 8px;">
	    		<legend style="margin-left:5px">Año:</legend>
	    		<div class="contentBoxBrSup">
	    		<label><input id="chkTotAnios" type="checkbox"> <span>Todos/Ninguno</span></label></div>
                <div  id="divAnios" class="contentBoxBr" style="background-color:#E6FFFF; height:100px; width:130px; overflow:auto">
                   
                </div>
            </fieldset>
        </div>        
        <div style="float:left;">
        	<fieldset class="ui-widget ui-widget-content" style="padding: 8px;">
	    		<legend style="margin-left:5px">Predio:</legend>
	    		<div class="contentBoxBrSup">
	    		<label><input id="chkTotPreddd" type="checkbox"> <span>Todos/Ninguno</span></label></div>
              <div id="divPredios" class="contentBoxBr" style="background-color:#E6FFFF; height:100px; width:355px; overflow:auto">

                </div>
            </fieldset>
        </div>
		<br style="clear:both">
		<div class="divButtons" style="margin:10px 0 10px 0;">
		<table>
		<tr>
		<td style="padding-right:5px"><input type="button" id="btnVerRec" value="Ver Recibos" /></td>
		<!--<td style="padding-right:5px"><input type="button" id="btnpgcoactivo" value="Pago Coactivo" /></td>
		<td style="padding-right:5px"><input type="button" id="btnpg2013" value="Pago 2013" /></td>
		<td style="padding-right:5px"><input type="button" id="btnpgpronto" value="Pronto Pago" /></td>-->

		
		<td style="padding-right:5px"><input type="button" id="btnMostrar" value="Ver Deuda" /></td>
		<!--
		<td style="padding-right:5px"><input type="button" id="btnProntoPago" value="Pronto Pago IP y Arb." /></td>
		<td style="padding-right:5px"><input type="button" id="btnProntoPagoMulta" value="Pronto Pago Multa" style="width:150px;"/></td>
		<td style="padding-right:5px"><input type="button" id="btnProntoPagoCoactivo" value="Pronto Pago Coact." style="width:150px;"/></td>
		-->
		<td style="padding-right:5px"><input type="button" id="btnPagarRecibos" value="Pagar" style="width:100px;"/></td>
	
		
		<td style="padding-right:5px"><input type="button" id="btnCerrar" value="Cerrar Ventana" /></td>
	
		</td>
		</tr>
		</table>
		</div>
		
		<!--manuel-->
		<!--
		<div class="divButtons" style="margin:10px 0 10px 0;">
		<table>
		<tr>
		
		<td style="padding-right:5px"><input type="button" id="btnPagafaci2014a" value="Paga Facil 2015 (10%)" style="border-color: #EF0A38 #EF0A38 #EF0A38;" /><td>
		<td style="padding-right:5px"><input type="button" id="btnPagafaci2014b" value="Paga Facil 2015 (5%)" style="border-color: #EF0A38 #EF0A38 #EF0A38;" /><td>

		</tr>
		</table>
		</div>
		-->
		<!---------->
		
		<td><input type="hidden" id="txtverifica" name="txtverifica"></td>
		
		
		
		
		
		<div class="divButtons" style="margin:10px 0 10px 0;">
		<table>
		<tr>
		<td style="padding-right:5px">
				<input type="radio" name="rdTpobus" id="chFr" value="1">FR
				<input type="radio" name="rdTpobus" id="chMulta" value="2">MULTA
		</td>
		<td style="padding-right:5px"><input type="text" id="txtBuscodigo" name="txtBuscodigo" class="caja" value="" style="width:100px;"/></td>
		<td style="padding-right:5px">
			<input type="button" id="btnBuscarxcodigo" id="btnBuscarxcodigo" value="Buscar" style="width:100px;"/>
		</td>
		</tr>
		</table>
		</div>

   	  <div id="gridRecContri" aling="center"></div>
	  
      <div style="margin:10px 0 0 0">
		  <table style='float:left'>
		  <tr>
			<td style='padding-right:5px'><div style="background-color:#FFFFFF; border:1px #333 solid; width:15px; height:15px"></div></td><td style='font-size:10px'>Ordinario&nbsp;</td>
			<td style='padding-right:5px'><div style="background-color:#2E9AFE; border:1px #333 solid; width:15px; height:15px"></div></td><td style='font-size:10px'>Valor Tributario&nbsp;</td>
			<td style='padding-right:5px'><div style="background-color:#8017C6; border:1px #333 solid; width:15px; height:15px"></div></td><td style='font-size:10px'>Coactivo&nbsp;</td>
	      </tr>
		  <tr>
		  	<td style="height:10px" colspan="6"></td>
		  </tr>
		  <tr>
			<td style='padding-right:5px'><div style="background-color:#4EC617; border:1px #333 solid; width:15px; height:15px"></div></td><td style='font-size:10px'>Fraccionado&nbsp;</td>
			<td style='padding-right:5px'><div style="background-color:#FF8000; border:1px #333 solid; width:15px; height:15px"></div></td><td style='font-size:10px'>Fiscalizado&nbsp;</td>
			<td style='padding-right:5px'>&nbsp;</td><td style='font-size:10px'>&nbsp;</td>
			</tr>
		  </table>
		  <table style='float:right; margin-right:30px'>
		  <tr>
			<td style="padding-right:5px"><input name="txtinso" type="text" id="txtinso" value="0.00" class="cajaoff" style="text-align:right; width:95px;" readonly></td>
			<td style="padding-right:5px"><input name="txtreaj" type="text" id="txtreaj" value="0.00" class="cajaoff" style="text-align:right; width:95px;" readonly></td>
			<td style="padding-right:5px"><input name="txtmora" type="text" id="txtmora" value="0.00" class="cajaoff" style="text-align:right; width:95px;" readonly></td>
			<td style="padding-right:5px"><input name="txtemis" type="text" id="txtemis" value="0.00" class="cajaoff" style="text-align:right; width:95px;" readonly></td>
			<td style="padding-right:5px"><input name="txtbenef" type="text" id="txtbenef" value="0.00" class="cajaoff" style="text-align:right; width:95px;" readonly></td>
			<td style="padding-right:5px"><input name="txt_total" type="text" id="txt_total" value="0.00" class="cajaoff" style="text-align:right; width:95px;" readonly></td>
		  </tr>
		  </table>
      </div>
  </div>
</form>
