<?php header('Content-Type: text/html; charset=iso-8859-1'); ?>
<script>
	var tiporec = '<?php echo $this->tiporec; ?>';
</script>
<script type="text/javascript" src="<?php echo $this->ruta; ?>js/js_tesocaja_tupadatconcep.js"></script>
<form id="frmContri">
<div id="contentBox" class="ui-content-tabs">
	<ul>
    	<li class="contentBoxHead" style="padding:0 0 2px 5px"><?php echo $this->title;?></li>
    </ul>
    <div id="contenidoForm" class="contentBox">
	    <fieldset class="ui-widget ui-widget-content">
		    <legend style="margin-left:5px">Datos del Pago:</legend>
	        <div class="contentForm">
	   		<table class="tableContent">
			<!--
				<tr>
				<td><span>Concepto: </span></td>
				<td>
					<input type="text" class="caja" style="width:400px" />
					<input type="hidden" id="oculto" class="caja" style="width:400px" />
				</td>
				</tr>
				<tr>
				<td><span>Contribuyente Nro.Doc.:</span></td>
				<td><input id="nrodocu" type="text" class="caja" style="width:200px" /></td>
				</tr>
			-->
				<tr>
				<td><span>Contribuyente Nombre: </span></td>
				<td><input id="contribuyente" type="text" class="caja" style="width:600px" /></td>
				</tr>
				<tr>
                  <td><span>Referencia: </span></td>
				  <td><input id="referencia" type="text" class="caja" style="width:600px" /></td>
			  </tr>
			  <tr>
                  <td><span>Observacion: </span></td>
				  <td><input id="observacion" type="text" class="caja" style="width:600px" /></td>
			  </tr>
				<tr>
                  <td><span>Tipo de Tarjeta: </span></td>
				  <td><select name="cmbtarjeta" id="cmbtarjeta" class="combo" style="width:200px"></select></td>
			  </tr>
			</table>
	    	</div>
	    </fieldset>		
	    <div id="gridTesoDetaTupa"></div>

		  <div class="divButtons" align="center">
			<table class="hovertable">
			  <tr>
				<td>
					<table width="100%">
					  <tr>
						<th><span>Monto</span></th>
						<th><span>Cantidad</span></th>
						<th><span>Total</span></th>
					  </tr>
					  <tr>
						<td>
						
						<input type="hidden" id="tipooculto" class="caja" style="width:400px" />
						<input type="hidden" id="tiporecoculto" class="caja" style="width:400px" />
						<input name="txtprecio" type="text" class="caja" id="txtprecio" style="width:80px;text-align:right" maxlength="12" value="0.00"></td>
						<td><input name="txtcantidad" type="text" class="caja" id="txtcantidad" style="width:80px;text-align:right" maxlength="12" value="1"></td>
						<td><input name="txttotal" type="text" class="cajaoff" id="txttotal" style="width:80px;text-align:right" maxlength="12" value="0.00" readonly ></td>
					  </tr>
				  </table>
				 </td>
			  </tr>
			</table>
			<br/>
			<table border="0" cellpadding="0" cellspacing="0" width="25%">
			<tr>
			<td style="padding-left:5px">
			  <label>
			  <input name="rdformaPago" id="rdformaPago1" type="radio" value="E" checked/><b>Efectivo</b>
			  </label>
			  </td>
			  <td>
			  <label>
			  <input name="rdformaPago" id="rdformaPago2" type="radio" value="C" /><b>Cheque</b>
			  </label>
			  </td>
			  <td>
			  <label>
			  <input name="rdformaPago" id="rdformaPago3" type="radio" value="T" /><b>Tarjeta</b>
			  </label>
			</td>
			<td> &nbsp </td>
			<td> &nbsp </td>
				<td><input type="button" id="btnPagar" value="Pagar" /></td>
				<td> &nbsp </td>
			</tr>
			
			</table>
		  </div>
		<div id="div_pintaboton"></div>
    </div>
</div>
</form>